// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-10-10 17:09:33
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: hdlsrc_64k
// EDAScriptGeneration: off
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp 
// GenerateHDLTestBench: off

// Filter Specifications:
//
// Sample Rate   : N/A (normalized frequency)
// Response      : Highpass
// Specification : N,F3dB
// 3-dB Point    : 3.125e-06
// Filter Order  : 1
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 1
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s24,22 -> [-2 2)
// Denominator         : s24,22 -> [-2 2)
// Scale Values        : s24,23 -> [-1 1)
// Input               : s33,0 -> [-4294967296 4294967296)
// Section Input       : s33,0 -> [-4294967296 4294967296)
// Section Output      : s33,0 -> [-4294967296 4294967296)
// Output              : s33,0 -> [-4294967296 4294967296)
// State               : s50,0 -> [-562949953421312 562949953421312)
// Numerator Prod      : s74,22 -> [-2251799813685248 2251799813685248)
// Denominator Prod    : s74,22 -> [-2251799813685248 2251799813685248)
// Numerator Accum     : s76,22 -> [-9007199254740992 9007199254740992)
// Denominator Accum   : s76,22 -> [-9007199254740992 9007199254740992)
// Round Mode          : convergent
// Overflow Mode       : saturate
// -------------------------------------------------------------
// Multipliers           : 2



`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [32:0] filter_in; //sfix33
  output  signed [32:0] filter_out; //sfix33

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [23:0] scaleconst1 = 24'b011111111111111111010111; //sfix24_En23
  parameter signed [23:0] coeff_b1_section1 = 24'b010000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b2_section1 = 24'b110000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b3_section1 = 24'b000000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_a2_section1 = 24'b110000000000000000101001; //sfix24_En22
  parameter signed [23:0] coeff_a3_section1 = 24'b000000000000000000000000; //sfix24_En22
  // Signals
  reg  signed [32:0] input_register; // sfix33
  wire signed [56:0] scale1; // sfix57_En23
  wire signed [32:0] scaletypeconvert1; // sfix33
  //   -- Section 1 Signals 
  wire signed [75:0] a1sum1; // sfix76_En22
  wire signed [75:0] b1sum1; // sfix76_En22
  wire signed [49:0] a1sumtypeconvert1; // sfix50
  reg  signed [49:0] delay_section1; // sfix50
  wire signed [75:0] inputconv1; // sfix76_En22
  wire signed [73:0] a2mul1; // sfix74_En22
  wire signed [73:0] b1mul1; // sfix74_En22
  wire signed [73:0] b2mul1; // sfix74_En22
  wire signed [50:0] unaryminus_temp; // sfix51
  wire signed [75:0] sub_cast; // sfix76_En22
  wire signed [75:0] sub_cast_1; // sfix76_En22
  wire signed [76:0] sub_temp; // sfix77_En22
  wire signed [75:0] b1multypeconvert1; // sfix76_En22
  wire signed [75:0] add_cast; // sfix76_En22
  wire signed [75:0] add_cast_1; // sfix76_En22
  wire signed [76:0] add_temp; // sfix77_En22
  wire signed [32:0] output_typeconvert; // sfix33
  reg  signed [32:0] output_register; // sfix33

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  assign scale1 = input_register * scaleconst1;

  assign scaletypeconvert1 = ((scale1[56] == 1'b0 & scale1[55] != 1'b0) || (scale1[56] == 1'b0 && scale1[55:23] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (scale1[56] == 1'b1 && scale1[55] != 1'b1) ? 33'b100000000000000000000000000000000 : (scale1[55:0] + {scale1[23], {22{~scale1[23]}}})>>>23;

  //   ------------------ Section 1 (First Order) ------------------

  assign a1sumtypeconvert1 = ((a1sum1[75] == 1'b0 & a1sum1[74:71] != 4'b0000) || (a1sum1[75] == 1'b0 && a1sum1[71:22] == 50'b01111111111111111111111111111111111111111111111111) // special case0
) ? 50'b01111111111111111111111111111111111111111111111111 : 
      (a1sum1[75] == 1'b1 && a1sum1[74:71] != 4'b1111) ? 50'b10000000000000000000000000000000000000000000000000 : (a1sum1[71:0] + {a1sum1[22], {21{~a1sum1[22]}}})>>>22;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section1
      if (reset == 1'b1) begin
        delay_section1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section1 <= a1sumtypeconvert1;
        end
      end
    end // delay_process_section1

  assign inputconv1 = $signed({scaletypeconvert1, 22'b0000000000000000000000});

  assign a2mul1 = delay_section1 * coeff_a2_section1;

  assign b1mul1 = $signed({a1sumtypeconvert1, 22'b0000000000000000000000});

  assign unaryminus_temp = (delay_section1==50'b10000000000000000000000000000000000000000000000000) ? $signed({1'b0, delay_section1}) : -delay_section1;
  assign b2mul1 = $signed({unaryminus_temp, 22'b0000000000000000000000});

  assign sub_cast = inputconv1;
  assign sub_cast_1 = $signed({{2{a2mul1[73]}}, a2mul1});
  assign sub_temp = sub_cast - sub_cast_1;
  assign a1sum1 = ((sub_temp[76] == 1'b0 & sub_temp[75] != 1'b0) || (sub_temp[76] == 1'b0 && sub_temp[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (sub_temp[76] == 1'b1 && sub_temp[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : sub_temp[75:0];

  assign b1multypeconvert1 = $signed({{2{b1mul1[73]}}, b1mul1});

  assign add_cast = b1multypeconvert1;
  assign add_cast_1 = $signed({{2{b2mul1[73]}}, b2mul1});
  assign add_temp = add_cast + add_cast_1;
  assign b1sum1 = ((add_temp[76] == 1'b0 & add_temp[75] != 1'b0) || (add_temp[76] == 1'b0 && add_temp[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp[76] == 1'b1 && add_temp[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp[75:0];

  assign output_typeconvert = ((b1sum1[75] == 1'b0 & b1sum1[74:54] != 21'b000000000000000000000) || (b1sum1[75] == 1'b0 && b1sum1[54:22] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (b1sum1[75] == 1'b1 && b1sum1[74:54] != 21'b111111111111111111111) ? 33'b100000000000000000000000000000000 : (b1sum1[54:0] + {b1sum1[22], {21{~b1sum1[22]}}})>>>22;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
