// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-11-07 16:23:31
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// EDAScriptGeneration: off
// SerialPartition: 32
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully Serial
// Folding Factor        : 32
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 32
// Stable            : Yes
// Linear Phase      : Yes (Type 2)
// Arithmetic        : fixed
// Numerator         : s18,18 -> [-5.000000e-01 5.000000e-01)
// Input             : s33,0 -> [-4294967296 4294967296)
// Filter Internals  : Specify Precision
//   Output          : s33,0 -> [-4294967296 4294967296)
//   Product         : s52,18 -> [-8589934592 8589934592)
//   Accumulator     : s53,18 -> [-17179869184 17179869184)
//   Round Mode      : convergent
//   Overflow Mode   : saturate
// -------------------------------------------------------------
// Multipliers           : 1



`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [32:0] filter_in; //sfix33
  output  signed [32:0] filter_out; //sfix33

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [17:0] coeff1 = 18'b111111110101011001; //sfix18_En18
  parameter signed [17:0] coeff2 = 18'b111111011001001111; //sfix18_En18
  parameter signed [17:0] coeff3 = 18'b111110110111111011; //sfix18_En18
  parameter signed [17:0] coeff4 = 18'b111110100010001010; //sfix18_En18
  parameter signed [17:0] coeff5 = 18'b111110110110110100; //sfix18_En18
  parameter signed [17:0] coeff6 = 18'b111111111010000001; //sfix18_En18
  parameter signed [17:0] coeff7 = 18'b000001001111000001; //sfix18_En18
  parameter signed [17:0] coeff8 = 18'b000001111000001101; //sfix18_En18
  parameter signed [17:0] coeff9 = 18'b000001000100000010; //sfix18_En18
  parameter signed [17:0] coeff10 = 18'b111110111010001001; //sfix18_En18
  parameter signed [17:0] coeff11 = 18'b111100110001000011; //sfix18_En18
  parameter signed [17:0] coeff12 = 18'b111100100111111110; //sfix18_En18
  parameter signed [17:0] coeff13 = 18'b111111110111111101; //sfix18_En18
  parameter signed [17:0] coeff14 = 18'b000110001001101110; //sfix18_En18
  parameter signed [17:0] coeff15 = 18'b001101001010110011; //sfix18_En18
  parameter signed [17:0] coeff16 = 18'b010001110010011111; //sfix18_En18
  parameter signed [17:0] coeff17 = 18'b010001110010011111; //sfix18_En18
  parameter signed [17:0] coeff18 = 18'b001101001010110011; //sfix18_En18
  parameter signed [17:0] coeff19 = 18'b000110001001101110; //sfix18_En18
  parameter signed [17:0] coeff20 = 18'b111111110111111101; //sfix18_En18
  parameter signed [17:0] coeff21 = 18'b111100100111111110; //sfix18_En18
  parameter signed [17:0] coeff22 = 18'b111100110001000011; //sfix18_En18
  parameter signed [17:0] coeff23 = 18'b111110111010001001; //sfix18_En18
  parameter signed [17:0] coeff24 = 18'b000001000100000010; //sfix18_En18
  parameter signed [17:0] coeff25 = 18'b000001111000001101; //sfix18_En18
  parameter signed [17:0] coeff26 = 18'b000001001111000001; //sfix18_En18
  parameter signed [17:0] coeff27 = 18'b111111111010000001; //sfix18_En18
  parameter signed [17:0] coeff28 = 18'b111110110110110100; //sfix18_En18
  parameter signed [17:0] coeff29 = 18'b111110100010001010; //sfix18_En18
  parameter signed [17:0] coeff30 = 18'b111110110111111011; //sfix18_En18
  parameter signed [17:0] coeff31 = 18'b111111011001001111; //sfix18_En18
  parameter signed [17:0] coeff32 = 18'b111111110101011001; //sfix18_En18

  // Signals
  reg  [4:0] cur_count; // ufix5
  wire phase_31; // boolean
  wire phase_0; // boolean
  reg  signed [32:0] delay_pipeline [0:31] ; // sfix33
  wire signed [32:0] inputmux_1; // sfix33
  reg  signed [52:0] acc_final; // sfix53_En18
  reg  signed [52:0] acc_out_1; // sfix53_En18
  wire signed [51:0] product_1; // sfix52_En18
  wire signed [17:0] product_1_mux; // sfix18_En18
  wire signed [50:0] mul_temp; // sfix51_En18
  wire signed [52:0] prod_typeconvert_1; // sfix53_En18
  wire signed [52:0] acc_sum_1; // sfix53_En18
  wire signed [52:0] acc_in_1; // sfix53_En18
  wire signed [52:0] add_signext; // sfix53_En18
  wire signed [52:0] add_signext_1; // sfix53_En18
  wire signed [53:0] add_temp; // sfix54_En18
  wire signed [32:0] output_typeconvert; // sfix33
  reg  signed [32:0] output_register; // sfix33

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: Counter_process
      if (reset == 1'b1) begin
        cur_count <= 5'b11111;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 5'b11111) begin
            cur_count <= 5'b00000;
          end
          else begin
            cur_count <= cur_count + 5'b00001;
          end
        end
      end
    end // Counter_process

  assign  phase_31 = (cur_count == 5'b11111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_0 = (cur_count == 5'b00000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
      end
      else begin
        if (phase_31 == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
        end
      end
    end // Delay_Pipeline_process


  assign inputmux_1 = (cur_count == 5'b00000) ? delay_pipeline[0] :
                     (cur_count == 5'b00001) ? delay_pipeline[1] :
                     (cur_count == 5'b00010) ? delay_pipeline[2] :
                     (cur_count == 5'b00011) ? delay_pipeline[3] :
                     (cur_count == 5'b00100) ? delay_pipeline[4] :
                     (cur_count == 5'b00101) ? delay_pipeline[5] :
                     (cur_count == 5'b00110) ? delay_pipeline[6] :
                     (cur_count == 5'b00111) ? delay_pipeline[7] :
                     (cur_count == 5'b01000) ? delay_pipeline[8] :
                     (cur_count == 5'b01001) ? delay_pipeline[9] :
                     (cur_count == 5'b01010) ? delay_pipeline[10] :
                     (cur_count == 5'b01011) ? delay_pipeline[11] :
                     (cur_count == 5'b01100) ? delay_pipeline[12] :
                     (cur_count == 5'b01101) ? delay_pipeline[13] :
                     (cur_count == 5'b01110) ? delay_pipeline[14] :
                     (cur_count == 5'b01111) ? delay_pipeline[15] :
                     (cur_count == 5'b10000) ? delay_pipeline[16] :
                     (cur_count == 5'b10001) ? delay_pipeline[17] :
                     (cur_count == 5'b10010) ? delay_pipeline[18] :
                     (cur_count == 5'b10011) ? delay_pipeline[19] :
                     (cur_count == 5'b10100) ? delay_pipeline[20] :
                     (cur_count == 5'b10101) ? delay_pipeline[21] :
                     (cur_count == 5'b10110) ? delay_pipeline[22] :
                     (cur_count == 5'b10111) ? delay_pipeline[23] :
                     (cur_count == 5'b11000) ? delay_pipeline[24] :
                     (cur_count == 5'b11001) ? delay_pipeline[25] :
                     (cur_count == 5'b11010) ? delay_pipeline[26] :
                     (cur_count == 5'b11011) ? delay_pipeline[27] :
                     (cur_count == 5'b11100) ? delay_pipeline[28] :
                     (cur_count == 5'b11101) ? delay_pipeline[29] :
                     (cur_count == 5'b11110) ? delay_pipeline[30] :
                     delay_pipeline[31];

  //   ------------------ Serial partition # 1 ------------------

  assign product_1_mux = (cur_count == 5'b00000) ? coeff1 :
                        (cur_count == 5'b00001) ? coeff2 :
                        (cur_count == 5'b00010) ? coeff3 :
                        (cur_count == 5'b00011) ? coeff4 :
                        (cur_count == 5'b00100) ? coeff5 :
                        (cur_count == 5'b00101) ? coeff6 :
                        (cur_count == 5'b00110) ? coeff7 :
                        (cur_count == 5'b00111) ? coeff8 :
                        (cur_count == 5'b01000) ? coeff9 :
                        (cur_count == 5'b01001) ? coeff10 :
                        (cur_count == 5'b01010) ? coeff11 :
                        (cur_count == 5'b01011) ? coeff12 :
                        (cur_count == 5'b01100) ? coeff13 :
                        (cur_count == 5'b01101) ? coeff14 :
                        (cur_count == 5'b01110) ? coeff15 :
                        (cur_count == 5'b01111) ? coeff16 :
                        (cur_count == 5'b10000) ? coeff17 :
                        (cur_count == 5'b10001) ? coeff18 :
                        (cur_count == 5'b10010) ? coeff19 :
                        (cur_count == 5'b10011) ? coeff20 :
                        (cur_count == 5'b10100) ? coeff21 :
                        (cur_count == 5'b10101) ? coeff22 :
                        (cur_count == 5'b10110) ? coeff23 :
                        (cur_count == 5'b10111) ? coeff24 :
                        (cur_count == 5'b11000) ? coeff25 :
                        (cur_count == 5'b11001) ? coeff26 :
                        (cur_count == 5'b11010) ? coeff27 :
                        (cur_count == 5'b11011) ? coeff28 :
                        (cur_count == 5'b11100) ? coeff29 :
                        (cur_count == 5'b11101) ? coeff30 :
                        (cur_count == 5'b11110) ? coeff31 :
                        coeff32;
  assign mul_temp = inputmux_1 * product_1_mux;
  assign product_1 = $signed({{1{mul_temp[50]}}, mul_temp});

  assign prod_typeconvert_1 = $signed({{1{product_1[51]}}, product_1});

  assign add_signext = prod_typeconvert_1;
  assign add_signext_1 = acc_out_1;
  assign add_temp = add_signext + add_signext_1;
  assign acc_sum_1 = add_temp[52:0];

  assign acc_in_1 = (phase_0 == 1'b1) ? prod_typeconvert_1 :
                   acc_sum_1;

  always @ (posedge clk or posedge reset)
    begin: Acc_reg_1_process
      if (reset == 1'b1) begin
        acc_out_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          acc_out_1 <= acc_in_1;
        end
      end
    end // Acc_reg_1_process

  always @ (posedge clk or posedge reset)
    begin: Finalsum_reg_process
      if (reset == 1'b1) begin
        acc_final <= 0;
      end
      else begin
        if (phase_0 == 1'b1) begin
          acc_final <= acc_out_1;
        end
      end
    end // Finalsum_reg_process

  assign output_typeconvert = ((acc_final[52] == 1'b0 & acc_final[51:50] != 2'b00) || (acc_final[52] == 1'b0 && acc_final[50:18] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (acc_final[52] == 1'b1 && acc_final[51:50] != 2'b11) ? 33'b100000000000000000000000000000000 : (acc_final[50:0] + {acc_final[18], {17{~acc_final[18]}}})>>>18;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_31 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
