// MAX TB Test Protocol File, generated by MAX TB Version T-2022.03-SP1
// Tue Jun 18 16:20:25 2024
// Module under test: Nanochap_ENS2
// Generated from original STIL file : "../data/atpg_patterns_postscan/pattern_seri.stil"
// STIL file version: "1.0"
// Enhanced Runtime Version: use <sim_exec> +tmax_help for available runtime options
// Simulation mode: default serial simulation
`timescale 1ns/1ps

module /* maxtb */ tb_chip_top ();
   parameter NSTMTS = 19; // number of all stmts
   parameter DFSHIFTS = 0; // (default) number of serial shifts in parallel scan mode
   parameter NAMELENGTH = 200; // max length of names reported in fails
   parameter FILELENGTH = 1024; // max length for file names 
   parameter MAXCHLEN = 940, NCHAINS = 5;
   parameter NINPUTS = 29, NOUTPUTS = 25, CUM_WIDTH=124;
   parameter NSIS = 5, NSOUTS = 5;
   parameter WFT_IDS = 2, SIG_IDS = 36, SIG_IDS_W = 6, MAX_WIDTH = 29, MAX_SIGW = 1;
   parameter PARSERINC = 940; 
   parameter SYNC_LATENCY = 3; 
   parameter PRTIME = 0.000000; 
   integer xtb_sim_mode; // simulation modes: xtb_sim_mode=0 -> serial, xtb_sim_mode=1 -> parallel (default);
   integer nbfails, abit, cbit;
   integer prev_error; // flag for tracking displayed error banner
   integer loads;        // number of load_unloads for current pattern
   integer prev_pat;     // previous pattern number;
   integer rep_pat; // report pattern progress every Nth pattern
   integer verbose;      // message verbosity level
   integer debug;      // enable debug level
   integer test_setup_runs; // counts the number of executed test_setups
   integer test_setup_only_once; // flag to trigger only one execution of test_setup
   integer data_i, n, cur_pat, start_pat, end_pat, last_pat, total_pats, csci, fsci, cur_stmt;
   integer v_count, v_count_per_pat;  // track the cycle count and cycle/pattern count (helpful for the simulator GUI)
   integer v_count_per_stmt;  // track the cycle count per statement (procedure or macro)
   integer SSHIFTS;
   integer diagf, diagm;
   integer sertmg;
   integer the_wft_id, wft_id_s;
   integer ser_pats;
   integer first_pat;
   event start_part, end_part;
   event error_ev;
   `define NBRTOPS 9
   integer csim_op;
   reg [32*8:1] RT_OPS [0:`NBRTOPS];
   integer      rt_ops [0:`NBRTOPS-1];
   integer      tdfm;
   integer lp_addr, lp_count, lp_max;
   reg [0:(8*FILELENGTH)-1] TDATA_FILE;

   reg [MAX_SIGW*(NINPUTS+NOUTPUTS)-1:0] ALLINSIGS, ALLOUTSIGS;
   reg [MAX_SIGW*(NINPUTS+NOUTPUTS)-1:0] TMPINSIGS_V,TMPINSIGS_T,TMPINSIGS_V_S,TMPINSIGS_T_S;
   reg [MAX_SIGW*(NINPUTS+NOUTPUTS)-1:0] TMPOUTSIGS_V,TMPOUTSIGS_T,TMPOUTSIGS_V_S,TMPOUTSIGS_T_S;
   reg [NINPUTS+NOUTPUTS-1:0] ALLINSIGIDS, ALLOUTSIGIDS, ALLINSIGIDS_S, ALLOUTSIGIDS_S;
   reg [NSTMTS-1:0] opcode, popcode;
   event force_scells;
   event strobe_scells;
   event release_scells;
   reg [945:0] memel, memall [1:19843];
   reg [0:(8*NAMELENGTH)-1] CH_NAMES [0:NCHAINS-1];
   reg [0:(8*NAMELENGTH)-1] CH_PINS [0:NCHAINS-1];
   reg [0:MAXCHLEN-1] LOD, LOAD[0:NCHAINS-1];
   reg [0:MAXCHLEN-1] UNL, UNLOAD[0:NCHAINS-1];
   reg [0:MAXCHLEN-1] UNLM;
   reg [0:MAXCHLEN-1] SERIALM;
   reg [0:MAXCHLEN-1] CH_INPINV[0:NCHAINS-1], CH_OUTINV[0:NCHAINS-1];
   reg [0:MAXCHLEN-1] CT_OUTINV[0:NCHAINS-1];
   wire [0:NCHAINS-1] SCANOUT;
   reg [0:MAXCHLEN-1] CHOUT, CHAINOUT[0:NCHAINS-1];
   reg [0:MAXCHLEN-1] CHAINOUT0,  CHAINOUT1,  CHAINOUT2,  CHAINOUT3,  CHAINOUT4;
   reg [0:MAXCHLEN-1] LOD0,  LOD1,  LOD2,  LOD3,  LOD4;
   reg strobe_en;
   reg [SIG_IDS-1:0] sid_args ;
   reg [2*CUM_WIDTH-1:0] sval_args;
   reg [5:0] the_sids [0:SIG_IDS-1];
   reg [8*NAMELENGTH-1:0]  SignalIDName [0:35];
   reg [2:0]  SignalIDType [0:35];
   reg [4:0]  SignalIDWidth [0:35];
   reg [(8*NAMELENGTH-1):0]  WFTIDName [0:1];
   reg [0:(8*FILELENGTH)-1] diag_file;
   reg [0:(8*NAMELENGTH-1)] StmtNames [0:NSTMTS];

   reg CLKSEL_con ;
   reg iopad_testmode0_con ;
   reg iopad_testmode1_con ;
   reg RESETn_con ;
   reg VPP_con ;
   wire \w_VPP_con ;
   reg VDDIO_con ;
   wire \w_VDDIO_con ;
   reg VSSIO_con ;
   wire \w_VSSIO_con ;
   reg VDD_DIG_con ;
   wire \w_VDD_DIG_con ;
   reg VDD_DIG_SW_con ;
   wire \w_VDD_DIG_SW_con ;
   reg VDD_DIG_AO_con ;
   wire \w_VDD_DIG_AO_con ;
   reg VSS_DIG_con ;
   wire \w_VSS_DIG_con ;
   reg VSS_DIG_AO_con ;
   wire \w_VSS_DIG_AO_con ;
   reg \IOBUF_PAD[15]  ;
   wire \w_\IOBUF_PAD[15]  ;
   reg \IOBUF_PAD[14]  ;
   wire \w_\IOBUF_PAD[14]  ;
   reg \IOBUF_PAD[13]  ;
   wire \w_\IOBUF_PAD[13]  ;
   reg \IOBUF_PAD[12]  ;
   wire \w_\IOBUF_PAD[12]  ;
   reg \IOBUF_PAD[11]  ;
   wire \w_\IOBUF_PAD[11]  ;
   reg \IOBUF_PAD[10]  ;
   wire \w_\IOBUF_PAD[10]  ;
   reg \IOBUF_PAD[9]  ;
   wire \w_\IOBUF_PAD[9]  ;
   reg \IOBUF_PAD[8]  ;
   wire \w_\IOBUF_PAD[8]  ;
   reg \IOBUF_PAD[7]  ;
   wire \w_\IOBUF_PAD[7]  ;
   reg \IOBUF_PAD[6]  ;
   wire \w_\IOBUF_PAD[6]  ;
   reg \IOBUF_PAD[5]  ;
   wire \w_\IOBUF_PAD[5]  ;
   reg \IOBUF_PAD[4]  ;
   wire \w_\IOBUF_PAD[4]  ;
   reg \IOBUF_PAD[3]  ;
   wire \w_\IOBUF_PAD[3]  ;
   reg \IOBUF_PAD[2]  ;
   wire \w_\IOBUF_PAD[2]  ;
   reg \IOBUF_PAD[1]  ;
   wire \w_\IOBUF_PAD[1]  ;
   reg \IOBUF_PAD[0]  ;
   wire \w_\IOBUF_PAD[0]  ;
   reg CLK_con ;
   wire \w_CLK_con ;

   wire [0:(8*NAMELENGTH-1)] cur_StmtName;
   assign cur_StmtName = StmtNames[cur_stmt] ;

   assign \w_VPP_con = VPP_con ;
   assign \w_VDDIO_con = VDDIO_con ;
   assign \w_VSSIO_con = VSSIO_con ;
   assign \w_VDD_DIG_con = VDD_DIG_con ;
   assign \w_VDD_DIG_SW_con = VDD_DIG_SW_con ;
   assign \w_VDD_DIG_AO_con = VDD_DIG_AO_con ;
   assign \w_VSS_DIG_con = VSS_DIG_con ;
   assign \w_VSS_DIG_AO_con = VSS_DIG_AO_con ;
   assign \w_\IOBUF_PAD[15]  = \IOBUF_PAD[15]  ;
   assign \w_\IOBUF_PAD[14]  = \IOBUF_PAD[14]  ;
   assign \w_\IOBUF_PAD[13]  = \IOBUF_PAD[13]  ;
   assign \w_\IOBUF_PAD[12]  = \IOBUF_PAD[12]  ;
   assign \w_\IOBUF_PAD[11]  = \IOBUF_PAD[11]  ;
   assign \w_\IOBUF_PAD[10]  = \IOBUF_PAD[10]  ;
   assign \w_\IOBUF_PAD[9]  = \IOBUF_PAD[9]  ;
   assign \w_\IOBUF_PAD[8]  = \IOBUF_PAD[8]  ;
   assign \w_\IOBUF_PAD[7]  = \IOBUF_PAD[7]  ;
   assign \w_\IOBUF_PAD[6]  = \IOBUF_PAD[6]  ;
   assign \w_\IOBUF_PAD[5]  = \IOBUF_PAD[5]  ;
   assign \w_\IOBUF_PAD[4]  = \IOBUF_PAD[4]  ;
   assign \w_\IOBUF_PAD[3]  = \IOBUF_PAD[3]  ;
   assign \w_\IOBUF_PAD[2]  = \IOBUF_PAD[2]  ;
   assign \w_\IOBUF_PAD[1]  = \IOBUF_PAD[1]  ;
   assign \w_\IOBUF_PAD[0]  = \IOBUF_PAD[0]  ;
   assign \w_CLK_con = CLK_con ;

   Nanochap_ENS2 dut ( 
     .CLKSEL ( CLKSEL_con ),
     .iopad_testmode0 ( iopad_testmode0_con ),
     .iopad_testmode1 ( iopad_testmode1_con ),
     .RESETn ( RESETn_con ),
     .VPP ( \w_VPP_con ),
     .VDDIO ( \w_VDDIO_con ),
     .VSSIO ( \w_VSSIO_con ),
     .VDD_DIG ( \w_VDD_DIG_con ),
     .VDD_DIG_SW ( \w_VDD_DIG_SW_con ),
     .VDD_DIG_AO ( \w_VDD_DIG_AO_con ),
     .VSS_DIG ( \w_VSS_DIG_con ),
     .VSS_DIG_AO ( \w_VSS_DIG_AO_con ),
     .IOBUF_PAD ( { \w_\IOBUF_PAD[15] ,
        \w_\IOBUF_PAD[14] ,
        \w_\IOBUF_PAD[13] ,
        \w_\IOBUF_PAD[12] ,
        \w_\IOBUF_PAD[11] ,
        \w_\IOBUF_PAD[10] ,
        \w_\IOBUF_PAD[9] ,
        \w_\IOBUF_PAD[8] ,
        \w_\IOBUF_PAD[7] ,
        \w_\IOBUF_PAD[6] ,
        \w_\IOBUF_PAD[5] ,
        \w_\IOBUF_PAD[4] ,
        \w_\IOBUF_PAD[3] ,
        \w_\IOBUF_PAD[2] ,
        \w_\IOBUF_PAD[1] ,
        \w_\IOBUF_PAD[0] } ),
     .CLK ( \w_CLK_con )
  );

 endmodule
