// -------------------------------------------------------------
//
// Module: filter_comp
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-08-05 17:17:35
// -------------------------------------------------------------
//========================================================================================  
// ----------------------------------------------------------------------------- 
//  Nanochap Electronics Copyright (C) 2014. ALL RIGHTS RESERVED. 
// ----------------------------------------------------------------------------- 
// Module name     : filter_fir_lpf
// Description     : this is LOW-PASS filter; the order is 19
// ======================================================================================= 
// =sinc_osr_sel :
// =value 4'h0 - 4'h1 - 4'h2 - 4'h3 - 4'h4 - 4'h5 - 4'h6 - 4'h7 - 4'h8 - 4'h9 - 4'ha - 4'hb  
// =OSR                  32  - 64   - 128  - 256  - 512  - 1024 
// =Fs                   64k   32k    16k    8k     4K     2k    //hz
// =Fpass                8192  4096   2048   1024   512     256  //hz
// =Fstop                16348 8192   4096   2048   1024    512  //hz
// =Wpass                1     1      1      1      1       1     //dB
// =Wstop   80    80     80    80     80     80     80      80    //dB
// ======================================================================================= 
// =sign_en:
// =value        1'b0     -   1'b1 
// =signed?    unsigned   -  signed   
// ======================================================================================= 
// ----------------------------------------------------------------------------- 
// Revision History: 
// ----------------------------------------------------------------------------- 
// Revision       Date(xxxx-xx-xx)     Author             Description 
// ----------------------------------------------------------------------------- 
//   1.0          2025-8-25         Zhen Cao           Initial version 
// ----------------------------------------------------------------------------- 
//======================================================================================== 


module filter_fir_lpf
               (
                clk,
                clk_enable,
                reset,
		sign_en,
                filter_in,
//                sinc_osr_sel,	                
		bypass,
		o_cur_count,		
		lpf_coeff_data,
		filter_out_en,		
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   sign_en;   
  input   bypass; 
  output   wire  [4:0]  o_cur_count;  
//  input [3:0] sinc_osr_sel;
  
  input wire signed [17:0]  lpf_coeff_data [31:0];
  output                filter_out_en;  
  input   signed [31:0] filter_in; //sfix33
  output  signed [31:0] filter_out; //sfix33

wire signed [17:0] coeff1 ;
wire signed [17:0] coeff2 ;
wire signed [17:0] coeff3 ;
wire signed [17:0] coeff4 ;
wire signed [17:0] coeff5 ;
wire signed [17:0] coeff6 ;
wire signed [17:0] coeff7 ;
wire signed [17:0] coeff8 ;
wire signed [17:0] coeff9 ;
wire signed [17:0] coeff10;
wire signed [17:0] coeff11;
wire signed [17:0] coeff12;
wire signed [17:0] coeff13;
wire signed [17:0] coeff14;
wire signed [17:0] coeff15;
wire signed [17:0] coeff16;
wire signed [17:0] coeff17;
wire signed [17:0] coeff18;
wire signed [17:0] coeff19;
wire signed [17:0] coeff20;
wire signed [17:0] coeff21;
wire signed [17:0] coeff22;
wire signed [17:0] coeff23;
wire signed [17:0] coeff24;
wire signed [17:0] coeff25;
wire signed [17:0] coeff26;
wire signed [17:0] coeff27;
wire signed [17:0] coeff28;
wire signed [17:0] coeff29;
wire signed [17:0] coeff30;
wire signed [17:0] coeff31;
wire signed [17:0] coeff32;

assign coeff1  = lpf_coeff_data[0];
assign coeff2  = lpf_coeff_data[1];
assign coeff3  = lpf_coeff_data[2];
assign coeff4  = lpf_coeff_data[3];
assign coeff5  = lpf_coeff_data[4];
assign coeff6  = lpf_coeff_data[5];
assign coeff7  = lpf_coeff_data[6];
assign coeff8  = lpf_coeff_data[7];
assign coeff9  = lpf_coeff_data[8];
assign coeff10 = lpf_coeff_data[9];
assign coeff11 = lpf_coeff_data[10];
assign coeff12 = lpf_coeff_data[11];
assign coeff13 = lpf_coeff_data[12];
assign coeff14 = lpf_coeff_data[13];
assign coeff15 = lpf_coeff_data[14];
assign coeff16 = lpf_coeff_data[15];
assign coeff17 = lpf_coeff_data[16];
assign coeff18 = lpf_coeff_data[17];
assign coeff19 = lpf_coeff_data[18];
assign coeff20 = lpf_coeff_data[19];
assign coeff21 = lpf_coeff_data[20];
assign coeff22 = lpf_coeff_data[21];
assign coeff23 = lpf_coeff_data[22];
assign coeff24 = lpf_coeff_data[23];
assign coeff25 = lpf_coeff_data[24];
assign coeff26 = lpf_coeff_data[25];
assign coeff27 = lpf_coeff_data[26];
assign coeff28 = lpf_coeff_data[27];
assign coeff29 = lpf_coeff_data[28];
assign coeff30 = lpf_coeff_data[29];
assign coeff31 = lpf_coeff_data[30];
assign coeff32 = lpf_coeff_data[31];

  // Signals
  reg  [4:0] cur_count; // ufix5
  assign o_cur_count = cur_count;
  
  wire phase_31; // boolean
  wire phase_0; // boolean
  reg  signed [32:0] delay_pipeline [0:31] ; // sfix33
  wire signed [32:0] inputmux_1; // sfix33
  reg  signed [52:0] acc_final; // sfix53_En18
  reg  signed [52:0] acc_out_1; // sfix53_En18
  wire signed [51:0] product_1; // sfix52_En18
  wire signed [17:0] product_1_mux; // sfix18_En18
  wire signed [50:0] mul_temp; // sfix51_En18
  wire signed [52:0] prod_typeconvert_1; // sfix53_En18
  wire signed [52:0] acc_sum_1; // sfix53_En18
  wire signed [52:0] acc_in_1; // sfix53_En18
  wire signed [52:0] add_signext; // sfix53_En18
  wire signed [52:0] add_signext_1; // sfix53_En18
  wire signed [53:0] add_temp; // sfix54_En18
  wire signed [32:0] output_typeconvert; // sfix33
  wire signed [32:0] output_register; // sfix33

  // Block Statements
  always @ (posedge clk or negedge reset)
    begin: Counter_process
      if (reset == 1'b0) begin
        cur_count <= 5'b11111;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 5'b11111) begin
            cur_count <= 5'b00000;
          end
          else begin
            cur_count <= cur_count + 5'b00001;
          end
        end
      end
    end // Counter_process

  assign  phase_31 = (cur_count == 5'b11111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_0 = (cur_count == 5'b00000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @( posedge clk or negedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b0) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
      end
      else begin
        if (phase_31 == 1'b1) begin
//          delay_pipeline[0] <= ~sign_en?  (filter_in==32'hffff_ffff)? 33'h8000_0000 :  (filter_in==32'h7fff_ffff)? 33'h0 : $signed({{2{~filter_in[31]}},filter_in[30:0]+1'b1}) : {{2{filter_in[31]}},filter_in[30:0]};
	  delay_pipeline[0] <=   ~sign_en?  $signed({1'b0,filter_in})-33'sh0_8000_0000 : {{2{filter_in[31]}},filter_in[30:0]};
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
        end
      end
    end // Delay_Pipeline_process


  assign inputmux_1 = (cur_count == 5'b00000) ? delay_pipeline[0] :
                     (cur_count == 5'b00001) ? delay_pipeline[1] :
                     (cur_count == 5'b00010) ? delay_pipeline[2] :
                     (cur_count == 5'b00011) ? delay_pipeline[3] :
                     (cur_count == 5'b00100) ? delay_pipeline[4] :
                     (cur_count == 5'b00101) ? delay_pipeline[5] :
                     (cur_count == 5'b00110) ? delay_pipeline[6] :
                     (cur_count == 5'b00111) ? delay_pipeline[7] :
                     (cur_count == 5'b01000) ? delay_pipeline[8] :
                     (cur_count == 5'b01001) ? delay_pipeline[9] :
                     (cur_count == 5'b01010) ? delay_pipeline[10] :
                     (cur_count == 5'b01011) ? delay_pipeline[11] :
                     (cur_count == 5'b01100) ? delay_pipeline[12] :
                     (cur_count == 5'b01101) ? delay_pipeline[13] :
                     (cur_count == 5'b01110) ? delay_pipeline[14] :
                     (cur_count == 5'b01111) ? delay_pipeline[15] :
                     (cur_count == 5'b10000) ? delay_pipeline[16] :
                     (cur_count == 5'b10001) ? delay_pipeline[17] :
                     (cur_count == 5'b10010) ? delay_pipeline[18] :
                     (cur_count == 5'b10011) ? delay_pipeline[19] :
                     (cur_count == 5'b10100) ? delay_pipeline[20] :
                     (cur_count == 5'b10101) ? delay_pipeline[21] :
                     (cur_count == 5'b10110) ? delay_pipeline[22] :
                     (cur_count == 5'b10111) ? delay_pipeline[23] :
                     (cur_count == 5'b11000) ? delay_pipeline[24] :
                     (cur_count == 5'b11001) ? delay_pipeline[25] :
                     (cur_count == 5'b11010) ? delay_pipeline[26] :
                     (cur_count == 5'b11011) ? delay_pipeline[27] :
                     (cur_count == 5'b11100) ? delay_pipeline[28] :
                     (cur_count == 5'b11101) ? delay_pipeline[29] :
                     (cur_count == 5'b11110) ? delay_pipeline[30] :
                     delay_pipeline[31];

  //   ------------------ Serial partition # 1 ------------------

  assign product_1_mux = (cur_count == 5'b00000) ? coeff1 :
                        (cur_count == 5'b00001) ? coeff2 :
                        (cur_count == 5'b00010) ? coeff3 :
                        (cur_count == 5'b00011) ? coeff4 :
                        (cur_count == 5'b00100) ? coeff5 :
                        (cur_count == 5'b00101) ? coeff6 :
                        (cur_count == 5'b00110) ? coeff7 :
                        (cur_count == 5'b00111) ? coeff8 :
                        (cur_count == 5'b01000) ? coeff9 :
                        (cur_count == 5'b01001) ? coeff10 :
                        (cur_count == 5'b01010) ? coeff11 :
                        (cur_count == 5'b01011) ? coeff12 :
                        (cur_count == 5'b01100) ? coeff13 :
                        (cur_count == 5'b01101) ? coeff14 :
                        (cur_count == 5'b01110) ? coeff15 :
                        (cur_count == 5'b01111) ? coeff16 :
                        (cur_count == 5'b10000) ? coeff17 :
                        (cur_count == 5'b10001) ? coeff18 :
                        (cur_count == 5'b10010) ? coeff19 :
                        (cur_count == 5'b10011) ? coeff20 :
                        (cur_count == 5'b10100) ? coeff21 :
                        (cur_count == 5'b10101) ? coeff22 :
                        (cur_count == 5'b10110) ? coeff23 :
                        (cur_count == 5'b10111) ? coeff24 :
                        (cur_count == 5'b11000) ? coeff25 :
                        (cur_count == 5'b11001) ? coeff26 :
                        (cur_count == 5'b11010) ? coeff27 :
                        (cur_count == 5'b11011) ? coeff28 :
                        (cur_count == 5'b11100) ? coeff29 :
                        (cur_count == 5'b11101) ? coeff30 :
                        (cur_count == 5'b11110) ? coeff31 :
                        coeff32;
  assign mul_temp = inputmux_1 * product_1_mux;
  assign product_1 = $signed({{1{mul_temp[50]}}, mul_temp});

  assign prod_typeconvert_1 = $signed({{1{product_1[51]}}, product_1});

  assign add_signext = prod_typeconvert_1;
  assign add_signext_1 = acc_out_1;
  assign add_temp = add_signext + add_signext_1;
  assign acc_sum_1 = add_temp[52:0];

  assign acc_in_1 = (phase_0 == 1'b1) ? prod_typeconvert_1 :
                   acc_sum_1;

  always @ (posedge clk or negedge reset)
    begin: Acc_reg_1_process
      if (reset == 1'b0) begin
        acc_out_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          acc_out_1 <= acc_in_1;
        end
      end
    end // Acc_reg_1_process

  always @ (posedge clk or negedge reset)
    begin: Finalsum_reg_process
      if (reset == 1'b0) begin
        acc_final <= 0;
      end
      else begin
        if (phase_0 == 1'b1) begin
          acc_final <= acc_out_1;
        end
      end
    end // Finalsum_reg_process

  assign output_typeconvert = ((acc_final[52] == 1'b0 & acc_final[51:50] != 2'b00) || (acc_final[52] == 1'b0 && acc_final[50:18] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (acc_final[52] == 1'b1 && acc_final[51:50] != 2'b11) ? 33'b100000000000000000000000000000000 : (acc_final[50:0] + {acc_final[18], {17{~acc_final[18]}}})>>>18;

  wire   phase_31_dly1; 
//  always @ (posedge clk or negedge reset) begin: Output_Register_process
//      if (reset == 1'b0) begin
//        output_register <= 0;
//	phase_31_dly1   <= 0;
//      end
//      else begin
//        if (phase_31 == 1'b1) begin
assign    output_register = output_typeconvert;
assign	  phase_31_dly1   = phase_0;	  
//        end
//        else begin          
//	  phase_31_dly1   <= 0;	  
//        end	
//      end
//end // Output_Register_process

  // Assignment Statements
     wire [31:0] output_register_temp; 
 assign output_register_temp = (output_register[32:31]==2'b10)? 32'h8000_0000 : (output_register[32:31]==2'b01)? 32'h7fff_ffff : output_register[31:0];
 assign filter_out  =bypass? filter_in : ~sign_en? output_register_temp[31:0] + 32'h8000_0000 : output_register_temp[31:0];

 assign filter_out_en = phase_31_dly1;


endmodule  // filter_comp
