// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2026-01-05 10:49:36
// -------------------------------------------------------------
//========================================================================================  
// ----------------------------------------------------------------------------- 
//  Nanochap Electronics Copyright (C) 2014. ALL RIGHTS RESERVED. 
// ----------------------------------------------------------------------------- 
// Module name     : 
// Description     : 
// ======================================================================================= 
// -------------------------------------------------------------
// HDL Code Generation Options:
//
// OptimizeForHDL: on
// ResetInputPort: reset_n
// TargetDirectory: hdlsrc_1_5
// EDAScriptGeneration: off
// AddInputRegister: off
// AddPipelineRegisters: on
// ResetAssertedLevel: Active-low
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp 
// GenerateHDLTestBench: off
// LoopUnrolling: on

// Filter Specifications:
//
// Sample Rate   : N/A (normalized frequency)
// Response      : Highpass
// Specification : N,F3dB
// Filter Order  : 1
// 3-dB Point    : 7.8125e-06
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 1
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s24,22 -> [-2 2)
// Denominator         : s24,22 -> [-2 2)
// Scale Values        : s24,23 -> [-1 1)
// Input               : s33,32 -> [-1 1)
// Section Input       : s33,32 -> [-1 1)
// Section Output      : s33,32 -> [-1 1)
// Output              : s33,32 -> [-1 1)
// State               : s50,17 -> [-4294967296 4294967296)
// Numerator Prod      : s74,39 -> [-17179869184 17179869184)
// Denominator Prod    : s74,39 -> [-17179869184 17179869184)
// Numerator Accum     : s76,39 -> [-68719476736 68719476736)
// Denominator Accum   : s76,39 -> [-68719476736 68719476736)
// Round Mode          : convergent
// Overflow Mode       : saturate
// -------------------------------------------------------------
// Multipliers           : 2

module filter_iir_hpf
               (
                clk,
                clk_enable,
                reset_n,
                sign_en,
                bypass,
                coeff,
                filter_in,
                filter_out
                );

  input                 clk;
  input                 clk_enable;
  input                 reset_n;
  input                 sign_en;
  input                 bypass;
  input          [23:0] coeff;
  input   signed [31:0] filter_in; //sfix33
  output  signed [31:0] filter_out; //sfix33

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  wire      signed [23:0] scaleconst1 = coeff; // sfix24_En23
  parameter signed [23:0] coeff_b1_section1 = 24'b010000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b2_section1 = 24'b110000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b3_section1 = 24'b000000000000000000000000; //sfix24_En22
  wire      signed [23:0] coeff_a2_section1 = coeff_b1_section1 - coeff; // sfix24_En22
  parameter signed [23:0] coeff_a3_section1 = 24'b000000000000000000000000; //sfix24_En22
  // Signals
  wire signed [32:0] input_typeconvert; // sfix33_En32
  wire signed [56:0] scale1; // sfix57_En55
  wire signed [32:0] scaletypeconvert1; // sfix33_En32
  //   -- Section 1 Signals 
  wire signed [75:0] a1sum1; // sfix76_En39
  wire signed [75:0] b1sum1; // sfix76_En39
  wire signed [49:0] a1sumtypeconvert1; // sfix50_En17
  reg  signed [49:0] delay_section1; // sfix50_En17
  wire signed [75:0] inputconv1; // sfix76_En39
  wire signed [73:0] a2mul1; // sfix74_En39
  wire signed [73:0] b2mul1; // sfix74_En39
  wire signed [50:0] unaryminus_temp; // sfix51_En17
  wire signed [75:0] sub_cast; // sfix76_En39
  wire signed [75:0] sub_cast_1; // sfix76_En39
  wire signed [76:0] sub_temp; // sfix77_En39
  wire signed [75:0] b1multypeconvert1; // sfix76_En39
  wire signed [75:0] add_cast; // sfix76_En39
  wire signed [75:0] add_cast_1; // sfix76_En39
  wire signed [76:0] add_temp; // sfix77_En39
  wire signed [32:0] output_typeconvert; // sfix33_En32
  reg  signed [32:0] output_register; // sfix33_En32

  // Block Statements
//  assign input_typeconvert = ~sign_en ? (filter_in==32'hffff_ffff)? 33'h8000_0000 :  (filter_in==32'h7fff_ffff)? 33'h0 : $signed({{2{~filter_in[31]}},filter_in[30:0]+1'b1}) : {{2{filter_in[31]}},filter_in[30:0]};
    assign input_typeconvert = ~sign_en?  $signed({1'b0,filter_in})-33'sh0_8000_0000 : {{2{filter_in[31]}},filter_in[30:0]};

  assign scale1 = input_typeconvert * scaleconst1;

  assign scaletypeconvert1 = ((scale1[56] == 1'b0 & scale1[55] != 1'b0) || (scale1[56] == 1'b0 && scale1[55:23] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (scale1[56] == 1'b1 && scale1[55] != 1'b1) ? 33'b100000000000000000000000000000000 : (scale1[55:0] + {scale1[23], {22{~scale1[23]}}})>>>23;

  //   ------------------ Section 1 (First Order) ------------------

  assign a1sumtypeconvert1 = ((a1sum1[75] == 1'b0 & a1sum1[74:71] != 4'b0000) || (a1sum1[75] == 1'b0 && a1sum1[71:22] == 50'b01111111111111111111111111111111111111111111111111) // special case0
) ? 50'b01111111111111111111111111111111111111111111111111 : 
      (a1sum1[75] == 1'b1 && a1sum1[74:71] != 4'b1111) ? 50'b10000000000000000000000000000000000000000000000000 : (a1sum1[71:0] + {a1sum1[22], {21{~a1sum1[22]}}})>>>22;

  always @ (posedge clk or negedge reset_n)
    begin: delay_process_section1
      if (reset_n == 1'b0) begin
        delay_section1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section1 <= a1sumtypeconvert1;
        end
      end
    end // delay_process_section1

  assign inputconv1 = $signed({scaletypeconvert1, 7'b0000000});

  assign a2mul1 = delay_section1 * coeff_a2_section1;

  assign unaryminus_temp = (delay_section1==50'b10000000000000000000000000000000000000000000000000) ? $signed({1'b0, delay_section1}) : -delay_section1;
  assign b2mul1 = $signed({unaryminus_temp, 22'b0000000000000000000000});

  assign sub_cast = inputconv1;
  assign sub_cast_1 = $signed({{2{a2mul1[73]}}, a2mul1});
  assign sub_temp = sub_cast - sub_cast_1;
  assign a1sum1 = ((sub_temp[76] == 1'b0 & sub_temp[75] != 1'b0) || (sub_temp[76] == 1'b0 && sub_temp[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (sub_temp[76] == 1'b1 && sub_temp[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : sub_temp[75:0];

  assign b1multypeconvert1 = $signed({a1sumtypeconvert1, 22'b0000000000000000000000});

  assign add_cast = b1multypeconvert1;
  assign add_cast_1 = $signed({{2{b2mul1[73]}}, b2mul1});
  assign add_temp = add_cast + add_cast_1;
  assign b1sum1 = ((add_temp[76] == 1'b0 & add_temp[75] != 1'b0) || (add_temp[76] == 1'b0 && add_temp[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp[76] == 1'b1 && add_temp[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp[75:0];

  assign output_typeconvert = ((b1sum1[75] == 1'b0 & b1sum1[74:39] != 36'h000000000) || (b1sum1[75] == 1'b0 && b1sum1[39:7] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (b1sum1[75] == 1'b1 && b1sum1[74:39] != 36'b111111111111111111111111111111111111) ? 33'b100000000000000000000000000000000 : (b1sum1[39:0] + {b1sum1[7], {6{~b1sum1[7]}}})>>>7;

  always @ (posedge clk or negedge reset_n)
    begin: Output_Register_process
      if (reset_n == 1'b0) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  wire [31:0] output_register_tmp; 
  assign output_register_tmp = (output_register[32:31]==2'b10)? 32'h8000_0000 : (output_register[32:31]==2'b01)? 32'h7fff_ffff : output_register[31:0];
  assign filter_out  = bypass? filter_in : ~sign_en ? output_register_tmp[31:0] + 32'h8000_0000 : output_register_tmp[31:0];
endmodule  // filter
