// -------------------------------------------------------------
//
// Module: filter_comp
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-08-05 17:17:35
// -------------------------------------------------------------
//========================================================================================  
// ----------------------------------------------------------------------------- 
//  Nanochap Electronics Copyright (C) 2014. ALL RIGHTS RESERVED. 
// ----------------------------------------------------------------------------- 
// Module name     : filter_wrapper
// Description     : the wrapper of LPF/HPF/MOTCH FILER
// ======================================================================================= 
// ----------------------------------------------------------------------------- 
// Revision History: 
// ----------------------------------------------------------------------------- 
// Revision       Date(xxxx-xx-xx)     Author             Description 
// ----------------------------------------------------------------------------- 
//   1.0          2025-9-15         Zhen Cao           Initial version 
// ----------------------------------------------------------------------------- 
//======================================================================================== 

module filter_wrapper#(
parameter DATA_WIDTH = 32,
          CHN_NUM    = 16
)(
input wire [CHN_NUM-1:0]   clk,   
input wire [CHN_NUM-1:0]   notch_clk,
input wire [CHN_NUM-1:0]   lpf_clk,
input wire [CHN_NUM-1:0]   hpf_clk,
input wire    pclk,     
input wire    reset,
input wire    sign_en,
input wire    scan_mode,

input wire [3:0]   osr_sel,
input wire [3:0]   iclk_div,
//input wire [2:0]   filter_seq,

input wire         int_length_slct,
input wire [1:0]   eeg_int_en,
input wire         eeg_int_clr,
input wire [15:0]  cic_data_ignore_tar,
input wire        [23:0]  hpf_coeff_data,
input wire signed [17:0]  lpf_coeff_data   [31:0],
input wire signed [19:0]  notch_coeff_data [41:0],


input wire [CHN_NUM-1:0] notch_filter_bypass,
input wire [CHN_NUM-1:0] lpf_filter_bypass,
input wire [CHN_NUM-1:0] hpf_filter_bypass,

input wire  [DATA_WIDTH-1:0] imeas_chdata_in[CHN_NUM-1:0],
input wire  [CHN_NUM-1:0]    chdata_en,
input wire                   i_imeas_intr_clr,

output wire [CHN_NUM-1:0]    notch_clk_gtg_en,
output wire [CHN_NUM-1:0]    lpf_clk_gtg_en,
output wire [CHN_NUM-1:0]    hpf_clk_gtg_en,
output wire                  notch_filter_valid,

output wire                   o_eeg_int,
output reg                    eeg_int_sts,
output reg                    meas_done_d1,
output wire  [DATA_WIDTH-1:0] imeas_chdata_out[CHN_NUM-1:0]

);

reg notch_filter_enable[CHN_NUM-1:0];
reg notch_chdata_en_temp[CHN_NUM-1:0];
reg hpf_chdata_en_temp[CHN_NUM-1:0];
wire notch_chdata_en[CHN_NUM-1:0];
wire hpf_chdata_en[CHN_NUM-1:0];
wire [CHN_NUM-1:0] notch_filter_bypass_temp; 
wire [CHN_NUM-1:0] lpf_filter_bypass_temp;
wire [CHN_NUM-1:0] hpf_filter_bypass_temp;

wire [CHN_NUM-1:0] filter_chdata_en;


assign notch_filter_valid = |notch_filter_bypass_temp;


//OSR logic
  //NOTCH 
wire [3:0] data_rate_notch;
wire [4:0] data_rate_add;
wire       data_rate_by_pass;
wire       data_rate_by_pass_lpf;


assign data_rate_notch = (data_rate_add<=4'h3)? 4'h0 : (osr_sel - 4'h2 + iclk_div);  
              

assign data_rate_add     = {1'b0,iclk_div} + {1'b0,osr_sel};
assign data_rate_by_pass = ~((data_rate_add>=5'h4) & (data_rate_add<=5'hd));

//LPF
//
assign data_rate_by_pass_lpf = ~((data_rate_add>=5'h2) & (data_rate_add<=5'hf));

//HPF//



//int
wire [DATA_WIDTH-1:0] filter1[CHN_NUM-1:0];
wire [DATA_WIDTH-1:0] filter2[CHN_NUM-1:0];
wire [DATA_WIDTH-1:0] filter3[CHN_NUM-1:0];
wire [DATA_WIDTH-1:0] filter4[CHN_NUM-1:0];
wire [DATA_WIDTH-1:0] filter5[CHN_NUM-1:0];
wire [DATA_WIDTH-1:0] filter6[CHN_NUM-1:0];
wire [DATA_WIDTH-1:0] imeas_chdata_out_temp[CHN_NUM-1:0];

wire        meas_done;
wire        meas_done_pulse;
wire        eeg_sts_clr_sync_pulse;
wire        eeg_int_sts_pulse;
wire        eeg_imeas_sts_clr_sync_pulse;

//for shadow notch filter
reg  [15:0] cic_data_counter;
wire [15:0] cic_data_counter_tar;
wire [15:0] cic_data_counter_tar_temp;
wire        cic_data_ok;
wire        cic_data_counter_clr;
assign cic_data_counter_tar =  (|notch_filter_bypass_temp)?  (|lpf_filter_bypass_temp)? cic_data_ignore_tar : 16'h0000 : cic_data_ignore_tar;    

common_sync_bit u_cic_data_counter_tar_sync[15:0](
       .clk(pclk),
       .rst_(reset),
       .async_in(cic_data_counter_tar),
       .sync_out(cic_data_counter_tar_temp)
);

common_sync_bit u_cic_data_counter_clr_sync(
       .clk(pclk),
       .rst_(reset),
       .async_in(cic_data_counter_tar!=cic_data_counter_tar_temp),
       .sync_out(cic_data_counter_clr)
);

always @(posedge pclk or negedge reset) begin
  if(~reset) begin
    cic_data_counter <= 16'h0000;
  end
        else if(cic_data_counter_clr) begin
    cic_data_counter <= 16'h0000;
        end
        else if(meas_done & (cic_data_counter!=cic_data_counter_tar_temp)) begin
    cic_data_counter <= cic_data_counter + 1'b1;
        end
end

assign cic_data_ok = cic_data_counter==cic_data_counter_tar_temp;

//int
assign meas_done = |filter_chdata_en;
assign o_eeg_int = ((eeg_int_sts & !int_length_slct) | (eeg_int_sts_pulse & int_length_slct)) & eeg_int_en[0];

common_pulse_rising u_eeg_int_sts_pulse(
.d_in(eeg_int_sts),
.clk(pclk),
.rst_(reset),
.d_out(eeg_int_sts_pulse)
);

common_pulse_async_clr u_eeg_clr_sync(
.d_in(eeg_int_clr),
.clk(pclk),
.rst_(reset),
.int_sts(eeg_int_sts),
.scan_mode(scan_mode),
.d_out(eeg_sts_clr_sync_pulse)
);

wire eeg_int_en_sync;
common_sync_bit u_eeg_int_en_sync(
       .clk(pclk),
       .rst_(reset),
       .async_in(eeg_int_en[1]),
       .sync_out(eeg_int_en_sync)
);

common_pulse_async_clr u_eeg_imeas_clr_sync(
.d_in(i_imeas_intr_clr),
.clk(pclk),
.rst_(reset),
.int_sts(eeg_int_sts),
.scan_mode(scan_mode),
.d_out(eeg_imeas_sts_clr_sync_pulse)
);

always @(posedge pclk or negedge reset) begin
  if(~reset) begin
    eeg_int_sts <= 1'b0;
  end
        else if(eeg_sts_clr_sync_pulse | !eeg_int_en_sync | eeg_imeas_sts_clr_sync_pulse)begin
    eeg_int_sts <= 1'b0;
        end
        else if(meas_done & ((cic_data_ok) | ((&(notch_filter_bypass_temp)) && (&(lpf_filter_bypass_temp)))))begin
    eeg_int_sts <= 1'b1;
        end
        else begin
    eeg_int_sts <= eeg_int_sts;
        end
end

always @(posedge pclk or negedge reset) begin
  if(~reset) begin
    meas_done_d1 <= 1'b0;
  end
        else if(cic_data_ok | ((&(notch_filter_bypass_temp)) && (&(lpf_filter_bypass_temp)))) begin
    meas_done_d1 <= meas_done;
        end
end

//notch with the osr that it doesn't support
wire   notch_filter_osr_valid;
assign notch_filter_osr_valid   =   ~((data_rate_notch >= 4'h2) & (data_rate_notch <= 4'hb));
assign notch_filter_bypass_temp = notch_filter_bypass | {CHN_NUM{notch_filter_osr_valid}} | {CHN_NUM{data_rate_by_pass}};


//lpf with the osr that it doesn't support
assign lpf_filter_bypass_temp = lpf_filter_bypass | {CHN_NUM{data_rate_by_pass_lpf}};

//lpf with the osr that it doesn't support
assign hpf_filter_bypass_temp = hpf_filter_bypass;


reg lpf_filter_enable[CHN_NUM-1:0];
wire [4:0] lpf_filter_enable_cnt[CHN_NUM-1:0];

wire [5:0] notch_filter_enable_cnt[CHN_NUM-1:0];

wire lpf_filter_out_en[CHN_NUM-1:0];
wire lpf_filter_out_en_temp[CHN_NUM-1:0];
wire chdata_en_pulse[CHN_NUM-1:0];


genvar i;
generate
  for(i=0; i<CHN_NUM; i=i+1) begin : FILTER
   //HPF
   //.bypass(hpf_filter_bypass),

   //HPF
   filter_iir_hpf U_filter_iir_hpf (
    .clk          (hpf_clk[i]),
    .clk_enable   (1'b1),
    .reset_n      (reset),
    .sign_en      (sign_en),
    .bypass       (hpf_filter_bypass_temp[i]),
    .coeff        (hpf_coeff_data),
    .filter_in    (filter1[i]),
    .filter_out   (filter2[i])
   );

   //NOTCH
   notch_filter u_notch_filter(
   .clk(notch_clk[i]),
   .clk_enable(1'b1),
   .reset(reset),
   .sign_en(sign_en),
   .bypass(notch_filter_bypass_temp[i]),
   .notch_coeff_data(notch_coeff_data),
   .filter_in(filter3[i]),
   .o_cur_count(notch_filter_enable_cnt[i]),
   .filter_out(filter4[i])
   );
   
   //LPF
   filter_fir_lpf u_filter_fir_lpf(
   .clk(lpf_clk[i]),
   .clk_enable(1'b1),
   .reset(reset),
   .sign_en(sign_en),
   .filter_out_en(lpf_filter_out_en_temp[i]),
   .lpf_coeff_data(lpf_coeff_data),
   .bypass(lpf_filter_bypass_temp[i]),
   .filter_in(filter5[i]),
   .o_cur_count(lpf_filter_enable_cnt[i]),
   .filter_out(filter6[i])
   );

assign imeas_chdata_out[i] = imeas_chdata_out_temp[i] & ({DATA_WIDTH{cic_data_ok}} | {DATA_WIDTH{notch_filter_bypass_temp[i] & lpf_filter_bypass_temp[i]}});


common_pulse_rising u_chdata_en_pulse(
.d_in(chdata_en[i]),
.clk(clk[i]),
.rst_(reset),
.d_out(chdata_en_pulse[i])
);


always @ (posedge clk[i] or negedge reset)begin
    if (reset == 1'b0) begin
        lpf_filter_enable[i] <= 1'b0;
    end
    else if (chdata_en_pulse[i] & !lpf_filter_bypass_temp[i]) begin        
        lpf_filter_enable[i] <= 1'b1;   
    end
    else if (lpf_filter_enable[i]) begin 
      if (lpf_filter_enable_cnt[i] == 5'b11110) begin        
              lpf_filter_enable[i] <= 1'b0;   
            end
            else begin
              lpf_filter_enable[i] <= 1'b1;   
      end	    
    end   
    else begin
        lpf_filter_enable[i] <= 1'b0;
    end 
end

//notch
assign lpf_filter_out_en[i] = lpf_filter_bypass_temp[i]? chdata_en_pulse[i] : lpf_filter_out_en_temp[i];
always @ (posedge clk[i] or negedge reset)begin
    if (reset == 1'b0) begin
        notch_filter_enable[i] <= 1'b0;
        notch_chdata_en_temp[i]        <= 1'b0;
    end
    else if (lpf_filter_out_en[i] & !notch_filter_bypass_temp[i]) begin        
        notch_filter_enable[i] <= 1'b1;  
        notch_chdata_en_temp[i]        <= 1'b0; 
    end
    else if (notch_filter_enable[i]) begin 
      if (notch_filter_enable_cnt[i] == 6'b10_1001) begin        
              notch_filter_enable[i] <= 1'b0;  
              notch_chdata_en_temp[i]        <= 1'b1; 
            end
            else begin
              notch_filter_enable[i] <= 1'b1; 
              notch_chdata_en_temp[i]        <= 1'b0;  
      end	    
    end   
    else begin
        notch_filter_enable[i] <= 1'b0;
        notch_chdata_en_temp[i]        <= 1'b0;
    end 
end

//hpf
always @ (posedge clk[i] or negedge reset)begin
    if (reset == 1'b0) begin
        hpf_chdata_en_temp[i] <= 1'b0;
    end else if (notch_chdata_en[i] & !hpf_filter_bypass_temp[i]) begin        
        hpf_chdata_en_temp[i] <= 1'b1; 
    end else begin
        hpf_chdata_en_temp[i] <= 1'b0;
    end 
end

assign lpf_clk_gtg_en[i]      = !lpf_filter_bypass_temp[i] & (chdata_en_pulse[i] | lpf_filter_enable[i]);

assign notch_clk_gtg_en[i]    = !notch_filter_bypass_temp[i] & notch_filter_enable[i];

assign notch_chdata_en[i]     = notch_filter_bypass_temp[i]? lpf_filter_out_en[i] : notch_chdata_en_temp[i];

assign hpf_clk_gtg_en[i]      = !hpf_filter_bypass_temp[i] & (hpf_chdata_en[i]);

assign hpf_chdata_en[i]       = hpf_filter_bypass_temp[i]? notch_chdata_en[i] : hpf_chdata_en_temp[i];

common_pulse_sync u_chdata_en_sync(
.i_a_clk(clk[i]),
.i_b_clk(pclk),  
.i_a_rst_n(reset),
.i_b_rst_n(reset),
.i_test_mode(scan_mode), 
.i_a_pulse(hpf_chdata_en[i]),  
.o_a_ready(),   
.o_b_pulse(filter_chdata_en[i])    
); 















  end
endgenerate


//always@(*)begin
//   case(filter_seq)	
//    3'b000 : begin //H-N-L
//    filter1           = imeas_chdata_in;
//    filter3           = filter2;
//    filter5           = filter4;
//    imeas_chdata_out_temp  = filter6;
//    end
//    3'b001 : begin //H-L-N
//    filter1           = imeas_chdata_in;
//    filter5           = filter2;
//    filter3           = filter6;
//    imeas_chdata_out_temp  = filter4;
//
//    end
//    3'b010 : begin //L-N-H
// Fixed filter order: LPF → Notch → HPF
// Per-channel routing using generate to avoid unsupported array-to-array assign
genvar k;
generate
  for (k=0; k<CHN_NUM; k=k+1) begin : ROUTING
    assign filter5[k]               = imeas_chdata_in[k];
    assign filter3[k]               = filter6[k];
    assign filter1[k]               = filter4[k];
    assign imeas_chdata_out_temp[k] = filter2[k];
  end
endgenerate
//    end
//    3'b011 : begin //L-H-N
//    filter5           = imeas_chdata_in;
//    filter1           = filter6;
//    filter3           = filter2;
//    imeas_chdata_out_temp  = filter4;
//    end
//    3'b100 : begin //N-H-L
//    filter3           = imeas_chdata_in;
//    filter1           = filter4;
//    filter5           = filter2;
//    imeas_chdata_out_temp  = filter6;
//    end
//    3'b101 : begin //N-L-H
//    filter3           = imeas_chdata_in;
//    filter5           = filter4;
//    filter1           = filter6;
//    imeas_chdata_out_temp  = filter2;
//    end
//    default : begin //H-N-L
//    filter1           = imeas_chdata_in;
//    filter3           = filter2;
//    filter5           = filter4;
//    imeas_chdata_out_temp  = filter6;
//    end
//
//  endcase
//end


endmodule
