// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-09-24 14:35:34
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: hdlsrc_notch
// EDAScriptGeneration: off
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp 
// GenerateHDLTestBench: off

// Filter Specifications:
//
// Sample Rate            : N/A (normalized frequency)
// Response               : Bandstop
// Specification          : Fp1,Fst1,Fst2,Fp2,Ap1,Ast,Ap2
// Stopband Atten.        : 20 dB
// First Passband Edge    : 0.093
// First Stopband Edge    : 0.098
// Second Stopband Edge   : 0.102
// Second Passband Edge   : 0.1075
// First Passband Ripple  : 3 dB
// Second Passband Ripple : 3 dB
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 2
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s16,14 -> [-2 2)
// Denominator         : s16,14 -> [-2 2)
// Scale Values        : s16,15 -> [-1 1)
// Input               : s18,0 -> [-131072 131072)
// Section Input       : s18,0 -> [-131072 131072)
// Section Output      : s18,0 -> [-131072 131072)
// Output              : s18,-10 -> [-134217728 134217728)
// State               : s24,0 -> [-8388608 8388608)
// Numerator Prod      : s40,14 -> [-33554432 33554432)
// Denominator Prod    : s40,14 -> [-33554432 33554432)
// Numerator Accum     : s42,14 -> [-134217728 134217728)
// Denominator Accum   : s42,14 -> [-134217728 134217728)
// Round Mode          : convergent
// Overflow Mode       : saturate
// Cast Before Sum     : true
// -------------------------------------------------------------
// Multipliers           : 8



`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [17:0] filter_in; //sfix18
  output  signed [17:0] filter_out; //sfix18_E10

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] scaleconst1 = 16'b0111111000110100; //sfix16_En15
  parameter signed [15:0] coeff_b1_section1 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_b2_section1 = 16'b1000011001000100; //sfix16_En14
  parameter signed [15:0] coeff_b3_section1 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_a2_section1 = 16'b1000100010011100; //sfix16_En14
  parameter signed [15:0] coeff_a3_section1 = 16'b0011111000100100; //sfix16_En14
  parameter signed [15:0] scaleconst2 = 16'b0111111000110100; //sfix16_En15
  parameter signed [15:0] coeff_b1_section2 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_b2_section2 = 16'b1000011001000100; //sfix16_En14
  parameter signed [15:0] coeff_b3_section2 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_a2_section2 = 16'b1000011101011100; //sfix16_En14
  parameter signed [15:0] coeff_a3_section2 = 16'b0011111001001011; //sfix16_En14
  // Signals
  reg  signed [17:0] input_register; // sfix18
  wire signed [33:0] scale1; // sfix34_En15
  wire signed [17:0] scaletypeconvert1; // sfix18
  // Section 1 Signals 
  wire signed [41:0] a1sum1; // sfix42_En14
  wire signed [41:0] a2sum1; // sfix42_En14
  wire signed [41:0] b1sum1; // sfix42_En14
  wire signed [41:0] b2sum1; // sfix42_En14
  wire signed [23:0] typeconvert1; // sfix24
  reg  signed [23:0] delay_section1 [0:1] ; // sfix24
  wire signed [41:0] inputconv1; // sfix42_En14
  wire signed [39:0] a2mul1; // sfix40_En14
  wire signed [39:0] a3mul1; // sfix40_En14
  wire signed [39:0] b1mul1; // sfix40_En14
  wire signed [39:0] b2mul1; // sfix40_En14
  wire signed [39:0] b3mul1; // sfix40_En14
  wire signed [41:0] sub_cast; // sfix42_En14
  wire signed [41:0] sub_cast_1; // sfix42_En14
  wire signed [42:0] sub_temp; // sfix43_En14
  wire signed [41:0] sub_cast_2; // sfix42_En14
  wire signed [41:0] sub_cast_3; // sfix42_En14
  wire signed [42:0] sub_temp_1; // sfix43_En14
  wire signed [41:0] b1multypeconvert1; // sfix42_En14
  wire signed [41:0] add_cast; // sfix42_En14
  wire signed [41:0] add_cast_1; // sfix42_En14
  wire signed [42:0] add_temp; // sfix43_En14
  wire signed [41:0] add_cast_2; // sfix42_En14
  wire signed [41:0] add_cast_3; // sfix42_En14
  wire signed [42:0] add_temp_1; // sfix43_En14
  wire signed [17:0] section_result1; // sfix18
  wire signed [33:0] scale2; // sfix34_En15
  wire signed [17:0] scaletypeconvert2; // sfix18
  // Section 2 Signals 
  wire signed [41:0] a1sum2; // sfix42_En14
  wire signed [41:0] a2sum2; // sfix42_En14
  wire signed [41:0] b1sum2; // sfix42_En14
  wire signed [41:0] b2sum2; // sfix42_En14
  wire signed [23:0] typeconvert2; // sfix24
  reg  signed [23:0] delay_section2 [0:1] ; // sfix24
  wire signed [41:0] inputconv2; // sfix42_En14
  wire signed [39:0] a2mul2; // sfix40_En14
  wire signed [39:0] a3mul2; // sfix40_En14
  wire signed [39:0] b1mul2; // sfix40_En14
  wire signed [39:0] b2mul2; // sfix40_En14
  wire signed [39:0] b3mul2; // sfix40_En14
  wire signed [41:0] sub_cast_4; // sfix42_En14
  wire signed [41:0] sub_cast_5; // sfix42_En14
  wire signed [42:0] sub_temp_2; // sfix43_En14
  wire signed [41:0] sub_cast_6; // sfix42_En14
  wire signed [41:0] sub_cast_7; // sfix42_En14
  wire signed [42:0] sub_temp_3; // sfix43_En14
  wire signed [41:0] b1multypeconvert2; // sfix42_En14
  wire signed [41:0] add_cast_4; // sfix42_En14
  wire signed [41:0] add_cast_5; // sfix42_En14
  wire signed [42:0] add_temp_2; // sfix43_En14
  wire signed [41:0] add_cast_6; // sfix42_En14
  wire signed [41:0] add_cast_7; // sfix42_En14
  wire signed [42:0] add_temp_3; // sfix43_En14
  wire signed [17:0] output_typeconvert; // sfix18_E10
  reg  signed [17:0] output_register; // sfix18_E10

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  assign scale1 = input_register * scaleconst1;

  assign scaletypeconvert1 = ((scale1[33] == 1'b0 & scale1[32] != 1'b0) || (scale1[33] == 1'b0 && scale1[32:15] == 18'b011111111111111111) // special case0
) ? 18'b011111111111111111 : 
      (scale1[33] == 1'b1 && scale1[32] != 1'b1) ? 18'b100000000000000000 : (scale1[32:0] + {scale1[15], {14{~scale1[15]}}})>>>15;

  //   ------------------ Section 1 ------------------

  assign typeconvert1 = ((a1sum1[41] == 1'b0 & a1sum1[40:37] != 4'b0000) || (a1sum1[41] == 1'b0 && a1sum1[37:14] == 24'b011111111111111111111111) // special case0
) ? 24'b011111111111111111111111 : 
      (a1sum1[41] == 1'b1 && a1sum1[40:37] != 4'b1111) ? 24'b100000000000000000000000 : (a1sum1[37:0] + {a1sum1[14], {13{~a1sum1[14]}}})>>>14;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section1
      if (reset == 1'b1) begin
        delay_section1[0] <= 24'b000000000000000000000000;
        delay_section1[1] <= 24'b000000000000000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section1[1] <= delay_section1[0];
          delay_section1[0] <= typeconvert1;
        end
      end
    end // delay_process_section1

  assign inputconv1 = $signed({scaletypeconvert1, 14'b00000000000000});

  assign a2mul1 = delay_section1[0] * coeff_a2_section1;

  assign a3mul1 = delay_section1[1] * coeff_a3_section1;

  assign b1mul1 = $signed({typeconvert1, 14'b00000000000000});

  assign b2mul1 = delay_section1[0] * coeff_b2_section1;

  assign b3mul1 = $signed({delay_section1[1], 14'b00000000000000});

  assign sub_cast = inputconv1;
  assign sub_cast_1 = $signed({{2{a2mul1[39]}}, a2mul1});
  assign sub_temp = sub_cast - sub_cast_1;
  assign a2sum1 = ((sub_temp[42] == 1'b0 & sub_temp[41] != 1'b0) || (sub_temp[42] == 1'b0 && sub_temp[41:0] == 42'b011111111111111111111111111111111111111111) // special case0
) ? 42'b011111111111111111111111111111111111111111 : 
      (sub_temp[42] == 1'b1 && sub_temp[41] != 1'b1) ? 42'b100000000000000000000000000000000000000000 : sub_temp[41:0];

  assign sub_cast_2 = a2sum1;
  assign sub_cast_3 = $signed({{2{a3mul1[39]}}, a3mul1});
  assign sub_temp_1 = sub_cast_2 - sub_cast_3;
  assign a1sum1 = ((sub_temp_1[42] == 1'b0 & sub_temp_1[41] != 1'b0) || (sub_temp_1[42] == 1'b0 && sub_temp_1[41:0] == 42'b011111111111111111111111111111111111111111) // special case0
) ? 42'b011111111111111111111111111111111111111111 : 
      (sub_temp_1[42] == 1'b1 && sub_temp_1[41] != 1'b1) ? 42'b100000000000000000000000000000000000000000 : sub_temp_1[41:0];

  assign b1multypeconvert1 = $signed({{2{b1mul1[39]}}, b1mul1});

  assign add_cast = b1multypeconvert1;
  assign add_cast_1 = $signed({{2{b2mul1[39]}}, b2mul1});
  assign add_temp = add_cast + add_cast_1;
  assign b2sum1 = ((add_temp[42] == 1'b0 & add_temp[41] != 1'b0) || (add_temp[42] == 1'b0 && add_temp[41:0] == 42'b011111111111111111111111111111111111111111) // special case0
) ? 42'b011111111111111111111111111111111111111111 : 
      (add_temp[42] == 1'b1 && add_temp[41] != 1'b1) ? 42'b100000000000000000000000000000000000000000 : add_temp[41:0];

  assign add_cast_2 = b2sum1;
  assign add_cast_3 = $signed({{2{b3mul1[39]}}, b3mul1});
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign b1sum1 = ((add_temp_1[42] == 1'b0 & add_temp_1[41] != 1'b0) || (add_temp_1[42] == 1'b0 && add_temp_1[41:0] == 42'b011111111111111111111111111111111111111111) // special case0
) ? 42'b011111111111111111111111111111111111111111 : 
      (add_temp_1[42] == 1'b1 && add_temp_1[41] != 1'b1) ? 42'b100000000000000000000000000000000000000000 : add_temp_1[41:0];

  assign section_result1 = ((b1sum1[41] == 1'b0 & b1sum1[40:31] != 10'b0000000000) || (b1sum1[41] == 1'b0 && b1sum1[31:14] == 18'b011111111111111111) // special case0
) ? 18'b011111111111111111 : 
      (b1sum1[41] == 1'b1 && b1sum1[40:31] != 10'b1111111111) ? 18'b100000000000000000 : (b1sum1[31:0] + {b1sum1[14], {13{~b1sum1[14]}}})>>>14;

  assign scale2 = section_result1 * scaleconst2;

  assign scaletypeconvert2 = ((scale2[33] == 1'b0 & scale2[32] != 1'b0) || (scale2[33] == 1'b0 && scale2[32:15] == 18'b011111111111111111) // special case0
) ? 18'b011111111111111111 : 
      (scale2[33] == 1'b1 && scale2[32] != 1'b1) ? 18'b100000000000000000 : (scale2[32:0] + {scale2[15], {14{~scale2[15]}}})>>>15;

  //   ------------------ Section 2 ------------------

  assign typeconvert2 = ((a1sum2[41] == 1'b0 & a1sum2[40:37] != 4'b0000) || (a1sum2[41] == 1'b0 && a1sum2[37:14] == 24'b011111111111111111111111) // special case0
) ? 24'b011111111111111111111111 : 
      (a1sum2[41] == 1'b1 && a1sum2[40:37] != 4'b1111) ? 24'b100000000000000000000000 : (a1sum2[37:0] + {a1sum2[14], {13{~a1sum2[14]}}})>>>14;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section2
      if (reset == 1'b1) begin
        delay_section2[0] <= 24'b000000000000000000000000;
        delay_section2[1] <= 24'b000000000000000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section2[1] <= delay_section2[0];
          delay_section2[0] <= typeconvert2;
        end
      end
    end // delay_process_section2

  assign inputconv2 = $signed({scaletypeconvert2, 14'b00000000000000});

  assign a2mul2 = delay_section2[0] * coeff_a2_section2;

  assign a3mul2 = delay_section2[1] * coeff_a3_section2;

  assign b1mul2 = $signed({typeconvert2, 14'b00000000000000});

  assign b2mul2 = delay_section2[0] * coeff_b2_section2;

  assign b3mul2 = $signed({delay_section2[1], 14'b00000000000000});

  assign sub_cast_4 = inputconv2;
  assign sub_cast_5 = $signed({{2{a2mul2[39]}}, a2mul2});
  assign sub_temp_2 = sub_cast_4 - sub_cast_5;
  assign a2sum2 = ((sub_temp_2[42] == 1'b0 & sub_temp_2[41] != 1'b0) || (sub_temp_2[42] == 1'b0 && sub_temp_2[41:0] == 42'b011111111111111111111111111111111111111111) // special case0
) ? 42'b011111111111111111111111111111111111111111 : 
      (sub_temp_2[42] == 1'b1 && sub_temp_2[41] != 1'b1) ? 42'b100000000000000000000000000000000000000000 : sub_temp_2[41:0];

  assign sub_cast_6 = a2sum2;
  assign sub_cast_7 = $signed({{2{a3mul2[39]}}, a3mul2});
  assign sub_temp_3 = sub_cast_6 - sub_cast_7;
  assign a1sum2 = ((sub_temp_3[42] == 1'b0 & sub_temp_3[41] != 1'b0) || (sub_temp_3[42] == 1'b0 && sub_temp_3[41:0] == 42'b011111111111111111111111111111111111111111) // special case0
) ? 42'b011111111111111111111111111111111111111111 : 
      (sub_temp_3[42] == 1'b1 && sub_temp_3[41] != 1'b1) ? 42'b100000000000000000000000000000000000000000 : sub_temp_3[41:0];

  assign b1multypeconvert2 = $signed({{2{b1mul2[39]}}, b1mul2});

  assign add_cast_4 = b1multypeconvert2;
  assign add_cast_5 = $signed({{2{b2mul2[39]}}, b2mul2});
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign b2sum2 = ((add_temp_2[42] == 1'b0 & add_temp_2[41] != 1'b0) || (add_temp_2[42] == 1'b0 && add_temp_2[41:0] == 42'b011111111111111111111111111111111111111111) // special case0
) ? 42'b011111111111111111111111111111111111111111 : 
      (add_temp_2[42] == 1'b1 && add_temp_2[41] != 1'b1) ? 42'b100000000000000000000000000000000000000000 : add_temp_2[41:0];

  assign add_cast_6 = b2sum2;
  assign add_cast_7 = $signed({{2{b3mul2[39]}}, b3mul2});
  assign add_temp_3 = add_cast_6 + add_cast_7;
  assign b1sum2 = ((add_temp_3[42] == 1'b0 & add_temp_3[41] != 1'b0) || (add_temp_3[42] == 1'b0 && add_temp_3[41:0] == 42'b011111111111111111111111111111111111111111) // special case0
) ? 42'b011111111111111111111111111111111111111111 : 
      (add_temp_3[42] == 1'b1 && add_temp_3[41] != 1'b1) ? 42'b100000000000000000000000000000000000000000 : add_temp_3[41:0];

  assign output_typeconvert = (b1sum2[41] == 1'b0 && b1sum2[40:23] == 18'b111111111111111111) ? 18'b011111111111111111 : (b1sum2[41:0] + {b1sum2[24], {23{~b1sum2[24]}}})>>>24;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
