// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-10-03 14:54:28
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: hdlsrc_256k_f
// EDAScriptGeneration: off
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp 
// GenerateHDLTestBench: off

// Filter Specifications:
//
// Sample Rate   : N/A (normalized frequency)
// Response      : Highpass
// Specification : N,F3dB
// 3-dB Point    : 7.8125e-07
// Filter Order  : 1
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 1
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s24,22 -> [-2 2)
// Denominator         : s24,22 -> [-2 2)
// Scale Values        : s24,23 -> [-1 1)
// Input               : s32,31 -> [-1 1)
// Section Input       : s32,26 -> [-32 32)
// Section Output      : s32,27 -> [-16 16)
// Output              : s32,31 -> [-1 1)
// State               : s32,31 -> [-1 1)
// Numerator Prod      : s56,53 -> [-4 4)
// Denominator Prod    : s56,53 -> [-4 4)
// Numerator Accum     : s58,53 -> [-16 16)
// Denominator Accum   : s58,53 -> [-16 16)
// Round Mode          : convergent
// Overflow Mode       : wrap
// -------------------------------------------------------------
// Multipliers           : 2



`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [31:0] filter_in; //sfix32_En31
  output  signed [31:0] filter_out; //sfix32_En31

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [23:0] scaleconst1 = 24'b011111111111111111110110; //sfix24_En23
  parameter signed [23:0] coeff_b1_section1 = 24'b010000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b2_section1 = 24'b110000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b3_section1 = 24'b000000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_a2_section1 = 24'b110000000000000000001010; //sfix24_En22
  parameter signed [23:0] coeff_a3_section1 = 24'b000000000000000000000000; //sfix24_En22
  // Signals
  reg  signed [31:0] input_register; // sfix32_En31
  wire signed [59:0] scale1; // sfix60_En54
  wire signed [55:0] mul_temp; // sfix56_En54
  wire signed [31:0] scaletypeconvert1; // sfix32_En26
  //   -- Section 1 Signals 
  wire signed [57:0] a1sum1; // sfix58_En53
  wire signed [57:0] b1sum1; // sfix58_En53
  wire signed [31:0] a1sumtypeconvert1; // sfix32_En31
  reg  signed [31:0] delay_section1; // sfix32_En31
  wire signed [57:0] inputconv1; // sfix58_En53
  wire signed [55:0] a2mul1; // sfix56_En53
  wire signed [55:0] b1mul1; // sfix56_En53
  wire signed [55:0] b2mul1; // sfix56_En53
  wire signed [32:0] unaryminus_temp; // sfix33_En31
  wire signed [57:0] sub_cast; // sfix58_En53
  wire signed [57:0] sub_cast_1; // sfix58_En53
  wire signed [58:0] sub_temp; // sfix59_En53
  wire signed [57:0] b1multypeconvert1; // sfix58_En53
  wire signed [57:0] add_cast; // sfix58_En53
  wire signed [57:0] add_cast_1; // sfix58_En53
  wire signed [58:0] add_temp; // sfix59_En53
  wire signed [31:0] output_typeconvert; // sfix32_En31
  reg  signed [31:0] output_register; // sfix32_En31

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  assign mul_temp = input_register * scaleconst1;
  assign scale1 = $signed({{4{mul_temp[55]}}, mul_temp});

  assign scaletypeconvert1 = (scale1[59:0] + {scale1[28], {27{~scale1[28]}}})>>>28;

  //   ------------------ Section 1 (First Order) ------------------

  assign a1sumtypeconvert1 = (a1sum1[53:0] + {a1sum1[22], {21{~a1sum1[22]}}})>>>22;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section1
      if (reset == 1'b1) begin
        delay_section1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section1 <= a1sumtypeconvert1;
        end
      end
    end // delay_process_section1

  assign inputconv1 = $signed({scaletypeconvert1[30:0], 27'b000000000000000000000000000});

  assign a2mul1 = delay_section1 * coeff_a2_section1;

  assign b1mul1 = $signed({a1sumtypeconvert1[31:0], 22'b0000000000000000000000});

  assign unaryminus_temp = (delay_section1==32'b10000000000000000000000000000000) ? $signed({1'b0, delay_section1}) : -delay_section1;
  assign b2mul1 = $signed({unaryminus_temp[32:0], 22'b0000000000000000000000});

  assign sub_cast = inputconv1;
  assign sub_cast_1 = $signed({{2{a2mul1[55]}}, a2mul1});
  assign sub_temp = sub_cast - sub_cast_1;
  assign a1sum1 = sub_temp[57:0];

  assign b1multypeconvert1 = $signed({{2{b1mul1[55]}}, b1mul1});

  assign add_cast = b1multypeconvert1;
  assign add_cast_1 = $signed({{2{b2mul1[55]}}, b2mul1});
  assign add_temp = add_cast + add_cast_1;
  assign b1sum1 = add_temp[57:0];

  assign output_typeconvert = (b1sum1[53:0] + {b1sum1[22], {21{~b1sum1[22]}}})>>>22;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
