// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-09-19 16:05:51
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: hdlsrc_0p5
// EDAScriptGeneration: off
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp 
// GenerateHDLTestBench: off

// Filter Specifications:
//
// Sample Rate   : N/A (normalized frequency)
// Response      : Highpass
// Specification : N,F3dB
// 3-dB Point    : 0.00097656
// Filter Order  : 3
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 2
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s32,30 -> [-2 2)
// Denominator         : s32,30 -> [-2 2)
// Scale Values        : s32,31 -> [-1 1)
// Input               : s32,0 -> [-2147483648 2147483648)
// Section Input       : s32,26 -> [-32 32)
// Section Output      : s32,27 -> [-16 16)
// Output              : s32,27 -> [-16 16)
// State               : s16,15 -> [-1 1)
// Numerator Prod      : s47,18 -> [-268435456 268435456)
// Denominator Prod    : s47,33 -> [-8192 8192)
// Numerator Accum     : s51,18 -> [-4294967296 4294967296)
// Denominator Accum   : s51,33 -> [-131072 131072)
// Round Mode          : convergent
// Overflow Mode       : wrap
// Cast Before Sum     : true
// -------------------------------------------------------------
// Multipliers           : 5



`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [31:0] filter_in; //sfix32
  output  signed [31:0] filter_out; //sfix32_En27

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [31:0] scaleconst1 = 32'h7FCDBC0E; //sfix32_En31
  parameter signed [31:0] coeff_b1_section1 = 32'h40000000; //sfix32_En30
  parameter signed [31:0] coeff_b2_section1 = 32'h80000000; //sfix32_En30
  parameter signed [31:0] coeff_b3_section1 = 32'h40000000; //sfix32_En30
  parameter signed [31:0] coeff_a2_section1 = 32'h803257A7; //sfix32_En30
  parameter signed [31:0] coeff_a3_section1 = 32'h3FCDCFC4; //sfix32_En30
  parameter signed [31:0] scaleconst2 = 32'h7FCDCFBC; //sfix32_En31
  parameter signed [31:0] coeff_b1_section2 = 32'h40000000; //sfix32_En30
  parameter signed [31:0] coeff_b2_section2 = 32'hC0000000; //sfix32_En30
  parameter signed [31:0] coeff_b3_section2 = 32'h00000000; //sfix32_En30
  parameter signed [31:0] coeff_a2_section2 = 32'hC0323044; //sfix32_En30
  parameter signed [31:0] coeff_a3_section2 = 32'h00000000; //sfix32_En30
  // Signals
  reg  signed [31:0] input_register; // sfix32
  wire signed [90:0] scale1; // sfix91_En58
  wire signed [63:0] mul_temp; // sfix64_En31
  wire signed [31:0] scaletypeconvert1; // sfix32_En26
  // Section 1 Signals 
  wire signed [50:0] a1sum1; // sfix51_En33
  wire signed [50:0] a2sum1; // sfix51_En33
  wire signed [50:0] b1sum1; // sfix51_En18
  wire signed [50:0] b2sum1; // sfix51_En18
  wire signed [15:0] typeconvert1; // sfix16_En15
  reg  signed [15:0] delay_section1 [0:1] ; // sfix16_En15
  wire signed [50:0] inputconv1; // sfix51_En33
  wire signed [46:0] a2mul1; // sfix47_En33
  wire signed [46:0] a3mul1; // sfix47_En33
  wire signed [46:0] b1mul1; // sfix47_En18
  wire signed [46:0] b2mul1; // sfix47_En18
  wire signed [46:0] b3mul1; // sfix47_En18
  wire signed [47:0] mul_temp_1; // sfix48_En45
  wire signed [47:0] mul_temp_2; // sfix48_En45
  wire signed [16:0] mulpwr2_temp; // sfix17_En15
  wire signed [50:0] sub_cast; // sfix51_En33
  wire signed [50:0] sub_cast_1; // sfix51_En33
  wire signed [51:0] sub_temp; // sfix52_En33
  wire signed [50:0] sub_cast_2; // sfix51_En33
  wire signed [50:0] sub_cast_3; // sfix51_En33
  wire signed [51:0] sub_temp_1; // sfix52_En33
  wire signed [50:0] b1multypeconvert1; // sfix51_En18
  wire signed [50:0] add_cast; // sfix51_En18
  wire signed [50:0] add_cast_1; // sfix51_En18
  wire signed [51:0] add_temp; // sfix52_En18
  wire signed [50:0] add_cast_2; // sfix51_En18
  wire signed [50:0] add_cast_3; // sfix51_En18
  wire signed [51:0] add_temp_1; // sfix52_En18
  wire signed [31:0] section_result1; // sfix32_En27
  wire signed [90:0] scale2; // sfix91_En58
  wire signed [63:0] mul_temp_3; // sfix64_En58
  wire signed [31:0] scaletypeconvert2; // sfix32_En26
  //   -- Section 2 Signals 
  wire signed [50:0] a1sum2; // sfix51_En33
  wire signed [50:0] b1sum2; // sfix51_En18
  wire signed [15:0] a1sumtypeconvert2; // sfix16_En15
  reg  signed [15:0] delay_section2; // sfix16_En15
  wire signed [50:0] inputconv2; // sfix51_En33
  wire signed [46:0] a2mul2; // sfix47_En33
  wire signed [46:0] b1mul2; // sfix47_En18
  wire signed [46:0] b2mul2; // sfix47_En18
  wire signed [47:0] mul_temp_4; // sfix48_En45
  wire signed [16:0] unaryminus_temp; // sfix17_En15
  wire signed [50:0] sub_cast_4; // sfix51_En33
  wire signed [50:0] sub_cast_5; // sfix51_En33
  wire signed [51:0] sub_temp_2; // sfix52_En33
  wire signed [50:0] b1multypeconvert2; // sfix51_En18
  wire signed [50:0] add_cast_4; // sfix51_En18
  wire signed [50:0] add_cast_5; // sfix51_En18
  wire signed [51:0] add_temp_2; // sfix52_En18
  wire signed [31:0] output_typeconvert; // sfix32_En27
  reg  signed [31:0] output_register; // sfix32_En27

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  assign mul_temp = input_register * scaleconst1;
  assign scale1 = $signed({mul_temp[63:0], 27'b000000000000000000000000000});

  assign scaletypeconvert1 = (scale1[63:0] + {scale1[32], {31{~scale1[32]}}})>>>32;

  //   ------------------ Section 1 ------------------

  assign typeconvert1 = (a1sum1[33:0] + {a1sum1[18], {17{~a1sum1[18]}}})>>>18;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section1
      if (reset == 1'b1) begin
        delay_section1[0] <= 16'b0000000000000000;
        delay_section1[1] <= 16'b0000000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section1[1] <= delay_section1[0];
          delay_section1[0] <= typeconvert1;
        end
      end
    end // delay_process_section1

  assign inputconv1 = $signed({scaletypeconvert1[31:0], 7'b0000000});

  assign mul_temp_1 = delay_section1[0] * coeff_a2_section1;
  assign a2mul1 = ({{11{mul_temp_1[47]}}, mul_temp_1[47:0]} + {mul_temp_1[12], {11{~mul_temp_1[12]}}})>>>12;

  assign mul_temp_2 = delay_section1[1] * coeff_a3_section1;
  assign a3mul1 = ({{11{mul_temp_2[47]}}, mul_temp_2[47:0]} + {mul_temp_2[12], {11{~mul_temp_2[12]}}})>>>12;

  assign b1mul1 = $signed({typeconvert1[15:0], 3'b000});

  assign mulpwr2_temp = (delay_section1[0]==16'b1000000000000000) ? $signed({1'b0, delay_section1[0]}) : -delay_section1[0];

  assign b2mul1 = $signed({mulpwr2_temp[16:0], 4'b0000});

  assign b3mul1 = $signed({delay_section1[1][15:0], 3'b000});

  assign sub_cast = inputconv1;
  assign sub_cast_1 = $signed({{4{a2mul1[46]}}, a2mul1});
  assign sub_temp = sub_cast - sub_cast_1;
  assign a2sum1 = sub_temp[50:0];

  assign sub_cast_2 = a2sum1;
  assign sub_cast_3 = $signed({{4{a3mul1[46]}}, a3mul1});
  assign sub_temp_1 = sub_cast_2 - sub_cast_3;
  assign a1sum1 = sub_temp_1[50:0];

  assign b1multypeconvert1 = $signed({{4{b1mul1[46]}}, b1mul1});

  assign add_cast = b1multypeconvert1;
  assign add_cast_1 = $signed({{4{b2mul1[46]}}, b2mul1});
  assign add_temp = add_cast + add_cast_1;
  assign b2sum1 = add_temp[50:0];

  assign add_cast_2 = b2sum1;
  assign add_cast_3 = $signed({{4{b3mul1[46]}}, b3mul1});
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign b1sum1 = add_temp_1[50:0];

  assign section_result1 = $signed({b1sum1[22:0], 9'b000000000});

  assign mul_temp_3 = section_result1 * scaleconst2;
  assign scale2 = $signed({{27{mul_temp_3[63]}}, mul_temp_3});

  assign scaletypeconvert2 = (scale2[63:0] + {scale2[32], {31{~scale2[32]}}})>>>32;

  //   ------------------ Section 2 (First Order) ------------------

  assign a1sumtypeconvert2 = (a1sum2[33:0] + {a1sum2[18], {17{~a1sum2[18]}}})>>>18;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section2
      if (reset == 1'b1) begin
        delay_section2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section2 <= a1sumtypeconvert2;
        end
      end
    end // delay_process_section2

  assign inputconv2 = $signed({scaletypeconvert2[31:0], 7'b0000000});

  assign mul_temp_4 = delay_section2 * coeff_a2_section2;
  assign a2mul2 = ({{11{mul_temp_4[47]}}, mul_temp_4[47:0]} + {mul_temp_4[12], {11{~mul_temp_4[12]}}})>>>12;

  assign b1mul2 = $signed({a1sumtypeconvert2[15:0], 3'b000});

  assign unaryminus_temp = (delay_section2==16'b1000000000000000) ? $signed({1'b0, delay_section2}) : -delay_section2;
  assign b2mul2 = $signed({unaryminus_temp[16:0], 3'b000});

  assign sub_cast_4 = inputconv2;
  assign sub_cast_5 = $signed({{4{a2mul2[46]}}, a2mul2});
  assign sub_temp_2 = sub_cast_4 - sub_cast_5;
  assign a1sum2 = sub_temp_2[50:0];

  assign b1multypeconvert2 = $signed({{4{b1mul2[46]}}, b1mul2});

  assign add_cast_4 = b1multypeconvert2;
  assign add_cast_5 = $signed({{4{b2mul2[46]}}, b2mul2});
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign b1sum2 = add_temp_2[50:0];

  assign output_typeconvert = $signed({b1sum2[22:0], 9'b000000000});

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
