// -------------------------------------------------------------
// 
// File Name: hdlsrc_leaky/Untitled/Filter_leaky.v
// Created: 2025-10-08 17:31:12
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 3.90625e-06
// Target subsystem base rate: 3.90625e-06
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        3.90625e-06
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        3.90625e-06
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Filter_leaky
// Source Path: Untitled/Filter leaky
// Hierarchy Level: 0
// Model version: 1.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Filter_leaky
          (clk,
           reset,
           clk_enable,
           In1,
           ce_out,
           Out1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [31:0] In1;  // sfix32_En31
  output  ce_out;
  output  signed [31:0] Out1;  // sfix32_En31


  wire signed [31:0] y;  // sfix32_En31


  MATLAB_System u_MATLAB_System (.clk(clk),
                                 .reset(reset),
                                 .enb(clk_enable),
                                 .x(In1),  // sfix32_En31
                                 .y(y)  // sfix32_En31
                                 );

  assign Out1 = y;

  assign ce_out = clk_enable;

endmodule  // Filter_leaky

