// -------------------------------------------------------------
// 
// File Name: hdlsrc_leaky/Untitled/MATLAB_System.v
// Created: 2025-10-08 17:31:12
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_System
// Source Path: Untitled/Filter leaky/MATLAB System
// Hierarchy Level: 1
// Model version: 1.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_System
          (clk,
           reset,
           enb,
           x,
           y);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] x;  // sfix32_En31
  output  signed [31:0] y;  // sfix32_En31


  wire signed [47:0] leak;  // sfix48_En24
  reg signed [31:0] obj_x_prev;  // sfix32_En31
  wire signed [47:0] d;  // sfix48_En24
  wire signed [47:0] p4d_sub_cast;  // sfix48_En24
  wire signed [48:0] p4d_sub_cast_1;  // sfix49_En24
  wire signed [47:0] p4d_sub_cast_2;  // sfix48_En24
  wire signed [48:0] p4d_sub_cast_3;  // sfix49_En24
  wire signed [48:0] p4d_sub_temp;  // sfix49_En24
  reg signed [47:0] obj_y_prev;  // sfix48_En24
  reg signed [47:0] leak_1;  // sfix48_En24
  wire signed [47:0] tmp;  // sfix48_En24
  wire signed [48:0] p6tmp_sub_cast;  // sfix49_En24
  wire signed [48:0] p6tmp_sub_cast_1;  // sfix49_En24
  wire signed [48:0] p6tmp_sub_temp;  // sfix49_En24
  wire signed [47:0] p6tmp_add_cast;  // sfix48_En24
  wire signed [48:0] p6tmp_add_cast_1;  // sfix49_En24
  wire signed [48:0] p6tmp_add_cast_2;  // sfix49_En24
  wire signed [48:0] p6tmp_add_temp;  // sfix49_En24
  reg signed [31:0] p2_i;  // int32
  reg signed [47:0] p2_leak;  // sfix48_En24
  reg signed [47:0] p2_leak_0;  // sfix48_En24
  reg signed [31:0] p2_add_temp [0:7];  // int32 [8]
  reg [7:0] p2_sub_cast [0:7];  // uint8 [8]
  reg signed [31:0] p2_add_temp_0 [0:7];  // int32 [8]
  reg [7:0] p2_sub_cast_0 [0:7];  // uint8 [8]
  reg [7:0] p2_t_0 [0:7];  // uint8 [8]
  reg signed [48:0] p2_add_cast [0:7];  // sfix49_En24 [8]
  reg signed [31:0] p2_add_temp_1 [0:7];  // int32 [8]
  reg [7:0] p2_cast [0:7];  // uint8 [8]
  reg signed [47:0] p2_sra_temp [0:7];  // sfix48_En24 [8]
  reg signed [48:0] p2_add_cast_0 [0:7];  // sfix49_En24 [8]
  reg signed [48:0] p2_add_temp_2 [0:7];  // sfix49_En24 [8]


  // ---- leak: (m/2^K) * y_prev via shift-add (no multipliers) ----
  assign leak = 48'sh000000000000;



  // s48_En24 -> Q1.31
  // ---- update registers ----
  always @(posedge clk or posedge reset)
    begin : obj_x_prev_reg_process
      if (reset == 1'b1) begin
        obj_x_prev <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          obj_x_prev <= x;
        end
      end
    end



  // Expect x as Q1.31; if upstream is double, this quantizes it.
  // Clamp params
  // ---- IO -> STATE quantization (unbiased; handles scaling) ----
  // Q1.31 -> s48_En24
  // ---- numerator: d = x - x[n-1] (in state domain) ----
  assign p4d_sub_cast = ({{23{x[31]}}, x[31:7]}) + $signed({1'b0, x[6]});
  assign p4d_sub_cast_1 = {p4d_sub_cast[47], p4d_sub_cast};
  assign p4d_sub_cast_2 = ({{23{obj_x_prev[31]}}, obj_x_prev[31:7]}) + $signed({1'b0, obj_x_prev[6]});
  assign p4d_sub_cast_3 = {p4d_sub_cast_2[47], p4d_sub_cast_2};
  assign p4d_sub_temp = p4d_sub_cast_1 - p4d_sub_cast_3;
  assign d = ((p4d_sub_temp[48] == 1'b0) && (p4d_sub_temp[47] != 1'b0) ? 48'sh7FFFFFFFFFFF :
              ((p4d_sub_temp[48] == 1'b1) && (p4d_sub_temp[47] != 1'b1) ? 48'sh800000000000 :
              $signed(p4d_sub_temp[47:0])));



  always @(leak, obj_y_prev) begin
    p2_leak_0 = 48'sh000000000000;
    p2_leak = leak;

    for(p2_i = 32'sd0; p2_i <= 32'sd7; p2_i = p2_i + 32'sd1) begin
      p2_add_temp[p2_i] = p2_i + 32'sd1;
      p2_sub_cast[p2_i] = p2_add_temp[p2_i][7:0];
      p2_add_temp_0[p2_i] = p2_i + 32'sd1;
      p2_sub_cast_0[p2_i] = p2_add_temp_0[p2_i][7:0];
      p2_t_0[p2_i] = 8'd1;
      if (p2_t_0[p2_i][p2_sub_cast[p2_i] - 8'd1] != 1'b0) begin
        p2_add_cast[p2_i] = {p2_leak[47], p2_leak};
        p2_add_temp_1[p2_i] = p2_i + 32'sd19;
        p2_cast[p2_i] = p2_add_temp_1[p2_i][7:0];
        p2_sra_temp[p2_i] = obj_y_prev >>> p2_cast[p2_i];
        p2_add_cast_0[p2_i] = {p2_sra_temp[p2_i][47], p2_sra_temp[p2_i]};
        p2_add_temp_2[p2_i] = p2_add_cast[p2_i] + p2_add_cast_0[p2_i];
        if ((p2_add_temp_2[p2_i][48] == 1'b0) && (p2_add_temp_2[p2_i][47] != 1'b0)) begin
          p2_leak_0 = 48'sh7FFFFFFFFFFF;
        end
        else if ((p2_add_temp_2[p2_i][48] == 1'b1) && (p2_add_temp_2[p2_i][47] != 1'b1)) begin
          p2_leak_0 = 48'sh800000000000;
        end
        else begin
          p2_leak_0 = p2_add_temp_2[p2_i][47:0];
        end
      end
      else begin
        p2_leak_0 = p2_leak;
      end
      p2_leak = p2_leak_0;
    end

    leak_1 = p2_leak;
  end



  // ---- state update ----
  always @(posedge clk or posedge reset)
    begin : obj_y_prev_reg_process
      if (reset == 1'b1) begin
        obj_y_prev <= 48'sh000000000000;
      end
      else begin
        if (enb) begin
          obj_y_prev <= tmp;
        end
      end
    end



  // ---- STATE -> IO quantization (unbiased; handles scaling) ----
  assign p6tmp_sub_cast = {obj_y_prev[47], obj_y_prev};
  assign p6tmp_sub_cast_1 = {leak_1[47], leak_1};
  assign p6tmp_sub_temp = p6tmp_sub_cast - p6tmp_sub_cast_1;
  assign p6tmp_add_cast = ((p6tmp_sub_temp[48] == 1'b0) && (p6tmp_sub_temp[47] != 1'b0) ? 48'sh7FFFFFFFFFFF :
              ((p6tmp_sub_temp[48] == 1'b1) && (p6tmp_sub_temp[47] != 1'b1) ? 48'sh800000000000 :
              $signed(p6tmp_sub_temp[47:0])));
  assign p6tmp_add_cast_1 = {p6tmp_add_cast[47], p6tmp_add_cast};
  assign p6tmp_add_cast_2 = {d[47], d};
  assign p6tmp_add_temp = p6tmp_add_cast_1 + p6tmp_add_cast_2;
  assign tmp = ((p6tmp_add_temp[48] == 1'b0) && (p6tmp_add_temp[47] != 1'b0) ? 48'sh7FFFFFFFFFFF :
              ((p6tmp_add_temp[48] == 1'b1) && (p6tmp_add_temp[47] != 1'b1) ? 48'sh800000000000 :
              $signed(p6tmp_add_temp[47:0])));



  assign y = ((tmp[47] == 1'b0) && (tmp[46:24] != 23'b00000000000000000000000) ? 32'sb01111111111111111111111111111111 :
              ((tmp[47] == 1'b1) && (tmp[46:24] != 23'b11111111111111111111111) ? 32'sb10000000000000000000000000000000 :
              {tmp[24:0], 7'b0000000}));



endmodule  // MATLAB_System

