// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-10-21 16:08:37
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: hdlsrc_fir_equi
// EDAScriptGeneration: off
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 33
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s24,24 -> [-5.000000e-01 5.000000e-01)
// Input             : s33,0 -> [-4294967296 4294967296)
// Filter Internals  : Full Precision
//   Output          : s58,24 -> [-8589934592 8589934592)  (auto determined)
//   Product         : s56,24 -> [-2147483648 2147483648)  (auto determined)
//   Accumulator     : s58,24 -> [-8589934592 8589934592)  (auto determined)
//   Round Mode      : No rounding
//   Overflow Mode   : No overflow
// -------------------------------------------------------------
// Multipliers           : 33



`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [32:0] filter_in; //sfix33
  output  signed [57:0] filter_out; //sfix58_En24

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [23:0] coeff1 = 24'b000000000001010010010001; //sfix24_En24
  parameter signed [23:0] coeff2 = 24'b111111110000010100111101; //sfix24_En24
  parameter signed [23:0] coeff3 = 24'b111111010010101001010001; //sfix24_En24
  parameter signed [23:0] coeff4 = 24'b111110110001110000110111; //sfix24_En24
  parameter signed [23:0] coeff5 = 24'b111110101001000100101011; //sfix24_En24
  parameter signed [23:0] coeff6 = 24'b111111001111100111101011; //sfix24_En24
  parameter signed [23:0] coeff7 = 24'b000000011110111100001110; //sfix24_En24
  parameter signed [23:0] coeff8 = 24'b000001101000100101010101; //sfix24_En24
  parameter signed [23:0] coeff9 = 24'b000001101100110101011011; //sfix24_En24
  parameter signed [23:0] coeff10 = 24'b000000001100011100010001; //sfix24_En24
  parameter signed [23:0] coeff11 = 24'b111101110011011000101010; //sfix24_En24
  parameter signed [23:0] coeff12 = 24'b111100010101000000000001; //sfix24_En24
  parameter signed [23:0] coeff13 = 24'b111101101101001011001000; //sfix24_En24
  parameter signed [23:0] coeff14 = 24'b000010101000001101010010; //sfix24_En24
  parameter signed [23:0] coeff15 = 24'b001001101110100011000111; //sfix24_En24
  parameter signed [23:0] coeff16 = 24'b010000000001110111111000; //sfix24_En24
  parameter signed [23:0] coeff17 = 24'b010010100010111011101101; //sfix24_En24
  parameter signed [23:0] coeff18 = 24'b010000000001110111111000; //sfix24_En24
  parameter signed [23:0] coeff19 = 24'b001001101110100011000111; //sfix24_En24
  parameter signed [23:0] coeff20 = 24'b000010101000001101010010; //sfix24_En24
  parameter signed [23:0] coeff21 = 24'b111101101101001011001000; //sfix24_En24
  parameter signed [23:0] coeff22 = 24'b111100010101000000000001; //sfix24_En24
  parameter signed [23:0] coeff23 = 24'b111101110011011000101010; //sfix24_En24
  parameter signed [23:0] coeff24 = 24'b000000001100011100010001; //sfix24_En24
  parameter signed [23:0] coeff25 = 24'b000001101100110101011011; //sfix24_En24
  parameter signed [23:0] coeff26 = 24'b000001101000100101010101; //sfix24_En24
  parameter signed [23:0] coeff27 = 24'b000000011110111100001110; //sfix24_En24
  parameter signed [23:0] coeff28 = 24'b111111001111100111101011; //sfix24_En24
  parameter signed [23:0] coeff29 = 24'b111110101001000100101011; //sfix24_En24
  parameter signed [23:0] coeff30 = 24'b111110110001110000110111; //sfix24_En24
  parameter signed [23:0] coeff31 = 24'b111111010010101001010001; //sfix24_En24
  parameter signed [23:0] coeff32 = 24'b111111110000010100111101; //sfix24_En24
  parameter signed [23:0] coeff33 = 24'b000000000001010010010001; //sfix24_En24

  // Signals
  reg  signed [32:0] delay_pipeline [0:32] ; // sfix33
  wire signed [55:0] product33; // sfix56_En24
  wire signed [56:0] mul_temp; // sfix57_En24
  wire signed [55:0] product32; // sfix56_En24
  wire signed [56:0] mul_temp_1; // sfix57_En24
  wire signed [55:0] product31; // sfix56_En24
  wire signed [56:0] mul_temp_2; // sfix57_En24
  wire signed [55:0] product30; // sfix56_En24
  wire signed [56:0] mul_temp_3; // sfix57_En24
  wire signed [55:0] product29; // sfix56_En24
  wire signed [56:0] mul_temp_4; // sfix57_En24
  wire signed [55:0] product28; // sfix56_En24
  wire signed [56:0] mul_temp_5; // sfix57_En24
  wire signed [55:0] product27; // sfix56_En24
  wire signed [56:0] mul_temp_6; // sfix57_En24
  wire signed [55:0] product26; // sfix56_En24
  wire signed [56:0] mul_temp_7; // sfix57_En24
  wire signed [55:0] product25; // sfix56_En24
  wire signed [56:0] mul_temp_8; // sfix57_En24
  wire signed [55:0] product24; // sfix56_En24
  wire signed [56:0] mul_temp_9; // sfix57_En24
  wire signed [55:0] product23; // sfix56_En24
  wire signed [56:0] mul_temp_10; // sfix57_En24
  wire signed [55:0] product22; // sfix56_En24
  wire signed [56:0] mul_temp_11; // sfix57_En24
  wire signed [55:0] product21; // sfix56_En24
  wire signed [56:0] mul_temp_12; // sfix57_En24
  wire signed [55:0] product20; // sfix56_En24
  wire signed [56:0] mul_temp_13; // sfix57_En24
  wire signed [55:0] product19; // sfix56_En24
  wire signed [56:0] mul_temp_14; // sfix57_En24
  wire signed [55:0] product18; // sfix56_En24
  wire signed [56:0] mul_temp_15; // sfix57_En24
  wire signed [55:0] product17; // sfix56_En24
  wire signed [56:0] mul_temp_16; // sfix57_En24
  wire signed [55:0] product16; // sfix56_En24
  wire signed [56:0] mul_temp_17; // sfix57_En24
  wire signed [55:0] product15; // sfix56_En24
  wire signed [56:0] mul_temp_18; // sfix57_En24
  wire signed [55:0] product14; // sfix56_En24
  wire signed [56:0] mul_temp_19; // sfix57_En24
  wire signed [55:0] product13; // sfix56_En24
  wire signed [56:0] mul_temp_20; // sfix57_En24
  wire signed [55:0] product12; // sfix56_En24
  wire signed [56:0] mul_temp_21; // sfix57_En24
  wire signed [55:0] product11; // sfix56_En24
  wire signed [56:0] mul_temp_22; // sfix57_En24
  wire signed [55:0] product10; // sfix56_En24
  wire signed [56:0] mul_temp_23; // sfix57_En24
  wire signed [55:0] product9; // sfix56_En24
  wire signed [56:0] mul_temp_24; // sfix57_En24
  wire signed [55:0] product8; // sfix56_En24
  wire signed [56:0] mul_temp_25; // sfix57_En24
  wire signed [55:0] product7; // sfix56_En24
  wire signed [56:0] mul_temp_26; // sfix57_En24
  wire signed [55:0] product6; // sfix56_En24
  wire signed [56:0] mul_temp_27; // sfix57_En24
  wire signed [55:0] product5; // sfix56_En24
  wire signed [56:0] mul_temp_28; // sfix57_En24
  wire signed [55:0] product4; // sfix56_En24
  wire signed [56:0] mul_temp_29; // sfix57_En24
  wire signed [55:0] product3; // sfix56_En24
  wire signed [56:0] mul_temp_30; // sfix57_En24
  wire signed [55:0] product2; // sfix56_En24
  wire signed [56:0] mul_temp_31; // sfix57_En24
  wire signed [57:0] product1_cast; // sfix58_En24
  wire signed [55:0] product1; // sfix56_En24
  wire signed [56:0] mul_temp_32; // sfix57_En24
  wire signed [57:0] sum1; // sfix58_En24
  wire signed [57:0] add_signext; // sfix58_En24
  wire signed [57:0] add_signext_1; // sfix58_En24
  wire signed [58:0] add_temp; // sfix59_En24
  wire signed [57:0] sum2; // sfix58_En24
  wire signed [57:0] add_signext_2; // sfix58_En24
  wire signed [57:0] add_signext_3; // sfix58_En24
  wire signed [58:0] add_temp_1; // sfix59_En24
  wire signed [57:0] sum3; // sfix58_En24
  wire signed [57:0] add_signext_4; // sfix58_En24
  wire signed [57:0] add_signext_5; // sfix58_En24
  wire signed [58:0] add_temp_2; // sfix59_En24
  wire signed [57:0] sum4; // sfix58_En24
  wire signed [57:0] add_signext_6; // sfix58_En24
  wire signed [57:0] add_signext_7; // sfix58_En24
  wire signed [58:0] add_temp_3; // sfix59_En24
  wire signed [57:0] sum5; // sfix58_En24
  wire signed [57:0] add_signext_8; // sfix58_En24
  wire signed [57:0] add_signext_9; // sfix58_En24
  wire signed [58:0] add_temp_4; // sfix59_En24
  wire signed [57:0] sum6; // sfix58_En24
  wire signed [57:0] add_signext_10; // sfix58_En24
  wire signed [57:0] add_signext_11; // sfix58_En24
  wire signed [58:0] add_temp_5; // sfix59_En24
  wire signed [57:0] sum7; // sfix58_En24
  wire signed [57:0] add_signext_12; // sfix58_En24
  wire signed [57:0] add_signext_13; // sfix58_En24
  wire signed [58:0] add_temp_6; // sfix59_En24
  wire signed [57:0] sum8; // sfix58_En24
  wire signed [57:0] add_signext_14; // sfix58_En24
  wire signed [57:0] add_signext_15; // sfix58_En24
  wire signed [58:0] add_temp_7; // sfix59_En24
  wire signed [57:0] sum9; // sfix58_En24
  wire signed [57:0] add_signext_16; // sfix58_En24
  wire signed [57:0] add_signext_17; // sfix58_En24
  wire signed [58:0] add_temp_8; // sfix59_En24
  wire signed [57:0] sum10; // sfix58_En24
  wire signed [57:0] add_signext_18; // sfix58_En24
  wire signed [57:0] add_signext_19; // sfix58_En24
  wire signed [58:0] add_temp_9; // sfix59_En24
  wire signed [57:0] sum11; // sfix58_En24
  wire signed [57:0] add_signext_20; // sfix58_En24
  wire signed [57:0] add_signext_21; // sfix58_En24
  wire signed [58:0] add_temp_10; // sfix59_En24
  wire signed [57:0] sum12; // sfix58_En24
  wire signed [57:0] add_signext_22; // sfix58_En24
  wire signed [57:0] add_signext_23; // sfix58_En24
  wire signed [58:0] add_temp_11; // sfix59_En24
  wire signed [57:0] sum13; // sfix58_En24
  wire signed [57:0] add_signext_24; // sfix58_En24
  wire signed [57:0] add_signext_25; // sfix58_En24
  wire signed [58:0] add_temp_12; // sfix59_En24
  wire signed [57:0] sum14; // sfix58_En24
  wire signed [57:0] add_signext_26; // sfix58_En24
  wire signed [57:0] add_signext_27; // sfix58_En24
  wire signed [58:0] add_temp_13; // sfix59_En24
  wire signed [57:0] sum15; // sfix58_En24
  wire signed [57:0] add_signext_28; // sfix58_En24
  wire signed [57:0] add_signext_29; // sfix58_En24
  wire signed [58:0] add_temp_14; // sfix59_En24
  wire signed [57:0] sum16; // sfix58_En24
  wire signed [57:0] add_signext_30; // sfix58_En24
  wire signed [57:0] add_signext_31; // sfix58_En24
  wire signed [58:0] add_temp_15; // sfix59_En24
  wire signed [57:0] sum17; // sfix58_En24
  wire signed [57:0] add_signext_32; // sfix58_En24
  wire signed [57:0] add_signext_33; // sfix58_En24
  wire signed [58:0] add_temp_16; // sfix59_En24
  wire signed [57:0] sum18; // sfix58_En24
  wire signed [57:0] add_signext_34; // sfix58_En24
  wire signed [57:0] add_signext_35; // sfix58_En24
  wire signed [58:0] add_temp_17; // sfix59_En24
  wire signed [57:0] sum19; // sfix58_En24
  wire signed [57:0] add_signext_36; // sfix58_En24
  wire signed [57:0] add_signext_37; // sfix58_En24
  wire signed [58:0] add_temp_18; // sfix59_En24
  wire signed [57:0] sum20; // sfix58_En24
  wire signed [57:0] add_signext_38; // sfix58_En24
  wire signed [57:0] add_signext_39; // sfix58_En24
  wire signed [58:0] add_temp_19; // sfix59_En24
  wire signed [57:0] sum21; // sfix58_En24
  wire signed [57:0] add_signext_40; // sfix58_En24
  wire signed [57:0] add_signext_41; // sfix58_En24
  wire signed [58:0] add_temp_20; // sfix59_En24
  wire signed [57:0] sum22; // sfix58_En24
  wire signed [57:0] add_signext_42; // sfix58_En24
  wire signed [57:0] add_signext_43; // sfix58_En24
  wire signed [58:0] add_temp_21; // sfix59_En24
  wire signed [57:0] sum23; // sfix58_En24
  wire signed [57:0] add_signext_44; // sfix58_En24
  wire signed [57:0] add_signext_45; // sfix58_En24
  wire signed [58:0] add_temp_22; // sfix59_En24
  wire signed [57:0] sum24; // sfix58_En24
  wire signed [57:0] add_signext_46; // sfix58_En24
  wire signed [57:0] add_signext_47; // sfix58_En24
  wire signed [58:0] add_temp_23; // sfix59_En24
  wire signed [57:0] sum25; // sfix58_En24
  wire signed [57:0] add_signext_48; // sfix58_En24
  wire signed [57:0] add_signext_49; // sfix58_En24
  wire signed [58:0] add_temp_24; // sfix59_En24
  wire signed [57:0] sum26; // sfix58_En24
  wire signed [57:0] add_signext_50; // sfix58_En24
  wire signed [57:0] add_signext_51; // sfix58_En24
  wire signed [58:0] add_temp_25; // sfix59_En24
  wire signed [57:0] sum27; // sfix58_En24
  wire signed [57:0] add_signext_52; // sfix58_En24
  wire signed [57:0] add_signext_53; // sfix58_En24
  wire signed [58:0] add_temp_26; // sfix59_En24
  wire signed [57:0] sum28; // sfix58_En24
  wire signed [57:0] add_signext_54; // sfix58_En24
  wire signed [57:0] add_signext_55; // sfix58_En24
  wire signed [58:0] add_temp_27; // sfix59_En24
  wire signed [57:0] sum29; // sfix58_En24
  wire signed [57:0] add_signext_56; // sfix58_En24
  wire signed [57:0] add_signext_57; // sfix58_En24
  wire signed [58:0] add_temp_28; // sfix59_En24
  wire signed [57:0] sum30; // sfix58_En24
  wire signed [57:0] add_signext_58; // sfix58_En24
  wire signed [57:0] add_signext_59; // sfix58_En24
  wire signed [58:0] add_temp_29; // sfix59_En24
  wire signed [57:0] sum31; // sfix58_En24
  wire signed [57:0] add_signext_60; // sfix58_En24
  wire signed [57:0] add_signext_61; // sfix58_En24
  wire signed [58:0] add_temp_30; // sfix59_En24
  wire signed [57:0] sum32; // sfix58_En24
  wire signed [57:0] add_signext_62; // sfix58_En24
  wire signed [57:0] add_signext_63; // sfix58_En24
  wire signed [58:0] add_temp_31; // sfix59_En24
  reg  signed [57:0] output_register; // sfix58_En24

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
        end
      end
    end // Delay_Pipeline_process


  assign mul_temp = delay_pipeline[32] * coeff33;
  assign product33 = mul_temp[55:0];

  assign mul_temp_1 = delay_pipeline[31] * coeff32;
  assign product32 = mul_temp_1[55:0];

  assign mul_temp_2 = delay_pipeline[30] * coeff31;
  assign product31 = mul_temp_2[55:0];

  assign mul_temp_3 = delay_pipeline[29] * coeff30;
  assign product30 = mul_temp_3[55:0];

  assign mul_temp_4 = delay_pipeline[28] * coeff29;
  assign product29 = mul_temp_4[55:0];

  assign mul_temp_5 = delay_pipeline[27] * coeff28;
  assign product28 = mul_temp_5[55:0];

  assign mul_temp_6 = delay_pipeline[26] * coeff27;
  assign product27 = mul_temp_6[55:0];

  assign mul_temp_7 = delay_pipeline[25] * coeff26;
  assign product26 = mul_temp_7[55:0];

  assign mul_temp_8 = delay_pipeline[24] * coeff25;
  assign product25 = mul_temp_8[55:0];

  assign mul_temp_9 = delay_pipeline[23] * coeff24;
  assign product24 = mul_temp_9[55:0];

  assign mul_temp_10 = delay_pipeline[22] * coeff23;
  assign product23 = mul_temp_10[55:0];

  assign mul_temp_11 = delay_pipeline[21] * coeff22;
  assign product22 = mul_temp_11[55:0];

  assign mul_temp_12 = delay_pipeline[20] * coeff21;
  assign product21 = mul_temp_12[55:0];

  assign mul_temp_13 = delay_pipeline[19] * coeff20;
  assign product20 = mul_temp_13[55:0];

  assign mul_temp_14 = delay_pipeline[18] * coeff19;
  assign product19 = mul_temp_14[55:0];

  assign mul_temp_15 = delay_pipeline[17] * coeff18;
  assign product18 = mul_temp_15[55:0];

  assign mul_temp_16 = delay_pipeline[16] * coeff17;
  assign product17 = mul_temp_16[55:0];

  assign mul_temp_17 = delay_pipeline[15] * coeff16;
  assign product16 = mul_temp_17[55:0];

  assign mul_temp_18 = delay_pipeline[14] * coeff15;
  assign product15 = mul_temp_18[55:0];

  assign mul_temp_19 = delay_pipeline[13] * coeff14;
  assign product14 = mul_temp_19[55:0];

  assign mul_temp_20 = delay_pipeline[12] * coeff13;
  assign product13 = mul_temp_20[55:0];

  assign mul_temp_21 = delay_pipeline[11] * coeff12;
  assign product12 = mul_temp_21[55:0];

  assign mul_temp_22 = delay_pipeline[10] * coeff11;
  assign product11 = mul_temp_22[55:0];

  assign mul_temp_23 = delay_pipeline[9] * coeff10;
  assign product10 = mul_temp_23[55:0];

  assign mul_temp_24 = delay_pipeline[8] * coeff9;
  assign product9 = mul_temp_24[55:0];

  assign mul_temp_25 = delay_pipeline[7] * coeff8;
  assign product8 = mul_temp_25[55:0];

  assign mul_temp_26 = delay_pipeline[6] * coeff7;
  assign product7 = mul_temp_26[55:0];

  assign mul_temp_27 = delay_pipeline[5] * coeff6;
  assign product6 = mul_temp_27[55:0];

  assign mul_temp_28 = delay_pipeline[4] * coeff5;
  assign product5 = mul_temp_28[55:0];

  assign mul_temp_29 = delay_pipeline[3] * coeff4;
  assign product4 = mul_temp_29[55:0];

  assign mul_temp_30 = delay_pipeline[2] * coeff3;
  assign product3 = mul_temp_30[55:0];

  assign mul_temp_31 = delay_pipeline[1] * coeff2;
  assign product2 = mul_temp_31[55:0];

  assign product1_cast = $signed({{2{product1[55]}}, product1});

  assign mul_temp_32 = delay_pipeline[0] * coeff1;
  assign product1 = mul_temp_32[55:0];

  assign add_signext = product1_cast;
  assign add_signext_1 = $signed({{2{product2[55]}}, product2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[57:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{2{product3[55]}}, product3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[57:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{2{product4[55]}}, product4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[57:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{2{product5[55]}}, product5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[57:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{2{product6[55]}}, product6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[57:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{2{product7[55]}}, product7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[57:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{2{product8[55]}}, product8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[57:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{2{product9[55]}}, product9});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[57:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{2{product10[55]}}, product10});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[57:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{2{product11[55]}}, product11});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[57:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{2{product12[55]}}, product12});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = add_temp_10[57:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{2{product13[55]}}, product13});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = add_temp_11[57:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{2{product14[55]}}, product14});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = add_temp_12[57:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{2{product15[55]}}, product15});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = add_temp_13[57:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{2{product16[55]}}, product16});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = add_temp_14[57:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{2{product17[55]}}, product17});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = add_temp_15[57:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{2{product18[55]}}, product18});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = add_temp_16[57:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{2{product19[55]}}, product19});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = add_temp_17[57:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{2{product20[55]}}, product20});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = add_temp_18[57:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = $signed({{2{product21[55]}}, product21});
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = add_temp_19[57:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = $signed({{2{product22[55]}}, product22});
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = add_temp_20[57:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = $signed({{2{product23[55]}}, product23});
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = add_temp_21[57:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = $signed({{2{product24[55]}}, product24});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = add_temp_22[57:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = $signed({{2{product25[55]}}, product25});
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = add_temp_23[57:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = $signed({{2{product26[55]}}, product26});
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = add_temp_24[57:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = $signed({{2{product27[55]}}, product27});
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = add_temp_25[57:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = $signed({{2{product28[55]}}, product28});
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = add_temp_26[57:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = $signed({{2{product29[55]}}, product29});
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = add_temp_27[57:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = $signed({{2{product30[55]}}, product30});
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = add_temp_28[57:0];

  assign add_signext_58 = sum29;
  assign add_signext_59 = $signed({{2{product31[55]}}, product31});
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum30 = add_temp_29[57:0];

  assign add_signext_60 = sum30;
  assign add_signext_61 = $signed({{2{product32[55]}}, product32});
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum31 = add_temp_30[57:0];

  assign add_signext_62 = sum31;
  assign add_signext_63 = $signed({{2{product33[55]}}, product33});
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum32 = add_temp_31[57:0];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum32;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
