// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-10-13 15:57:03
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: hdlsrc_8k
// EDAScriptGeneration: off
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 52
// Stable            : Yes
// Linear Phase      : Yes (Type 2)
// Arithmetic        : fixed
// Numerator         : s24,24 -> [-5.000000e-01 5.000000e-01)
// Input             : s33,0 -> [-4294967296 4294967296)
// Filter Internals  : Specify Precision
//   Output          : s33,0 -> [-4294967296 4294967296)
//   Product         : s74,22 -> [-2251799813685248 2251799813685248)
//   Accumulator     : s76,22 -> [-9007199254740992 9007199254740992)
//   Round Mode      : convergent
//   Overflow Mode   : saturate
// -------------------------------------------------------------
// Multipliers           : 52



`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [32:0] filter_in; //sfix33
  output  signed [32:0] filter_out; //sfix33

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [23:0] coeff1 = 24'b000000000000100111000101; //sfix24_En24
  parameter signed [23:0] coeff2 = 24'b000000000100101011100100; //sfix24_En24
  parameter signed [23:0] coeff3 = 24'b000000001010011011001001; //sfix24_En24
  parameter signed [23:0] coeff4 = 24'b000000001110101101111101; //sfix24_En24
  parameter signed [23:0] coeff5 = 24'b000000001011110001000110; //sfix24_En24
  parameter signed [23:0] coeff6 = 24'b111111111111010110111011; //sfix24_En24
  parameter signed [23:0] coeff7 = 24'b111111101111010100100110; //sfix24_En24
  parameter signed [23:0] coeff8 = 24'b111111101000010111011001; //sfix24_En24
  parameter signed [23:0] coeff9 = 24'b111111110100110001100110; //sfix24_En24
  parameter signed [23:0] coeff10 = 24'b000000010000111000011000; //sfix24_En24
  parameter signed [23:0] coeff11 = 24'b000000101000010011010111; //sfix24_En24
  parameter signed [23:0] coeff12 = 24'b000000100010110010101100; //sfix24_En24
  parameter signed [23:0] coeff13 = 24'b111111111010010011100100; //sfix24_En24
  parameter signed [23:0] coeff14 = 24'b111111001000000010000001; //sfix24_En24
  parameter signed [23:0] coeff15 = 24'b111110111000000101110111; //sfix24_En24
  parameter signed [23:0] coeff16 = 24'b111111100110011110101110; //sfix24_En24
  parameter signed [23:0] coeff17 = 24'b000000111110100011011010; //sfix24_En24
  parameter signed [23:0] coeff18 = 24'b000001111100100000100110; //sfix24_En24
  parameter signed [23:0] coeff19 = 24'b000001011010111100100101; //sfix24_En24
  parameter signed [23:0] coeff20 = 24'b111111010001111110000101; //sfix24_En24
  parameter signed [23:0] coeff21 = 24'b111100110110010111101010; //sfix24_En24
  parameter signed [23:0] coeff22 = 24'b111100010101101100001000; //sfix24_En24
  parameter signed [23:0] coeff23 = 24'b111111011011001001100110; //sfix24_En24
  parameter signed [23:0] coeff24 = 24'b000101111000000000100110; //sfix24_En24
  parameter signed [23:0] coeff25 = 24'b001101010001101100010011; //sfix24_En24
  parameter signed [23:0] coeff26 = 24'b010010001101001000100000; //sfix24_En24
  parameter signed [23:0] coeff27 = 24'b010010001101001000100000; //sfix24_En24
  parameter signed [23:0] coeff28 = 24'b001101010001101100010011; //sfix24_En24
  parameter signed [23:0] coeff29 = 24'b000101111000000000100110; //sfix24_En24
  parameter signed [23:0] coeff30 = 24'b111111011011001001100110; //sfix24_En24
  parameter signed [23:0] coeff31 = 24'b111100010101101100001000; //sfix24_En24
  parameter signed [23:0] coeff32 = 24'b111100110110010111101010; //sfix24_En24
  parameter signed [23:0] coeff33 = 24'b111111010001111110000101; //sfix24_En24
  parameter signed [23:0] coeff34 = 24'b000001011010111100100101; //sfix24_En24
  parameter signed [23:0] coeff35 = 24'b000001111100100000100110; //sfix24_En24
  parameter signed [23:0] coeff36 = 24'b000000111110100011011010; //sfix24_En24
  parameter signed [23:0] coeff37 = 24'b111111100110011110101110; //sfix24_En24
  parameter signed [23:0] coeff38 = 24'b111110111000000101110111; //sfix24_En24
  parameter signed [23:0] coeff39 = 24'b111111001000000010000001; //sfix24_En24
  parameter signed [23:0] coeff40 = 24'b111111111010010011100100; //sfix24_En24
  parameter signed [23:0] coeff41 = 24'b000000100010110010101100; //sfix24_En24
  parameter signed [23:0] coeff42 = 24'b000000101000010011010111; //sfix24_En24
  parameter signed [23:0] coeff43 = 24'b000000010000111000011000; //sfix24_En24
  parameter signed [23:0] coeff44 = 24'b111111110100110001100110; //sfix24_En24
  parameter signed [23:0] coeff45 = 24'b111111101000010111011001; //sfix24_En24
  parameter signed [23:0] coeff46 = 24'b111111101111010100100110; //sfix24_En24
  parameter signed [23:0] coeff47 = 24'b111111111111010110111011; //sfix24_En24
  parameter signed [23:0] coeff48 = 24'b000000001011110001000110; //sfix24_En24
  parameter signed [23:0] coeff49 = 24'b000000001110101101111101; //sfix24_En24
  parameter signed [23:0] coeff50 = 24'b000000001010011011001001; //sfix24_En24
  parameter signed [23:0] coeff51 = 24'b000000000100101011100100; //sfix24_En24
  parameter signed [23:0] coeff52 = 24'b000000000000100111000101; //sfix24_En24

  // Signals
  reg  signed [32:0] delay_pipeline [0:51] ; // sfix33
  wire signed [73:0] product52; // sfix74_En22
  wire signed [56:0] mul_temp; // sfix57_En24
  wire signed [73:0] product51; // sfix74_En22
  wire signed [56:0] mul_temp_1; // sfix57_En24
  wire signed [73:0] product50; // sfix74_En22
  wire signed [56:0] mul_temp_2; // sfix57_En24
  wire signed [73:0] product49; // sfix74_En22
  wire signed [56:0] mul_temp_3; // sfix57_En24
  wire signed [73:0] product48; // sfix74_En22
  wire signed [56:0] mul_temp_4; // sfix57_En24
  wire signed [73:0] product47; // sfix74_En22
  wire signed [56:0] mul_temp_5; // sfix57_En24
  wire signed [73:0] product46; // sfix74_En22
  wire signed [56:0] mul_temp_6; // sfix57_En24
  wire signed [73:0] product45; // sfix74_En22
  wire signed [56:0] mul_temp_7; // sfix57_En24
  wire signed [73:0] product44; // sfix74_En22
  wire signed [56:0] mul_temp_8; // sfix57_En24
  wire signed [73:0] product43; // sfix74_En22
  wire signed [56:0] mul_temp_9; // sfix57_En24
  wire signed [73:0] product42; // sfix74_En22
  wire signed [56:0] mul_temp_10; // sfix57_En24
  wire signed [73:0] product41; // sfix74_En22
  wire signed [56:0] mul_temp_11; // sfix57_En24
  wire signed [73:0] product40; // sfix74_En22
  wire signed [56:0] mul_temp_12; // sfix57_En24
  wire signed [73:0] product39; // sfix74_En22
  wire signed [56:0] mul_temp_13; // sfix57_En24
  wire signed [73:0] product38; // sfix74_En22
  wire signed [56:0] mul_temp_14; // sfix57_En24
  wire signed [73:0] product37; // sfix74_En22
  wire signed [56:0] mul_temp_15; // sfix57_En24
  wire signed [73:0] product36; // sfix74_En22
  wire signed [56:0] mul_temp_16; // sfix57_En24
  wire signed [73:0] product35; // sfix74_En22
  wire signed [56:0] mul_temp_17; // sfix57_En24
  wire signed [73:0] product34; // sfix74_En22
  wire signed [56:0] mul_temp_18; // sfix57_En24
  wire signed [73:0] product33; // sfix74_En22
  wire signed [56:0] mul_temp_19; // sfix57_En24
  wire signed [73:0] product32; // sfix74_En22
  wire signed [56:0] mul_temp_20; // sfix57_En24
  wire signed [73:0] product31; // sfix74_En22
  wire signed [56:0] mul_temp_21; // sfix57_En24
  wire signed [73:0] product30; // sfix74_En22
  wire signed [56:0] mul_temp_22; // sfix57_En24
  wire signed [73:0] product29; // sfix74_En22
  wire signed [56:0] mul_temp_23; // sfix57_En24
  wire signed [73:0] product28; // sfix74_En22
  wire signed [56:0] mul_temp_24; // sfix57_En24
  wire signed [73:0] product27; // sfix74_En22
  wire signed [56:0] mul_temp_25; // sfix57_En24
  wire signed [73:0] product26; // sfix74_En22
  wire signed [56:0] mul_temp_26; // sfix57_En24
  wire signed [73:0] product25; // sfix74_En22
  wire signed [56:0] mul_temp_27; // sfix57_En24
  wire signed [73:0] product24; // sfix74_En22
  wire signed [56:0] mul_temp_28; // sfix57_En24
  wire signed [73:0] product23; // sfix74_En22
  wire signed [56:0] mul_temp_29; // sfix57_En24
  wire signed [73:0] product22; // sfix74_En22
  wire signed [56:0] mul_temp_30; // sfix57_En24
  wire signed [73:0] product21; // sfix74_En22
  wire signed [56:0] mul_temp_31; // sfix57_En24
  wire signed [73:0] product20; // sfix74_En22
  wire signed [56:0] mul_temp_32; // sfix57_En24
  wire signed [73:0] product19; // sfix74_En22
  wire signed [56:0] mul_temp_33; // sfix57_En24
  wire signed [73:0] product18; // sfix74_En22
  wire signed [56:0] mul_temp_34; // sfix57_En24
  wire signed [73:0] product17; // sfix74_En22
  wire signed [56:0] mul_temp_35; // sfix57_En24
  wire signed [73:0] product16; // sfix74_En22
  wire signed [56:0] mul_temp_36; // sfix57_En24
  wire signed [73:0] product15; // sfix74_En22
  wire signed [56:0] mul_temp_37; // sfix57_En24
  wire signed [73:0] product14; // sfix74_En22
  wire signed [56:0] mul_temp_38; // sfix57_En24
  wire signed [73:0] product13; // sfix74_En22
  wire signed [56:0] mul_temp_39; // sfix57_En24
  wire signed [73:0] product12; // sfix74_En22
  wire signed [56:0] mul_temp_40; // sfix57_En24
  wire signed [73:0] product11; // sfix74_En22
  wire signed [56:0] mul_temp_41; // sfix57_En24
  wire signed [73:0] product10; // sfix74_En22
  wire signed [56:0] mul_temp_42; // sfix57_En24
  wire signed [73:0] product9; // sfix74_En22
  wire signed [56:0] mul_temp_43; // sfix57_En24
  wire signed [73:0] product8; // sfix74_En22
  wire signed [56:0] mul_temp_44; // sfix57_En24
  wire signed [73:0] product7; // sfix74_En22
  wire signed [56:0] mul_temp_45; // sfix57_En24
  wire signed [73:0] product6; // sfix74_En22
  wire signed [56:0] mul_temp_46; // sfix57_En24
  wire signed [73:0] product5; // sfix74_En22
  wire signed [56:0] mul_temp_47; // sfix57_En24
  wire signed [73:0] product4; // sfix74_En22
  wire signed [56:0] mul_temp_48; // sfix57_En24
  wire signed [73:0] product3; // sfix74_En22
  wire signed [56:0] mul_temp_49; // sfix57_En24
  wire signed [73:0] product2; // sfix74_En22
  wire signed [56:0] mul_temp_50; // sfix57_En24
  wire signed [75:0] product1_cast; // sfix76_En22
  wire signed [73:0] product1; // sfix74_En22
  wire signed [56:0] mul_temp_51; // sfix57_En24
  wire signed [75:0] sum1; // sfix76_En22
  wire signed [75:0] add_signext; // sfix76_En22
  wire signed [75:0] add_signext_1; // sfix76_En22
  wire signed [76:0] add_temp; // sfix77_En22
  wire signed [75:0] sum2; // sfix76_En22
  wire signed [75:0] add_signext_2; // sfix76_En22
  wire signed [75:0] add_signext_3; // sfix76_En22
  wire signed [76:0] add_temp_1; // sfix77_En22
  wire signed [75:0] sum3; // sfix76_En22
  wire signed [75:0] add_signext_4; // sfix76_En22
  wire signed [75:0] add_signext_5; // sfix76_En22
  wire signed [76:0] add_temp_2; // sfix77_En22
  wire signed [75:0] sum4; // sfix76_En22
  wire signed [75:0] add_signext_6; // sfix76_En22
  wire signed [75:0] add_signext_7; // sfix76_En22
  wire signed [76:0] add_temp_3; // sfix77_En22
  wire signed [75:0] sum5; // sfix76_En22
  wire signed [75:0] add_signext_8; // sfix76_En22
  wire signed [75:0] add_signext_9; // sfix76_En22
  wire signed [76:0] add_temp_4; // sfix77_En22
  wire signed [75:0] sum6; // sfix76_En22
  wire signed [75:0] add_signext_10; // sfix76_En22
  wire signed [75:0] add_signext_11; // sfix76_En22
  wire signed [76:0] add_temp_5; // sfix77_En22
  wire signed [75:0] sum7; // sfix76_En22
  wire signed [75:0] add_signext_12; // sfix76_En22
  wire signed [75:0] add_signext_13; // sfix76_En22
  wire signed [76:0] add_temp_6; // sfix77_En22
  wire signed [75:0] sum8; // sfix76_En22
  wire signed [75:0] add_signext_14; // sfix76_En22
  wire signed [75:0] add_signext_15; // sfix76_En22
  wire signed [76:0] add_temp_7; // sfix77_En22
  wire signed [75:0] sum9; // sfix76_En22
  wire signed [75:0] add_signext_16; // sfix76_En22
  wire signed [75:0] add_signext_17; // sfix76_En22
  wire signed [76:0] add_temp_8; // sfix77_En22
  wire signed [75:0] sum10; // sfix76_En22
  wire signed [75:0] add_signext_18; // sfix76_En22
  wire signed [75:0] add_signext_19; // sfix76_En22
  wire signed [76:0] add_temp_9; // sfix77_En22
  wire signed [75:0] sum11; // sfix76_En22
  wire signed [75:0] add_signext_20; // sfix76_En22
  wire signed [75:0] add_signext_21; // sfix76_En22
  wire signed [76:0] add_temp_10; // sfix77_En22
  wire signed [75:0] sum12; // sfix76_En22
  wire signed [75:0] add_signext_22; // sfix76_En22
  wire signed [75:0] add_signext_23; // sfix76_En22
  wire signed [76:0] add_temp_11; // sfix77_En22
  wire signed [75:0] sum13; // sfix76_En22
  wire signed [75:0] add_signext_24; // sfix76_En22
  wire signed [75:0] add_signext_25; // sfix76_En22
  wire signed [76:0] add_temp_12; // sfix77_En22
  wire signed [75:0] sum14; // sfix76_En22
  wire signed [75:0] add_signext_26; // sfix76_En22
  wire signed [75:0] add_signext_27; // sfix76_En22
  wire signed [76:0] add_temp_13; // sfix77_En22
  wire signed [75:0] sum15; // sfix76_En22
  wire signed [75:0] add_signext_28; // sfix76_En22
  wire signed [75:0] add_signext_29; // sfix76_En22
  wire signed [76:0] add_temp_14; // sfix77_En22
  wire signed [75:0] sum16; // sfix76_En22
  wire signed [75:0] add_signext_30; // sfix76_En22
  wire signed [75:0] add_signext_31; // sfix76_En22
  wire signed [76:0] add_temp_15; // sfix77_En22
  wire signed [75:0] sum17; // sfix76_En22
  wire signed [75:0] add_signext_32; // sfix76_En22
  wire signed [75:0] add_signext_33; // sfix76_En22
  wire signed [76:0] add_temp_16; // sfix77_En22
  wire signed [75:0] sum18; // sfix76_En22
  wire signed [75:0] add_signext_34; // sfix76_En22
  wire signed [75:0] add_signext_35; // sfix76_En22
  wire signed [76:0] add_temp_17; // sfix77_En22
  wire signed [75:0] sum19; // sfix76_En22
  wire signed [75:0] add_signext_36; // sfix76_En22
  wire signed [75:0] add_signext_37; // sfix76_En22
  wire signed [76:0] add_temp_18; // sfix77_En22
  wire signed [75:0] sum20; // sfix76_En22
  wire signed [75:0] add_signext_38; // sfix76_En22
  wire signed [75:0] add_signext_39; // sfix76_En22
  wire signed [76:0] add_temp_19; // sfix77_En22
  wire signed [75:0] sum21; // sfix76_En22
  wire signed [75:0] add_signext_40; // sfix76_En22
  wire signed [75:0] add_signext_41; // sfix76_En22
  wire signed [76:0] add_temp_20; // sfix77_En22
  wire signed [75:0] sum22; // sfix76_En22
  wire signed [75:0] add_signext_42; // sfix76_En22
  wire signed [75:0] add_signext_43; // sfix76_En22
  wire signed [76:0] add_temp_21; // sfix77_En22
  wire signed [75:0] sum23; // sfix76_En22
  wire signed [75:0] add_signext_44; // sfix76_En22
  wire signed [75:0] add_signext_45; // sfix76_En22
  wire signed [76:0] add_temp_22; // sfix77_En22
  wire signed [75:0] sum24; // sfix76_En22
  wire signed [75:0] add_signext_46; // sfix76_En22
  wire signed [75:0] add_signext_47; // sfix76_En22
  wire signed [76:0] add_temp_23; // sfix77_En22
  wire signed [75:0] sum25; // sfix76_En22
  wire signed [75:0] add_signext_48; // sfix76_En22
  wire signed [75:0] add_signext_49; // sfix76_En22
  wire signed [76:0] add_temp_24; // sfix77_En22
  wire signed [75:0] sum26; // sfix76_En22
  wire signed [75:0] add_signext_50; // sfix76_En22
  wire signed [75:0] add_signext_51; // sfix76_En22
  wire signed [76:0] add_temp_25; // sfix77_En22
  wire signed [75:0] sum27; // sfix76_En22
  wire signed [75:0] add_signext_52; // sfix76_En22
  wire signed [75:0] add_signext_53; // sfix76_En22
  wire signed [76:0] add_temp_26; // sfix77_En22
  wire signed [75:0] sum28; // sfix76_En22
  wire signed [75:0] add_signext_54; // sfix76_En22
  wire signed [75:0] add_signext_55; // sfix76_En22
  wire signed [76:0] add_temp_27; // sfix77_En22
  wire signed [75:0] sum29; // sfix76_En22
  wire signed [75:0] add_signext_56; // sfix76_En22
  wire signed [75:0] add_signext_57; // sfix76_En22
  wire signed [76:0] add_temp_28; // sfix77_En22
  wire signed [75:0] sum30; // sfix76_En22
  wire signed [75:0] add_signext_58; // sfix76_En22
  wire signed [75:0] add_signext_59; // sfix76_En22
  wire signed [76:0] add_temp_29; // sfix77_En22
  wire signed [75:0] sum31; // sfix76_En22
  wire signed [75:0] add_signext_60; // sfix76_En22
  wire signed [75:0] add_signext_61; // sfix76_En22
  wire signed [76:0] add_temp_30; // sfix77_En22
  wire signed [75:0] sum32; // sfix76_En22
  wire signed [75:0] add_signext_62; // sfix76_En22
  wire signed [75:0] add_signext_63; // sfix76_En22
  wire signed [76:0] add_temp_31; // sfix77_En22
  wire signed [75:0] sum33; // sfix76_En22
  wire signed [75:0] add_signext_64; // sfix76_En22
  wire signed [75:0] add_signext_65; // sfix76_En22
  wire signed [76:0] add_temp_32; // sfix77_En22
  wire signed [75:0] sum34; // sfix76_En22
  wire signed [75:0] add_signext_66; // sfix76_En22
  wire signed [75:0] add_signext_67; // sfix76_En22
  wire signed [76:0] add_temp_33; // sfix77_En22
  wire signed [75:0] sum35; // sfix76_En22
  wire signed [75:0] add_signext_68; // sfix76_En22
  wire signed [75:0] add_signext_69; // sfix76_En22
  wire signed [76:0] add_temp_34; // sfix77_En22
  wire signed [75:0] sum36; // sfix76_En22
  wire signed [75:0] add_signext_70; // sfix76_En22
  wire signed [75:0] add_signext_71; // sfix76_En22
  wire signed [76:0] add_temp_35; // sfix77_En22
  wire signed [75:0] sum37; // sfix76_En22
  wire signed [75:0] add_signext_72; // sfix76_En22
  wire signed [75:0] add_signext_73; // sfix76_En22
  wire signed [76:0] add_temp_36; // sfix77_En22
  wire signed [75:0] sum38; // sfix76_En22
  wire signed [75:0] add_signext_74; // sfix76_En22
  wire signed [75:0] add_signext_75; // sfix76_En22
  wire signed [76:0] add_temp_37; // sfix77_En22
  wire signed [75:0] sum39; // sfix76_En22
  wire signed [75:0] add_signext_76; // sfix76_En22
  wire signed [75:0] add_signext_77; // sfix76_En22
  wire signed [76:0] add_temp_38; // sfix77_En22
  wire signed [75:0] sum40; // sfix76_En22
  wire signed [75:0] add_signext_78; // sfix76_En22
  wire signed [75:0] add_signext_79; // sfix76_En22
  wire signed [76:0] add_temp_39; // sfix77_En22
  wire signed [75:0] sum41; // sfix76_En22
  wire signed [75:0] add_signext_80; // sfix76_En22
  wire signed [75:0] add_signext_81; // sfix76_En22
  wire signed [76:0] add_temp_40; // sfix77_En22
  wire signed [75:0] sum42; // sfix76_En22
  wire signed [75:0] add_signext_82; // sfix76_En22
  wire signed [75:0] add_signext_83; // sfix76_En22
  wire signed [76:0] add_temp_41; // sfix77_En22
  wire signed [75:0] sum43; // sfix76_En22
  wire signed [75:0] add_signext_84; // sfix76_En22
  wire signed [75:0] add_signext_85; // sfix76_En22
  wire signed [76:0] add_temp_42; // sfix77_En22
  wire signed [75:0] sum44; // sfix76_En22
  wire signed [75:0] add_signext_86; // sfix76_En22
  wire signed [75:0] add_signext_87; // sfix76_En22
  wire signed [76:0] add_temp_43; // sfix77_En22
  wire signed [75:0] sum45; // sfix76_En22
  wire signed [75:0] add_signext_88; // sfix76_En22
  wire signed [75:0] add_signext_89; // sfix76_En22
  wire signed [76:0] add_temp_44; // sfix77_En22
  wire signed [75:0] sum46; // sfix76_En22
  wire signed [75:0] add_signext_90; // sfix76_En22
  wire signed [75:0] add_signext_91; // sfix76_En22
  wire signed [76:0] add_temp_45; // sfix77_En22
  wire signed [75:0] sum47; // sfix76_En22
  wire signed [75:0] add_signext_92; // sfix76_En22
  wire signed [75:0] add_signext_93; // sfix76_En22
  wire signed [76:0] add_temp_46; // sfix77_En22
  wire signed [75:0] sum48; // sfix76_En22
  wire signed [75:0] add_signext_94; // sfix76_En22
  wire signed [75:0] add_signext_95; // sfix76_En22
  wire signed [76:0] add_temp_47; // sfix77_En22
  wire signed [75:0] sum49; // sfix76_En22
  wire signed [75:0] add_signext_96; // sfix76_En22
  wire signed [75:0] add_signext_97; // sfix76_En22
  wire signed [76:0] add_temp_48; // sfix77_En22
  wire signed [75:0] sum50; // sfix76_En22
  wire signed [75:0] add_signext_98; // sfix76_En22
  wire signed [75:0] add_signext_99; // sfix76_En22
  wire signed [76:0] add_temp_49; // sfix77_En22
  wire signed [75:0] sum51; // sfix76_En22
  wire signed [75:0] add_signext_100; // sfix76_En22
  wire signed [75:0] add_signext_101; // sfix76_En22
  wire signed [76:0] add_temp_50; // sfix77_En22
  wire signed [32:0] output_typeconvert; // sfix33
  reg  signed [32:0] output_register; // sfix33

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
        delay_pipeline[43] <= 0;
        delay_pipeline[44] <= 0;
        delay_pipeline[45] <= 0;
        delay_pipeline[46] <= 0;
        delay_pipeline[47] <= 0;
        delay_pipeline[48] <= 0;
        delay_pipeline[49] <= 0;
        delay_pipeline[50] <= 0;
        delay_pipeline[51] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
          delay_pipeline[43] <= delay_pipeline[42];
          delay_pipeline[44] <= delay_pipeline[43];
          delay_pipeline[45] <= delay_pipeline[44];
          delay_pipeline[46] <= delay_pipeline[45];
          delay_pipeline[47] <= delay_pipeline[46];
          delay_pipeline[48] <= delay_pipeline[47];
          delay_pipeline[49] <= delay_pipeline[48];
          delay_pipeline[50] <= delay_pipeline[49];
          delay_pipeline[51] <= delay_pipeline[50];
        end
      end
    end // Delay_Pipeline_process


  assign mul_temp = delay_pipeline[51] * coeff52;
  assign product52 = ({{19{mul_temp[56]}}, mul_temp[56:0]} + {mul_temp[2], {1{~mul_temp[2]}}})>>>2;

  assign mul_temp_1 = delay_pipeline[50] * coeff51;
  assign product51 = ({{19{mul_temp_1[56]}}, mul_temp_1[56:0]} + {mul_temp_1[2], {1{~mul_temp_1[2]}}})>>>2;

  assign mul_temp_2 = delay_pipeline[49] * coeff50;
  assign product50 = ({{19{mul_temp_2[56]}}, mul_temp_2[56:0]} + {mul_temp_2[2], {1{~mul_temp_2[2]}}})>>>2;

  assign mul_temp_3 = delay_pipeline[48] * coeff49;
  assign product49 = ({{19{mul_temp_3[56]}}, mul_temp_3[56:0]} + {mul_temp_3[2], {1{~mul_temp_3[2]}}})>>>2;

  assign mul_temp_4 = delay_pipeline[47] * coeff48;
  assign product48 = ({{19{mul_temp_4[56]}}, mul_temp_4[56:0]} + {mul_temp_4[2], {1{~mul_temp_4[2]}}})>>>2;

  assign mul_temp_5 = delay_pipeline[46] * coeff47;
  assign product47 = ({{19{mul_temp_5[56]}}, mul_temp_5[56:0]} + {mul_temp_5[2], {1{~mul_temp_5[2]}}})>>>2;

  assign mul_temp_6 = delay_pipeline[45] * coeff46;
  assign product46 = ({{19{mul_temp_6[56]}}, mul_temp_6[56:0]} + {mul_temp_6[2], {1{~mul_temp_6[2]}}})>>>2;

  assign mul_temp_7 = delay_pipeline[44] * coeff45;
  assign product45 = ({{19{mul_temp_7[56]}}, mul_temp_7[56:0]} + {mul_temp_7[2], {1{~mul_temp_7[2]}}})>>>2;

  assign mul_temp_8 = delay_pipeline[43] * coeff44;
  assign product44 = ({{19{mul_temp_8[56]}}, mul_temp_8[56:0]} + {mul_temp_8[2], {1{~mul_temp_8[2]}}})>>>2;

  assign mul_temp_9 = delay_pipeline[42] * coeff43;
  assign product43 = ({{19{mul_temp_9[56]}}, mul_temp_9[56:0]} + {mul_temp_9[2], {1{~mul_temp_9[2]}}})>>>2;

  assign mul_temp_10 = delay_pipeline[41] * coeff42;
  assign product42 = ({{19{mul_temp_10[56]}}, mul_temp_10[56:0]} + {mul_temp_10[2], {1{~mul_temp_10[2]}}})>>>2;

  assign mul_temp_11 = delay_pipeline[40] * coeff41;
  assign product41 = ({{19{mul_temp_11[56]}}, mul_temp_11[56:0]} + {mul_temp_11[2], {1{~mul_temp_11[2]}}})>>>2;

  assign mul_temp_12 = delay_pipeline[39] * coeff40;
  assign product40 = ({{19{mul_temp_12[56]}}, mul_temp_12[56:0]} + {mul_temp_12[2], {1{~mul_temp_12[2]}}})>>>2;

  assign mul_temp_13 = delay_pipeline[38] * coeff39;
  assign product39 = ({{19{mul_temp_13[56]}}, mul_temp_13[56:0]} + {mul_temp_13[2], {1{~mul_temp_13[2]}}})>>>2;

  assign mul_temp_14 = delay_pipeline[37] * coeff38;
  assign product38 = ({{19{mul_temp_14[56]}}, mul_temp_14[56:0]} + {mul_temp_14[2], {1{~mul_temp_14[2]}}})>>>2;

  assign mul_temp_15 = delay_pipeline[36] * coeff37;
  assign product37 = ({{19{mul_temp_15[56]}}, mul_temp_15[56:0]} + {mul_temp_15[2], {1{~mul_temp_15[2]}}})>>>2;

  assign mul_temp_16 = delay_pipeline[35] * coeff36;
  assign product36 = ({{19{mul_temp_16[56]}}, mul_temp_16[56:0]} + {mul_temp_16[2], {1{~mul_temp_16[2]}}})>>>2;

  assign mul_temp_17 = delay_pipeline[34] * coeff35;
  assign product35 = ({{19{mul_temp_17[56]}}, mul_temp_17[56:0]} + {mul_temp_17[2], {1{~mul_temp_17[2]}}})>>>2;

  assign mul_temp_18 = delay_pipeline[33] * coeff34;
  assign product34 = ({{19{mul_temp_18[56]}}, mul_temp_18[56:0]} + {mul_temp_18[2], {1{~mul_temp_18[2]}}})>>>2;

  assign mul_temp_19 = delay_pipeline[32] * coeff33;
  assign product33 = ({{19{mul_temp_19[56]}}, mul_temp_19[56:0]} + {mul_temp_19[2], {1{~mul_temp_19[2]}}})>>>2;

  assign mul_temp_20 = delay_pipeline[31] * coeff32;
  assign product32 = ({{19{mul_temp_20[56]}}, mul_temp_20[56:0]} + {mul_temp_20[2], {1{~mul_temp_20[2]}}})>>>2;

  assign mul_temp_21 = delay_pipeline[30] * coeff31;
  assign product31 = ({{19{mul_temp_21[56]}}, mul_temp_21[56:0]} + {mul_temp_21[2], {1{~mul_temp_21[2]}}})>>>2;

  assign mul_temp_22 = delay_pipeline[29] * coeff30;
  assign product30 = ({{19{mul_temp_22[56]}}, mul_temp_22[56:0]} + {mul_temp_22[2], {1{~mul_temp_22[2]}}})>>>2;

  assign mul_temp_23 = delay_pipeline[28] * coeff29;
  assign product29 = ({{19{mul_temp_23[56]}}, mul_temp_23[56:0]} + {mul_temp_23[2], {1{~mul_temp_23[2]}}})>>>2;

  assign mul_temp_24 = delay_pipeline[27] * coeff28;
  assign product28 = ({{19{mul_temp_24[56]}}, mul_temp_24[56:0]} + {mul_temp_24[2], {1{~mul_temp_24[2]}}})>>>2;

  assign mul_temp_25 = delay_pipeline[26] * coeff27;
  assign product27 = ({{19{mul_temp_25[56]}}, mul_temp_25[56:0]} + {mul_temp_25[2], {1{~mul_temp_25[2]}}})>>>2;

  assign mul_temp_26 = delay_pipeline[25] * coeff26;
  assign product26 = ({{19{mul_temp_26[56]}}, mul_temp_26[56:0]} + {mul_temp_26[2], {1{~mul_temp_26[2]}}})>>>2;

  assign mul_temp_27 = delay_pipeline[24] * coeff25;
  assign product25 = ({{19{mul_temp_27[56]}}, mul_temp_27[56:0]} + {mul_temp_27[2], {1{~mul_temp_27[2]}}})>>>2;

  assign mul_temp_28 = delay_pipeline[23] * coeff24;
  assign product24 = ({{19{mul_temp_28[56]}}, mul_temp_28[56:0]} + {mul_temp_28[2], {1{~mul_temp_28[2]}}})>>>2;

  assign mul_temp_29 = delay_pipeline[22] * coeff23;
  assign product23 = ({{19{mul_temp_29[56]}}, mul_temp_29[56:0]} + {mul_temp_29[2], {1{~mul_temp_29[2]}}})>>>2;

  assign mul_temp_30 = delay_pipeline[21] * coeff22;
  assign product22 = ({{19{mul_temp_30[56]}}, mul_temp_30[56:0]} + {mul_temp_30[2], {1{~mul_temp_30[2]}}})>>>2;

  assign mul_temp_31 = delay_pipeline[20] * coeff21;
  assign product21 = ({{19{mul_temp_31[56]}}, mul_temp_31[56:0]} + {mul_temp_31[2], {1{~mul_temp_31[2]}}})>>>2;

  assign mul_temp_32 = delay_pipeline[19] * coeff20;
  assign product20 = ({{19{mul_temp_32[56]}}, mul_temp_32[56:0]} + {mul_temp_32[2], {1{~mul_temp_32[2]}}})>>>2;

  assign mul_temp_33 = delay_pipeline[18] * coeff19;
  assign product19 = ({{19{mul_temp_33[56]}}, mul_temp_33[56:0]} + {mul_temp_33[2], {1{~mul_temp_33[2]}}})>>>2;

  assign mul_temp_34 = delay_pipeline[17] * coeff18;
  assign product18 = ({{19{mul_temp_34[56]}}, mul_temp_34[56:0]} + {mul_temp_34[2], {1{~mul_temp_34[2]}}})>>>2;

  assign mul_temp_35 = delay_pipeline[16] * coeff17;
  assign product17 = ({{19{mul_temp_35[56]}}, mul_temp_35[56:0]} + {mul_temp_35[2], {1{~mul_temp_35[2]}}})>>>2;

  assign mul_temp_36 = delay_pipeline[15] * coeff16;
  assign product16 = ({{19{mul_temp_36[56]}}, mul_temp_36[56:0]} + {mul_temp_36[2], {1{~mul_temp_36[2]}}})>>>2;

  assign mul_temp_37 = delay_pipeline[14] * coeff15;
  assign product15 = ({{19{mul_temp_37[56]}}, mul_temp_37[56:0]} + {mul_temp_37[2], {1{~mul_temp_37[2]}}})>>>2;

  assign mul_temp_38 = delay_pipeline[13] * coeff14;
  assign product14 = ({{19{mul_temp_38[56]}}, mul_temp_38[56:0]} + {mul_temp_38[2], {1{~mul_temp_38[2]}}})>>>2;

  assign mul_temp_39 = delay_pipeline[12] * coeff13;
  assign product13 = ({{19{mul_temp_39[56]}}, mul_temp_39[56:0]} + {mul_temp_39[2], {1{~mul_temp_39[2]}}})>>>2;

  assign mul_temp_40 = delay_pipeline[11] * coeff12;
  assign product12 = ({{19{mul_temp_40[56]}}, mul_temp_40[56:0]} + {mul_temp_40[2], {1{~mul_temp_40[2]}}})>>>2;

  assign mul_temp_41 = delay_pipeline[10] * coeff11;
  assign product11 = ({{19{mul_temp_41[56]}}, mul_temp_41[56:0]} + {mul_temp_41[2], {1{~mul_temp_41[2]}}})>>>2;

  assign mul_temp_42 = delay_pipeline[9] * coeff10;
  assign product10 = ({{19{mul_temp_42[56]}}, mul_temp_42[56:0]} + {mul_temp_42[2], {1{~mul_temp_42[2]}}})>>>2;

  assign mul_temp_43 = delay_pipeline[8] * coeff9;
  assign product9 = ({{19{mul_temp_43[56]}}, mul_temp_43[56:0]} + {mul_temp_43[2], {1{~mul_temp_43[2]}}})>>>2;

  assign mul_temp_44 = delay_pipeline[7] * coeff8;
  assign product8 = ({{19{mul_temp_44[56]}}, mul_temp_44[56:0]} + {mul_temp_44[2], {1{~mul_temp_44[2]}}})>>>2;

  assign mul_temp_45 = delay_pipeline[6] * coeff7;
  assign product7 = ({{19{mul_temp_45[56]}}, mul_temp_45[56:0]} + {mul_temp_45[2], {1{~mul_temp_45[2]}}})>>>2;

  assign mul_temp_46 = delay_pipeline[5] * coeff6;
  assign product6 = ({{19{mul_temp_46[56]}}, mul_temp_46[56:0]} + {mul_temp_46[2], {1{~mul_temp_46[2]}}})>>>2;

  assign mul_temp_47 = delay_pipeline[4] * coeff5;
  assign product5 = ({{19{mul_temp_47[56]}}, mul_temp_47[56:0]} + {mul_temp_47[2], {1{~mul_temp_47[2]}}})>>>2;

  assign mul_temp_48 = delay_pipeline[3] * coeff4;
  assign product4 = ({{19{mul_temp_48[56]}}, mul_temp_48[56:0]} + {mul_temp_48[2], {1{~mul_temp_48[2]}}})>>>2;

  assign mul_temp_49 = delay_pipeline[2] * coeff3;
  assign product3 = ({{19{mul_temp_49[56]}}, mul_temp_49[56:0]} + {mul_temp_49[2], {1{~mul_temp_49[2]}}})>>>2;

  assign mul_temp_50 = delay_pipeline[1] * coeff2;
  assign product2 = ({{19{mul_temp_50[56]}}, mul_temp_50[56:0]} + {mul_temp_50[2], {1{~mul_temp_50[2]}}})>>>2;

  assign product1_cast = $signed({{2{product1[73]}}, product1});

  assign mul_temp_51 = delay_pipeline[0] * coeff1;
  assign product1 = ({{19{mul_temp_51[56]}}, mul_temp_51[56:0]} + {mul_temp_51[2], {1{~mul_temp_51[2]}}})>>>2;

  assign add_signext = product1_cast;
  assign add_signext_1 = $signed({{2{product2[73]}}, product2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = ((add_temp[76] == 1'b0 & add_temp[75] != 1'b0) || (add_temp[76] == 1'b0 && add_temp[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp[76] == 1'b1 && add_temp[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp[75:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{2{product3[73]}}, product3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = ((add_temp_1[76] == 1'b0 & add_temp_1[75] != 1'b0) || (add_temp_1[76] == 1'b0 && add_temp_1[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_1[76] == 1'b1 && add_temp_1[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_1[75:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{2{product4[73]}}, product4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = ((add_temp_2[76] == 1'b0 & add_temp_2[75] != 1'b0) || (add_temp_2[76] == 1'b0 && add_temp_2[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_2[76] == 1'b1 && add_temp_2[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_2[75:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{2{product5[73]}}, product5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = ((add_temp_3[76] == 1'b0 & add_temp_3[75] != 1'b0) || (add_temp_3[76] == 1'b0 && add_temp_3[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_3[76] == 1'b1 && add_temp_3[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_3[75:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{2{product6[73]}}, product6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = ((add_temp_4[76] == 1'b0 & add_temp_4[75] != 1'b0) || (add_temp_4[76] == 1'b0 && add_temp_4[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_4[76] == 1'b1 && add_temp_4[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_4[75:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{2{product7[73]}}, product7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = ((add_temp_5[76] == 1'b0 & add_temp_5[75] != 1'b0) || (add_temp_5[76] == 1'b0 && add_temp_5[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_5[76] == 1'b1 && add_temp_5[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_5[75:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{2{product8[73]}}, product8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = ((add_temp_6[76] == 1'b0 & add_temp_6[75] != 1'b0) || (add_temp_6[76] == 1'b0 && add_temp_6[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_6[76] == 1'b1 && add_temp_6[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_6[75:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{2{product9[73]}}, product9});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = ((add_temp_7[76] == 1'b0 & add_temp_7[75] != 1'b0) || (add_temp_7[76] == 1'b0 && add_temp_7[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_7[76] == 1'b1 && add_temp_7[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_7[75:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{2{product10[73]}}, product10});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = ((add_temp_8[76] == 1'b0 & add_temp_8[75] != 1'b0) || (add_temp_8[76] == 1'b0 && add_temp_8[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_8[76] == 1'b1 && add_temp_8[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_8[75:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{2{product11[73]}}, product11});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = ((add_temp_9[76] == 1'b0 & add_temp_9[75] != 1'b0) || (add_temp_9[76] == 1'b0 && add_temp_9[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_9[76] == 1'b1 && add_temp_9[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_9[75:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{2{product12[73]}}, product12});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = ((add_temp_10[76] == 1'b0 & add_temp_10[75] != 1'b0) || (add_temp_10[76] == 1'b0 && add_temp_10[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_10[76] == 1'b1 && add_temp_10[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_10[75:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{2{product13[73]}}, product13});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = ((add_temp_11[76] == 1'b0 & add_temp_11[75] != 1'b0) || (add_temp_11[76] == 1'b0 && add_temp_11[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_11[76] == 1'b1 && add_temp_11[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_11[75:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{2{product14[73]}}, product14});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = ((add_temp_12[76] == 1'b0 & add_temp_12[75] != 1'b0) || (add_temp_12[76] == 1'b0 && add_temp_12[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_12[76] == 1'b1 && add_temp_12[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_12[75:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{2{product15[73]}}, product15});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = ((add_temp_13[76] == 1'b0 & add_temp_13[75] != 1'b0) || (add_temp_13[76] == 1'b0 && add_temp_13[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_13[76] == 1'b1 && add_temp_13[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_13[75:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{2{product16[73]}}, product16});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = ((add_temp_14[76] == 1'b0 & add_temp_14[75] != 1'b0) || (add_temp_14[76] == 1'b0 && add_temp_14[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_14[76] == 1'b1 && add_temp_14[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_14[75:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{2{product17[73]}}, product17});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = ((add_temp_15[76] == 1'b0 & add_temp_15[75] != 1'b0) || (add_temp_15[76] == 1'b0 && add_temp_15[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_15[76] == 1'b1 && add_temp_15[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_15[75:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{2{product18[73]}}, product18});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = ((add_temp_16[76] == 1'b0 & add_temp_16[75] != 1'b0) || (add_temp_16[76] == 1'b0 && add_temp_16[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_16[76] == 1'b1 && add_temp_16[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_16[75:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{2{product19[73]}}, product19});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = ((add_temp_17[76] == 1'b0 & add_temp_17[75] != 1'b0) || (add_temp_17[76] == 1'b0 && add_temp_17[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_17[76] == 1'b1 && add_temp_17[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_17[75:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{2{product20[73]}}, product20});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = ((add_temp_18[76] == 1'b0 & add_temp_18[75] != 1'b0) || (add_temp_18[76] == 1'b0 && add_temp_18[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_18[76] == 1'b1 && add_temp_18[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_18[75:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = $signed({{2{product21[73]}}, product21});
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = ((add_temp_19[76] == 1'b0 & add_temp_19[75] != 1'b0) || (add_temp_19[76] == 1'b0 && add_temp_19[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_19[76] == 1'b1 && add_temp_19[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_19[75:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = $signed({{2{product22[73]}}, product22});
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = ((add_temp_20[76] == 1'b0 & add_temp_20[75] != 1'b0) || (add_temp_20[76] == 1'b0 && add_temp_20[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_20[76] == 1'b1 && add_temp_20[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_20[75:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = $signed({{2{product23[73]}}, product23});
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = ((add_temp_21[76] == 1'b0 & add_temp_21[75] != 1'b0) || (add_temp_21[76] == 1'b0 && add_temp_21[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_21[76] == 1'b1 && add_temp_21[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_21[75:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = $signed({{2{product24[73]}}, product24});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = ((add_temp_22[76] == 1'b0 & add_temp_22[75] != 1'b0) || (add_temp_22[76] == 1'b0 && add_temp_22[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_22[76] == 1'b1 && add_temp_22[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_22[75:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = $signed({{2{product25[73]}}, product25});
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = ((add_temp_23[76] == 1'b0 & add_temp_23[75] != 1'b0) || (add_temp_23[76] == 1'b0 && add_temp_23[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_23[76] == 1'b1 && add_temp_23[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_23[75:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = $signed({{2{product26[73]}}, product26});
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = ((add_temp_24[76] == 1'b0 & add_temp_24[75] != 1'b0) || (add_temp_24[76] == 1'b0 && add_temp_24[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_24[76] == 1'b1 && add_temp_24[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_24[75:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = $signed({{2{product27[73]}}, product27});
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = ((add_temp_25[76] == 1'b0 & add_temp_25[75] != 1'b0) || (add_temp_25[76] == 1'b0 && add_temp_25[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_25[76] == 1'b1 && add_temp_25[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_25[75:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = $signed({{2{product28[73]}}, product28});
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = ((add_temp_26[76] == 1'b0 & add_temp_26[75] != 1'b0) || (add_temp_26[76] == 1'b0 && add_temp_26[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_26[76] == 1'b1 && add_temp_26[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_26[75:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = $signed({{2{product29[73]}}, product29});
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = ((add_temp_27[76] == 1'b0 & add_temp_27[75] != 1'b0) || (add_temp_27[76] == 1'b0 && add_temp_27[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_27[76] == 1'b1 && add_temp_27[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_27[75:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = $signed({{2{product30[73]}}, product30});
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = ((add_temp_28[76] == 1'b0 & add_temp_28[75] != 1'b0) || (add_temp_28[76] == 1'b0 && add_temp_28[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_28[76] == 1'b1 && add_temp_28[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_28[75:0];

  assign add_signext_58 = sum29;
  assign add_signext_59 = $signed({{2{product31[73]}}, product31});
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum30 = ((add_temp_29[76] == 1'b0 & add_temp_29[75] != 1'b0) || (add_temp_29[76] == 1'b0 && add_temp_29[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_29[76] == 1'b1 && add_temp_29[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_29[75:0];

  assign add_signext_60 = sum30;
  assign add_signext_61 = $signed({{2{product32[73]}}, product32});
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum31 = ((add_temp_30[76] == 1'b0 & add_temp_30[75] != 1'b0) || (add_temp_30[76] == 1'b0 && add_temp_30[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_30[76] == 1'b1 && add_temp_30[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_30[75:0];

  assign add_signext_62 = sum31;
  assign add_signext_63 = $signed({{2{product33[73]}}, product33});
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum32 = ((add_temp_31[76] == 1'b0 & add_temp_31[75] != 1'b0) || (add_temp_31[76] == 1'b0 && add_temp_31[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_31[76] == 1'b1 && add_temp_31[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_31[75:0];

  assign add_signext_64 = sum32;
  assign add_signext_65 = $signed({{2{product34[73]}}, product34});
  assign add_temp_32 = add_signext_64 + add_signext_65;
  assign sum33 = ((add_temp_32[76] == 1'b0 & add_temp_32[75] != 1'b0) || (add_temp_32[76] == 1'b0 && add_temp_32[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_32[76] == 1'b1 && add_temp_32[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_32[75:0];

  assign add_signext_66 = sum33;
  assign add_signext_67 = $signed({{2{product35[73]}}, product35});
  assign add_temp_33 = add_signext_66 + add_signext_67;
  assign sum34 = ((add_temp_33[76] == 1'b0 & add_temp_33[75] != 1'b0) || (add_temp_33[76] == 1'b0 && add_temp_33[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_33[76] == 1'b1 && add_temp_33[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_33[75:0];

  assign add_signext_68 = sum34;
  assign add_signext_69 = $signed({{2{product36[73]}}, product36});
  assign add_temp_34 = add_signext_68 + add_signext_69;
  assign sum35 = ((add_temp_34[76] == 1'b0 & add_temp_34[75] != 1'b0) || (add_temp_34[76] == 1'b0 && add_temp_34[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_34[76] == 1'b1 && add_temp_34[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_34[75:0];

  assign add_signext_70 = sum35;
  assign add_signext_71 = $signed({{2{product37[73]}}, product37});
  assign add_temp_35 = add_signext_70 + add_signext_71;
  assign sum36 = ((add_temp_35[76] == 1'b0 & add_temp_35[75] != 1'b0) || (add_temp_35[76] == 1'b0 && add_temp_35[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_35[76] == 1'b1 && add_temp_35[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_35[75:0];

  assign add_signext_72 = sum36;
  assign add_signext_73 = $signed({{2{product38[73]}}, product38});
  assign add_temp_36 = add_signext_72 + add_signext_73;
  assign sum37 = ((add_temp_36[76] == 1'b0 & add_temp_36[75] != 1'b0) || (add_temp_36[76] == 1'b0 && add_temp_36[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_36[76] == 1'b1 && add_temp_36[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_36[75:0];

  assign add_signext_74 = sum37;
  assign add_signext_75 = $signed({{2{product39[73]}}, product39});
  assign add_temp_37 = add_signext_74 + add_signext_75;
  assign sum38 = ((add_temp_37[76] == 1'b0 & add_temp_37[75] != 1'b0) || (add_temp_37[76] == 1'b0 && add_temp_37[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_37[76] == 1'b1 && add_temp_37[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_37[75:0];

  assign add_signext_76 = sum38;
  assign add_signext_77 = $signed({{2{product40[73]}}, product40});
  assign add_temp_38 = add_signext_76 + add_signext_77;
  assign sum39 = ((add_temp_38[76] == 1'b0 & add_temp_38[75] != 1'b0) || (add_temp_38[76] == 1'b0 && add_temp_38[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_38[76] == 1'b1 && add_temp_38[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_38[75:0];

  assign add_signext_78 = sum39;
  assign add_signext_79 = $signed({{2{product41[73]}}, product41});
  assign add_temp_39 = add_signext_78 + add_signext_79;
  assign sum40 = ((add_temp_39[76] == 1'b0 & add_temp_39[75] != 1'b0) || (add_temp_39[76] == 1'b0 && add_temp_39[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_39[76] == 1'b1 && add_temp_39[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_39[75:0];

  assign add_signext_80 = sum40;
  assign add_signext_81 = $signed({{2{product42[73]}}, product42});
  assign add_temp_40 = add_signext_80 + add_signext_81;
  assign sum41 = ((add_temp_40[76] == 1'b0 & add_temp_40[75] != 1'b0) || (add_temp_40[76] == 1'b0 && add_temp_40[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_40[76] == 1'b1 && add_temp_40[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_40[75:0];

  assign add_signext_82 = sum41;
  assign add_signext_83 = $signed({{2{product43[73]}}, product43});
  assign add_temp_41 = add_signext_82 + add_signext_83;
  assign sum42 = ((add_temp_41[76] == 1'b0 & add_temp_41[75] != 1'b0) || (add_temp_41[76] == 1'b0 && add_temp_41[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_41[76] == 1'b1 && add_temp_41[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_41[75:0];

  assign add_signext_84 = sum42;
  assign add_signext_85 = $signed({{2{product44[73]}}, product44});
  assign add_temp_42 = add_signext_84 + add_signext_85;
  assign sum43 = ((add_temp_42[76] == 1'b0 & add_temp_42[75] != 1'b0) || (add_temp_42[76] == 1'b0 && add_temp_42[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_42[76] == 1'b1 && add_temp_42[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_42[75:0];

  assign add_signext_86 = sum43;
  assign add_signext_87 = $signed({{2{product45[73]}}, product45});
  assign add_temp_43 = add_signext_86 + add_signext_87;
  assign sum44 = ((add_temp_43[76] == 1'b0 & add_temp_43[75] != 1'b0) || (add_temp_43[76] == 1'b0 && add_temp_43[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_43[76] == 1'b1 && add_temp_43[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_43[75:0];

  assign add_signext_88 = sum44;
  assign add_signext_89 = $signed({{2{product46[73]}}, product46});
  assign add_temp_44 = add_signext_88 + add_signext_89;
  assign sum45 = ((add_temp_44[76] == 1'b0 & add_temp_44[75] != 1'b0) || (add_temp_44[76] == 1'b0 && add_temp_44[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_44[76] == 1'b1 && add_temp_44[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_44[75:0];

  assign add_signext_90 = sum45;
  assign add_signext_91 = $signed({{2{product47[73]}}, product47});
  assign add_temp_45 = add_signext_90 + add_signext_91;
  assign sum46 = ((add_temp_45[76] == 1'b0 & add_temp_45[75] != 1'b0) || (add_temp_45[76] == 1'b0 && add_temp_45[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_45[76] == 1'b1 && add_temp_45[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_45[75:0];

  assign add_signext_92 = sum46;
  assign add_signext_93 = $signed({{2{product48[73]}}, product48});
  assign add_temp_46 = add_signext_92 + add_signext_93;
  assign sum47 = ((add_temp_46[76] == 1'b0 & add_temp_46[75] != 1'b0) || (add_temp_46[76] == 1'b0 && add_temp_46[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_46[76] == 1'b1 && add_temp_46[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_46[75:0];

  assign add_signext_94 = sum47;
  assign add_signext_95 = $signed({{2{product49[73]}}, product49});
  assign add_temp_47 = add_signext_94 + add_signext_95;
  assign sum48 = ((add_temp_47[76] == 1'b0 & add_temp_47[75] != 1'b0) || (add_temp_47[76] == 1'b0 && add_temp_47[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_47[76] == 1'b1 && add_temp_47[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_47[75:0];

  assign add_signext_96 = sum48;
  assign add_signext_97 = $signed({{2{product50[73]}}, product50});
  assign add_temp_48 = add_signext_96 + add_signext_97;
  assign sum49 = ((add_temp_48[76] == 1'b0 & add_temp_48[75] != 1'b0) || (add_temp_48[76] == 1'b0 && add_temp_48[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_48[76] == 1'b1 && add_temp_48[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_48[75:0];

  assign add_signext_98 = sum49;
  assign add_signext_99 = $signed({{2{product51[73]}}, product51});
  assign add_temp_49 = add_signext_98 + add_signext_99;
  assign sum50 = ((add_temp_49[76] == 1'b0 & add_temp_49[75] != 1'b0) || (add_temp_49[76] == 1'b0 && add_temp_49[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_49[76] == 1'b1 && add_temp_49[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_49[75:0];

  assign add_signext_100 = sum50;
  assign add_signext_101 = $signed({{2{product52[73]}}, product52});
  assign add_temp_50 = add_signext_100 + add_signext_101;
  assign sum51 = ((add_temp_50[76] == 1'b0 & add_temp_50[75] != 1'b0) || (add_temp_50[76] == 1'b0 && add_temp_50[75:0] == 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 76'b0111111111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp_50[76] == 1'b1 && add_temp_50[75] != 1'b1) ? 76'b1000000000000000000000000000000000000000000000000000000000000000000000000000 : add_temp_50[75:0];

  assign output_typeconvert = ((sum51[75] == 1'b0 & sum51[74:54] != 21'b000000000000000000000) || (sum51[75] == 1'b0 && sum51[54:22] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (sum51[75] == 1'b1 && sum51[74:54] != 21'b111111111111111111111) ? 33'b100000000000000000000000000000000 : (sum51[54:0] + {sum51[22], {21{~sum51[22]}}})>>>22;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
