// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-09-30 17:44:27
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: hdlsrc_8192
// EDAScriptGeneration: off
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp 
// GenerateHDLTestBench: off

// Filter Specifications:
//
// Sample Rate            : N/A (normalized frequency)
// Response               : Bandstop
// Specification          : Fp1,Fst1,Fst2,Fp2,Ap1,Ast,Ap2
// Stopband Atten.        : 20 dB
// First Passband Edge    : 0.011353
// First Stopband Edge    : 0.011963
// Second Stopband Edge   : 0.012451
// Second Passband Edge   : 0.013123
// First Passband Ripple  : 3 dB
// Second Passband Ripple : 3 dB
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 2
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s24,22 -> [-2 2)
// Denominator         : s24,22 -> [-2 2)
// Scale Values        : s24,23 -> [-1 1)
// Input               : s32,0 -> [-2147483648 2147483648)
// Section Input       : s33,0 -> [-4294967296 4294967296)
// Section Output      : s32,0 -> [-2147483648 2147483648)
// Output              : s32,0 -> [-2147483648 2147483648)
// State               : s28,0 -> [-134217728 134217728)
// Numerator Prod      : s52,22 -> [-536870912 536870912)
// Denominator Prod    : s52,22 -> [-536870912 536870912)
// Numerator Accum     : s54,22 -> [-2147483648 2147483648)
// Denominator Accum   : s54,22 -> [-2147483648 2147483648)
// Round Mode          : convergent
// Overflow Mode       : saturate
// -------------------------------------------------------------
// Multipliers           : 8



`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [31:0] filter_in; //sfix32
  output  signed [31:0] filter_out; //sfix32

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [23:0] scaleconst1 = 24'b011111111100011111000110; //sfix24_En23
  parameter signed [23:0] coeff_b1_section1 = 24'b010000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b2_section1 = 24'b100000000001100000010110; //sfix24_En22
  parameter signed [23:0] coeff_b3_section1 = 24'b010000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_a2_section1 = 24'b100000000101010011111101; //sfix24_En22
  parameter signed [23:0] coeff_a3_section1 = 24'b001111111100010101010000; //sfix24_En22
  parameter signed [23:0] scaleconst2 = 24'b011111111100011111000110; //sfix24_En23
  parameter signed [23:0] coeff_b1_section2 = 24'b010000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b2_section2 = 24'b100000000001100000010110; //sfix24_En22
  parameter signed [23:0] coeff_b3_section2 = 24'b010000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_a2_section2 = 24'b100000000100101110100111; //sfix24_En22
  parameter signed [23:0] coeff_a3_section2 = 24'b001111111100101001010101; //sfix24_En22
  // Signals
  reg  signed [31:0] input_register; // sfix32
  wire signed [55:0] scale1; // sfix56_En23
  wire signed [32:0] scaletypeconvert1; // sfix33
  // Section 1 Signals 
  wire signed [53:0] a1sum1; // sfix54_En22
  wire signed [53:0] a2sum1; // sfix54_En22
  wire signed [53:0] b1sum1; // sfix54_En22
  wire signed [53:0] b2sum1; // sfix54_En22
  wire signed [27:0] typeconvert1; // sfix28
  reg  signed [27:0] delay_section1 [0:1] ; // sfix28
  wire signed [53:0] inputconv1; // sfix54_En22
  wire signed [51:0] a2mul1; // sfix52_En22
  wire signed [51:0] a3mul1; // sfix52_En22
  wire signed [51:0] b1mul1; // sfix52_En22
  wire signed [51:0] b2mul1; // sfix52_En22
  wire signed [51:0] b3mul1; // sfix52_En22
  wire signed [53:0] sub_cast; // sfix54_En22
  wire signed [53:0] sub_cast_1; // sfix54_En22
  wire signed [54:0] sub_temp; // sfix55_En22
  wire signed [53:0] sub_cast_2; // sfix54_En22
  wire signed [53:0] sub_cast_3; // sfix54_En22
  wire signed [54:0] sub_temp_1; // sfix55_En22
  wire signed [53:0] b1multypeconvert1; // sfix54_En22
  wire signed [53:0] add_cast; // sfix54_En22
  wire signed [53:0] add_cast_1; // sfix54_En22
  wire signed [54:0] add_temp; // sfix55_En22
  wire signed [53:0] add_cast_2; // sfix54_En22
  wire signed [53:0] add_cast_3; // sfix54_En22
  wire signed [54:0] add_temp_1; // sfix55_En22
  wire signed [31:0] section_result1; // sfix32
  wire signed [55:0] scale2; // sfix56_En23
  wire signed [32:0] scaletypeconvert2; // sfix33
  // Section 2 Signals 
  wire signed [53:0] a1sum2; // sfix54_En22
  wire signed [53:0] a2sum2; // sfix54_En22
  wire signed [53:0] b1sum2; // sfix54_En22
  wire signed [53:0] b2sum2; // sfix54_En22
  wire signed [27:0] typeconvert2; // sfix28
  reg  signed [27:0] delay_section2 [0:1] ; // sfix28
  wire signed [53:0] inputconv2; // sfix54_En22
  wire signed [51:0] a2mul2; // sfix52_En22
  wire signed [51:0] a3mul2; // sfix52_En22
  wire signed [51:0] b1mul2; // sfix52_En22
  wire signed [51:0] b2mul2; // sfix52_En22
  wire signed [51:0] b3mul2; // sfix52_En22
  wire signed [53:0] sub_cast_4; // sfix54_En22
  wire signed [53:0] sub_cast_5; // sfix54_En22
  wire signed [54:0] sub_temp_2; // sfix55_En22
  wire signed [53:0] sub_cast_6; // sfix54_En22
  wire signed [53:0] sub_cast_7; // sfix54_En22
  wire signed [54:0] sub_temp_3; // sfix55_En22
  wire signed [53:0] b1multypeconvert2; // sfix54_En22
  wire signed [53:0] add_cast_4; // sfix54_En22
  wire signed [53:0] add_cast_5; // sfix54_En22
  wire signed [54:0] add_temp_2; // sfix55_En22
  wire signed [53:0] add_cast_6; // sfix54_En22
  wire signed [53:0] add_cast_7; // sfix54_En22
  wire signed [54:0] add_temp_3; // sfix55_En22
  wire signed [31:0] output_typeconvert; // sfix32
  reg  signed [31:0] output_register; // sfix32

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  assign scale1 = input_register * scaleconst1;

  assign scaletypeconvert1 = (scale1[55] == 1'b0 && scale1[54:22] == 33'b111111111111111111111111111111111) ? 33'b011111111111111111111111111111111 : (scale1[55:0] + {scale1[23], {22{~scale1[23]}}})>>>23;

  //   ------------------ Section 1 ------------------

  assign typeconvert1 = ((a1sum1[53] == 1'b0 & a1sum1[52:49] != 4'b0000) || (a1sum1[53] == 1'b0 && a1sum1[49:22] == 28'b0111111111111111111111111111) // special case0
) ? 28'b0111111111111111111111111111 : 
      (a1sum1[53] == 1'b1 && a1sum1[52:49] != 4'b1111) ? 28'b1000000000000000000000000000 : (a1sum1[49:0] + {a1sum1[22], {21{~a1sum1[22]}}})>>>22;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section1
      if (reset == 1'b1) begin
        delay_section1[0] <= 28'b0000000000000000000000000000;
        delay_section1[1] <= 28'b0000000000000000000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section1[1] <= delay_section1[0];
          delay_section1[0] <= typeconvert1;
        end
      end
    end // delay_process_section1

  assign inputconv1 = (scaletypeconvert1[32] == 1'b0 & scaletypeconvert1[31] != 1'b0) ? 54'b011111111111111111111111111111111111111111111111111111 : 
      (scaletypeconvert1[32] == 1'b1 && scaletypeconvert1[31] != 1'b1) ? 54'b100000000000000000000000000000000000000000000000000000 : $signed({scaletypeconvert1, 22'b0000000000000000000000});

  assign a2mul1 = delay_section1[0] * coeff_a2_section1;

  assign a3mul1 = delay_section1[1] * coeff_a3_section1;

  assign b1mul1 = $signed({typeconvert1, 22'b0000000000000000000000});

  assign b2mul1 = delay_section1[0] * coeff_b2_section1;

  assign b3mul1 = $signed({delay_section1[1], 22'b0000000000000000000000});

  assign sub_cast = inputconv1;
  assign sub_cast_1 = $signed({{2{a2mul1[51]}}, a2mul1});
  assign sub_temp = sub_cast - sub_cast_1;
  assign a2sum1 = ((sub_temp[54] == 1'b0 & sub_temp[53] != 1'b0) || (sub_temp[54] == 1'b0 && sub_temp[53:0] == 54'b011111111111111111111111111111111111111111111111111111) // special case0
) ? 54'b011111111111111111111111111111111111111111111111111111 : 
      (sub_temp[54] == 1'b1 && sub_temp[53] != 1'b1) ? 54'b100000000000000000000000000000000000000000000000000000 : sub_temp[53:0];

  assign sub_cast_2 = a2sum1;
  assign sub_cast_3 = $signed({{2{a3mul1[51]}}, a3mul1});
  assign sub_temp_1 = sub_cast_2 - sub_cast_3;
  assign a1sum1 = ((sub_temp_1[54] == 1'b0 & sub_temp_1[53] != 1'b0) || (sub_temp_1[54] == 1'b0 && sub_temp_1[53:0] == 54'b011111111111111111111111111111111111111111111111111111) // special case0
) ? 54'b011111111111111111111111111111111111111111111111111111 : 
      (sub_temp_1[54] == 1'b1 && sub_temp_1[53] != 1'b1) ? 54'b100000000000000000000000000000000000000000000000000000 : sub_temp_1[53:0];

  assign b1multypeconvert1 = $signed({{2{b1mul1[51]}}, b1mul1});

  assign add_cast = b1multypeconvert1;
  assign add_cast_1 = $signed({{2{b2mul1[51]}}, b2mul1});
  assign add_temp = add_cast + add_cast_1;
  assign b2sum1 = ((add_temp[54] == 1'b0 & add_temp[53] != 1'b0) || (add_temp[54] == 1'b0 && add_temp[53:0] == 54'b011111111111111111111111111111111111111111111111111111) // special case0
) ? 54'b011111111111111111111111111111111111111111111111111111 : 
      (add_temp[54] == 1'b1 && add_temp[53] != 1'b1) ? 54'b100000000000000000000000000000000000000000000000000000 : add_temp[53:0];

  assign add_cast_2 = b2sum1;
  assign add_cast_3 = $signed({{2{b3mul1[51]}}, b3mul1});
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign b1sum1 = ((add_temp_1[54] == 1'b0 & add_temp_1[53] != 1'b0) || (add_temp_1[54] == 1'b0 && add_temp_1[53:0] == 54'b011111111111111111111111111111111111111111111111111111) // special case0
) ? 54'b011111111111111111111111111111111111111111111111111111 : 
      (add_temp_1[54] == 1'b1 && add_temp_1[53] != 1'b1) ? 54'b100000000000000000000000000000000000000000000000000000 : add_temp_1[53:0];

  assign section_result1 = (b1sum1[53] == 1'b0 && b1sum1[52:21] == 32'b11111111111111111111111111111111) ? 32'b01111111111111111111111111111111 : (b1sum1[53:0] + {b1sum1[22], {21{~b1sum1[22]}}})>>>22;

  assign scale2 = section_result1 * scaleconst2;

  assign scaletypeconvert2 = (scale2[55] == 1'b0 && scale2[54:22] == 33'b111111111111111111111111111111111) ? 33'b011111111111111111111111111111111 : (scale2[55:0] + {scale2[23], {22{~scale2[23]}}})>>>23;

  //   ------------------ Section 2 ------------------

  assign typeconvert2 = ((a1sum2[53] == 1'b0 & a1sum2[52:49] != 4'b0000) || (a1sum2[53] == 1'b0 && a1sum2[49:22] == 28'b0111111111111111111111111111) // special case0
) ? 28'b0111111111111111111111111111 : 
      (a1sum2[53] == 1'b1 && a1sum2[52:49] != 4'b1111) ? 28'b1000000000000000000000000000 : (a1sum2[49:0] + {a1sum2[22], {21{~a1sum2[22]}}})>>>22;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section2
      if (reset == 1'b1) begin
        delay_section2[0] <= 28'b0000000000000000000000000000;
        delay_section2[1] <= 28'b0000000000000000000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section2[1] <= delay_section2[0];
          delay_section2[0] <= typeconvert2;
        end
      end
    end // delay_process_section2

  assign inputconv2 = (scaletypeconvert2[32] == 1'b0 & scaletypeconvert2[31] != 1'b0) ? 54'b011111111111111111111111111111111111111111111111111111 : 
      (scaletypeconvert2[32] == 1'b1 && scaletypeconvert2[31] != 1'b1) ? 54'b100000000000000000000000000000000000000000000000000000 : $signed({scaletypeconvert2, 22'b0000000000000000000000});

  assign a2mul2 = delay_section2[0] * coeff_a2_section2;

  assign a3mul2 = delay_section2[1] * coeff_a3_section2;

  assign b1mul2 = $signed({typeconvert2, 22'b0000000000000000000000});

  assign b2mul2 = delay_section2[0] * coeff_b2_section2;

  assign b3mul2 = $signed({delay_section2[1], 22'b0000000000000000000000});

  assign sub_cast_4 = inputconv2;
  assign sub_cast_5 = $signed({{2{a2mul2[51]}}, a2mul2});
  assign sub_temp_2 = sub_cast_4 - sub_cast_5;
  assign a2sum2 = ((sub_temp_2[54] == 1'b0 & sub_temp_2[53] != 1'b0) || (sub_temp_2[54] == 1'b0 && sub_temp_2[53:0] == 54'b011111111111111111111111111111111111111111111111111111) // special case0
) ? 54'b011111111111111111111111111111111111111111111111111111 : 
      (sub_temp_2[54] == 1'b1 && sub_temp_2[53] != 1'b1) ? 54'b100000000000000000000000000000000000000000000000000000 : sub_temp_2[53:0];

  assign sub_cast_6 = a2sum2;
  assign sub_cast_7 = $signed({{2{a3mul2[51]}}, a3mul2});
  assign sub_temp_3 = sub_cast_6 - sub_cast_7;
  assign a1sum2 = ((sub_temp_3[54] == 1'b0 & sub_temp_3[53] != 1'b0) || (sub_temp_3[54] == 1'b0 && sub_temp_3[53:0] == 54'b011111111111111111111111111111111111111111111111111111) // special case0
) ? 54'b011111111111111111111111111111111111111111111111111111 : 
      (sub_temp_3[54] == 1'b1 && sub_temp_3[53] != 1'b1) ? 54'b100000000000000000000000000000000000000000000000000000 : sub_temp_3[53:0];

  assign b1multypeconvert2 = $signed({{2{b1mul2[51]}}, b1mul2});

  assign add_cast_4 = b1multypeconvert2;
  assign add_cast_5 = $signed({{2{b2mul2[51]}}, b2mul2});
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign b2sum2 = ((add_temp_2[54] == 1'b0 & add_temp_2[53] != 1'b0) || (add_temp_2[54] == 1'b0 && add_temp_2[53:0] == 54'b011111111111111111111111111111111111111111111111111111) // special case0
) ? 54'b011111111111111111111111111111111111111111111111111111 : 
      (add_temp_2[54] == 1'b1 && add_temp_2[53] != 1'b1) ? 54'b100000000000000000000000000000000000000000000000000000 : add_temp_2[53:0];

  assign add_cast_6 = b2sum2;
  assign add_cast_7 = $signed({{2{b3mul2[51]}}, b3mul2});
  assign add_temp_3 = add_cast_6 + add_cast_7;
  assign b1sum2 = ((add_temp_3[54] == 1'b0 & add_temp_3[53] != 1'b0) || (add_temp_3[54] == 1'b0 && add_temp_3[53:0] == 54'b011111111111111111111111111111111111111111111111111111) // special case0
) ? 54'b011111111111111111111111111111111111111111111111111111 : 
      (add_temp_3[54] == 1'b1 && add_temp_3[53] != 1'b1) ? 54'b100000000000000000000000000000000000000000000000000000 : add_temp_3[53:0];

  assign output_typeconvert = (b1sum2[53] == 1'b0 && b1sum2[52:21] == 32'b11111111111111111111111111111111) ? 32'b01111111111111111111111111111111 : (b1sum2[53:0] + {b1sum2[22], {21{~b1sum2[22]}}})>>>22;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
