// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-09-19 13:43:09
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// EDAScriptGeneration: off
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off
// LoopUnrolling: on

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 20
// Stable            : Yes
// Linear Phase      : Yes (Type 2)
// Arithmetic        : fixed
// Numerator         : s16,18 -> [-1.250000e-01 1.250000e-01)
// Input             : s32,0 -> [-2147483648 2147483648)
// Filter Internals  : Specify Precision
//   Output          : s32,0 -> [-2147483648 2147483648)
//   Product         : s47,18 -> [-268435456 268435456)
//   Accumulator     : s51,18 -> [-4294967296 4294967296)
//   Round Mode      : convergent
//   Overflow Mode   : wrap
// -------------------------------------------------------------
// Multipliers           : 20



`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [31:0] filter_in; //sfix32
  output  signed [31:0] filter_out; //sfix32

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b1111000010000111; //sfix16_En18
  parameter signed [15:0] coeff2 = 16'b1111100000011010; //sfix16_En18
  parameter signed [15:0] coeff3 = 16'b0000010001001011; //sfix16_En18
  parameter signed [15:0] coeff4 = 16'b0001010010100100; //sfix16_En18
  parameter signed [15:0] coeff5 = 16'b0010100000001011; //sfix16_En18
  parameter signed [15:0] coeff6 = 16'b0011110011011100; //sfix16_En18
  parameter signed [15:0] coeff7 = 16'b0101000100010100; //sfix16_En18
  parameter signed [15:0] coeff8 = 16'b0110001010011001; //sfix16_En18
  parameter signed [15:0] coeff9 = 16'b0110111110000010; //sfix16_En18
  parameter signed [15:0] coeff10 = 16'b0111011001011011; //sfix16_En18
  parameter signed [15:0] coeff11 = 16'b0111011001011011; //sfix16_En18
  parameter signed [15:0] coeff12 = 16'b0110111110000010; //sfix16_En18
  parameter signed [15:0] coeff13 = 16'b0110001010011001; //sfix16_En18
  parameter signed [15:0] coeff14 = 16'b0101000100010100; //sfix16_En18
  parameter signed [15:0] coeff15 = 16'b0011110011011100; //sfix16_En18
  parameter signed [15:0] coeff16 = 16'b0010100000001011; //sfix16_En18
  parameter signed [15:0] coeff17 = 16'b0001010010100100; //sfix16_En18
  parameter signed [15:0] coeff18 = 16'b0000010001001011; //sfix16_En18
  parameter signed [15:0] coeff19 = 16'b1111100000011010; //sfix16_En18
  parameter signed [15:0] coeff20 = 16'b1111000010000111; //sfix16_En18

  // Signals
  reg  signed [31:0] delay_pipeline [0:19] ; // sfix32
  wire signed [46:0] product20; // sfix47_En18
  wire signed [47:0] mul_temp; // sfix48_En18
  wire signed [46:0] product19; // sfix47_En18
  wire signed [47:0] mul_temp_1; // sfix48_En18
  wire signed [46:0] product18; // sfix47_En18
  wire signed [47:0] mul_temp_2; // sfix48_En18
  wire signed [46:0] product17; // sfix47_En18
  wire signed [47:0] mul_temp_3; // sfix48_En18
  wire signed [46:0] product16; // sfix47_En18
  wire signed [47:0] mul_temp_4; // sfix48_En18
  wire signed [46:0] product15; // sfix47_En18
  wire signed [47:0] mul_temp_5; // sfix48_En18
  wire signed [46:0] product14; // sfix47_En18
  wire signed [47:0] mul_temp_6; // sfix48_En18
  wire signed [46:0] product13; // sfix47_En18
  wire signed [47:0] mul_temp_7; // sfix48_En18
  wire signed [46:0] product12; // sfix47_En18
  wire signed [47:0] mul_temp_8; // sfix48_En18
  wire signed [46:0] product11; // sfix47_En18
  wire signed [47:0] mul_temp_9; // sfix48_En18
  wire signed [46:0] product10; // sfix47_En18
  wire signed [47:0] mul_temp_10; // sfix48_En18
  wire signed [46:0] product9; // sfix47_En18
  wire signed [47:0] mul_temp_11; // sfix48_En18
  wire signed [46:0] product8; // sfix47_En18
  wire signed [47:0] mul_temp_12; // sfix48_En18
  wire signed [46:0] product7; // sfix47_En18
  wire signed [47:0] mul_temp_13; // sfix48_En18
  wire signed [46:0] product6; // sfix47_En18
  wire signed [47:0] mul_temp_14; // sfix48_En18
  wire signed [46:0] product5; // sfix47_En18
  wire signed [47:0] mul_temp_15; // sfix48_En18
  wire signed [46:0] product4; // sfix47_En18
  wire signed [47:0] mul_temp_16; // sfix48_En18
  wire signed [46:0] product3; // sfix47_En18
  wire signed [47:0] mul_temp_17; // sfix48_En18
  wire signed [46:0] product2; // sfix47_En18
  wire signed [47:0] mul_temp_18; // sfix48_En18
  wire signed [50:0] product1_cast; // sfix51_En18
  wire signed [46:0] product1; // sfix47_En18
  wire signed [47:0] mul_temp_19; // sfix48_En18
  wire signed [50:0] sum1; // sfix51_En18
  wire signed [50:0] add_signext; // sfix51_En18
  wire signed [50:0] add_signext_1; // sfix51_En18
  wire signed [51:0] add_temp; // sfix52_En18
  wire signed [50:0] sum2; // sfix51_En18
  wire signed [50:0] add_signext_2; // sfix51_En18
  wire signed [50:0] add_signext_3; // sfix51_En18
  wire signed [51:0] add_temp_1; // sfix52_En18
  wire signed [50:0] sum3; // sfix51_En18
  wire signed [50:0] add_signext_4; // sfix51_En18
  wire signed [50:0] add_signext_5; // sfix51_En18
  wire signed [51:0] add_temp_2; // sfix52_En18
  wire signed [50:0] sum4; // sfix51_En18
  wire signed [50:0] add_signext_6; // sfix51_En18
  wire signed [50:0] add_signext_7; // sfix51_En18
  wire signed [51:0] add_temp_3; // sfix52_En18
  wire signed [50:0] sum5; // sfix51_En18
  wire signed [50:0] add_signext_8; // sfix51_En18
  wire signed [50:0] add_signext_9; // sfix51_En18
  wire signed [51:0] add_temp_4; // sfix52_En18
  wire signed [50:0] sum6; // sfix51_En18
  wire signed [50:0] add_signext_10; // sfix51_En18
  wire signed [50:0] add_signext_11; // sfix51_En18
  wire signed [51:0] add_temp_5; // sfix52_En18
  wire signed [50:0] sum7; // sfix51_En18
  wire signed [50:0] add_signext_12; // sfix51_En18
  wire signed [50:0] add_signext_13; // sfix51_En18
  wire signed [51:0] add_temp_6; // sfix52_En18
  wire signed [50:0] sum8; // sfix51_En18
  wire signed [50:0] add_signext_14; // sfix51_En18
  wire signed [50:0] add_signext_15; // sfix51_En18
  wire signed [51:0] add_temp_7; // sfix52_En18
  wire signed [50:0] sum9; // sfix51_En18
  wire signed [50:0] add_signext_16; // sfix51_En18
  wire signed [50:0] add_signext_17; // sfix51_En18
  wire signed [51:0] add_temp_8; // sfix52_En18
  wire signed [50:0] sum10; // sfix51_En18
  wire signed [50:0] add_signext_18; // sfix51_En18
  wire signed [50:0] add_signext_19; // sfix51_En18
  wire signed [51:0] add_temp_9; // sfix52_En18
  wire signed [50:0] sum11; // sfix51_En18
  wire signed [50:0] add_signext_20; // sfix51_En18
  wire signed [50:0] add_signext_21; // sfix51_En18
  wire signed [51:0] add_temp_10; // sfix52_En18
  wire signed [50:0] sum12; // sfix51_En18
  wire signed [50:0] add_signext_22; // sfix51_En18
  wire signed [50:0] add_signext_23; // sfix51_En18
  wire signed [51:0] add_temp_11; // sfix52_En18
  wire signed [50:0] sum13; // sfix51_En18
  wire signed [50:0] add_signext_24; // sfix51_En18
  wire signed [50:0] add_signext_25; // sfix51_En18
  wire signed [51:0] add_temp_12; // sfix52_En18
  wire signed [50:0] sum14; // sfix51_En18
  wire signed [50:0] add_signext_26; // sfix51_En18
  wire signed [50:0] add_signext_27; // sfix51_En18
  wire signed [51:0] add_temp_13; // sfix52_En18
  wire signed [50:0] sum15; // sfix51_En18
  wire signed [50:0] add_signext_28; // sfix51_En18
  wire signed [50:0] add_signext_29; // sfix51_En18
  wire signed [51:0] add_temp_14; // sfix52_En18
  wire signed [50:0] sum16; // sfix51_En18
  wire signed [50:0] add_signext_30; // sfix51_En18
  wire signed [50:0] add_signext_31; // sfix51_En18
  wire signed [51:0] add_temp_15; // sfix52_En18
  wire signed [50:0] sum17; // sfix51_En18
  wire signed [50:0] add_signext_32; // sfix51_En18
  wire signed [50:0] add_signext_33; // sfix51_En18
  wire signed [51:0] add_temp_16; // sfix52_En18
  wire signed [50:0] sum18; // sfix51_En18
  wire signed [50:0] add_signext_34; // sfix51_En18
  wire signed [50:0] add_signext_35; // sfix51_En18
  wire signed [51:0] add_temp_17; // sfix52_En18
  wire signed [50:0] sum19; // sfix51_En18
  wire signed [50:0] add_signext_36; // sfix51_En18
  wire signed [50:0] add_signext_37; // sfix51_En18
  wire signed [51:0] add_temp_18; // sfix52_En18
  wire signed [31:0] output_typeconvert; // sfix32
  reg  signed [31:0] output_register; // sfix32

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
        end
      end
    end // Delay_Pipeline_process


  assign mul_temp = delay_pipeline[19] * coeff20;
  assign product20 = mul_temp[46:0];

  assign mul_temp_1 = delay_pipeline[18] * coeff19;
  assign product19 = mul_temp_1[46:0];

  assign mul_temp_2 = delay_pipeline[17] * coeff18;
  assign product18 = mul_temp_2[46:0];

  assign mul_temp_3 = delay_pipeline[16] * coeff17;
  assign product17 = mul_temp_3[46:0];

  assign mul_temp_4 = delay_pipeline[15] * coeff16;
  assign product16 = mul_temp_4[46:0];

  assign mul_temp_5 = delay_pipeline[14] * coeff15;
  assign product15 = mul_temp_5[46:0];

  assign mul_temp_6 = delay_pipeline[13] * coeff14;
  assign product14 = mul_temp_6[46:0];

  assign mul_temp_7 = delay_pipeline[12] * coeff13;
  assign product13 = mul_temp_7[46:0];

  assign mul_temp_8 = delay_pipeline[11] * coeff12;
  assign product12 = mul_temp_8[46:0];

  assign mul_temp_9 = delay_pipeline[10] * coeff11;
  assign product11 = mul_temp_9[46:0];

  assign mul_temp_10 = delay_pipeline[9] * coeff10;
  assign product10 = mul_temp_10[46:0];

  assign mul_temp_11 = delay_pipeline[8] * coeff9;
  assign product9 = mul_temp_11[46:0];

  assign mul_temp_12 = delay_pipeline[7] * coeff8;
  assign product8 = mul_temp_12[46:0];

  assign mul_temp_13 = delay_pipeline[6] * coeff7;
  assign product7 = mul_temp_13[46:0];

  assign mul_temp_14 = delay_pipeline[5] * coeff6;
  assign product6 = mul_temp_14[46:0];

  assign mul_temp_15 = delay_pipeline[4] * coeff5;
  assign product5 = mul_temp_15[46:0];

  assign mul_temp_16 = delay_pipeline[3] * coeff4;
  assign product4 = mul_temp_16[46:0];

  assign mul_temp_17 = delay_pipeline[2] * coeff3;
  assign product3 = mul_temp_17[46:0];

  assign mul_temp_18 = delay_pipeline[1] * coeff2;
  assign product2 = mul_temp_18[46:0];

  assign product1_cast = $signed({{4{product1[46]}}, product1});

  assign mul_temp_19 = delay_pipeline[0] * coeff1;
  assign product1 = mul_temp_19[46:0];

  assign add_signext = product1_cast;
  assign add_signext_1 = $signed({{4{product2[46]}}, product2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[50:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{4{product3[46]}}, product3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[50:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{4{product4[46]}}, product4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[50:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{4{product5[46]}}, product5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[50:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{4{product6[46]}}, product6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[50:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{4{product7[46]}}, product7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[50:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{4{product8[46]}}, product8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[50:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{4{product9[46]}}, product9});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[50:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{4{product10[46]}}, product10});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[50:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{4{product11[46]}}, product11});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[50:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{4{product12[46]}}, product12});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = add_temp_10[50:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{4{product13[46]}}, product13});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = add_temp_11[50:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{4{product14[46]}}, product14});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = add_temp_12[50:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{4{product15[46]}}, product15});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = add_temp_13[50:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{4{product16[46]}}, product16});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = add_temp_14[50:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{4{product17[46]}}, product17});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = add_temp_15[50:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{4{product18[46]}}, product18});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = add_temp_16[50:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{4{product19[46]}}, product19});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = add_temp_17[50:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{4{product20[46]}}, product20});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = add_temp_18[50:0];

  assign output_typeconvert = (sum19[49:0] + {sum19[18], {17{~sum19[18]}}})>>>18;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
