// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-10-07 15:08:38
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: hdlsrc_less_sat
// EDAScriptGeneration: off
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp 
// GenerateHDLTestBench: off

// Filter Specifications:
//
// Sample Rate   : N/A (normalized frequency)
// Response      : Highpass
// Specification : N,F3dB
// 3-dB Point    : 7.8125e-07
// Filter Order  : 1
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 1
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s24,22 -> [-2 2)
// Denominator         : s24,22 -> [-2 2)
// Scale Values        : s24,23 -> [-1 1)
// Input               : s32,31 -> [-1 1)
// Section Input       : s32,21 -> [-1024 1024)
// Section Output      : s32,22 -> [-512 512)
// Output              : s32,31 -> [-1 1)
// State               : s48,24 -> [-8388608 8388608)
// Numerator Prod      : s56,46 -> [-512 512)
// Denominator Prod    : s56,46 -> [-512 512)
// Numerator Accum     : s56,46 -> [-512 512)
// Denominator Accum   : s56,46 -> [-512 512)
// Round Mode          : convergent
// Overflow Mode       : saturate
// Cast Before Sum     : true
// -------------------------------------------------------------
// Multipliers           : 2



`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [31:0] filter_in; //sfix32_En31
  output  signed [31:0] filter_out; //sfix32_En31

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [23:0] scaleconst1 = 24'b011111111111111111110110; //sfix24_En23
  parameter signed [23:0] coeff_b1_section1 = 24'b010000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b2_section1 = 24'b110000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b3_section1 = 24'b000000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_a2_section1 = 24'b110000000000000000001010; //sfix24_En22
  parameter signed [23:0] coeff_a3_section1 = 24'b000000000000000000000000; //sfix24_En22
  // Signals
  reg  signed [31:0] input_register; // sfix32_En31
  wire signed [64:0] scale1; // sfix65_En54
  wire signed [55:0] mul_temp; // sfix56_En54
  wire signed [31:0] scaletypeconvert1; // sfix32_En21
  //   -- Section 1 Signals 
  wire signed [55:0] a1sum1; // sfix56_En46
  wire signed [55:0] b1sum1; // sfix56_En46
  wire signed [47:0] a1sumtypeconvert1; // sfix48_En24
  reg  signed [47:0] delay_section1; // sfix48_En24
  wire signed [55:0] inputconv1; // sfix56_En46
  wire signed [55:0] a2mul1; // sfix56_En46
  wire signed [55:0] b1mul1; // sfix56_En46
  wire signed [55:0] b2mul1; // sfix56_En46
  wire signed [71:0] mul_temp_1; // sfix72_En46
  wire signed [48:0] unaryminus_temp; // sfix49_En24
  wire signed [55:0] sub_cast; // sfix56_En46
  wire signed [55:0] sub_cast_1; // sfix56_En46
  wire signed [56:0] sub_temp; // sfix57_En46
  wire signed [55:0] add_cast; // sfix56_En46
  wire signed [55:0] add_cast_1; // sfix56_En46
  wire signed [56:0] add_temp; // sfix57_En46
  wire signed [31:0] output_typeconvert; // sfix32_En31
  reg  signed [31:0] output_register; // sfix32_En31

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  assign mul_temp = input_register * scaleconst1;
  assign scale1 = $signed({{9{mul_temp[55]}}, mul_temp});

  assign scaletypeconvert1 = (scale1[64] == 1'b0 && scale1[63:32] == 32'b11111111111111111111111111111111) ? 32'b01111111111111111111111111111111 : (scale1[64:0] + {scale1[33], {32{~scale1[33]}}})>>>33;

  //   ------------------ Section 1 (First Order) ------------------

  assign a1sumtypeconvert1 = ({{14{a1sum1[55]}}, a1sum1[55:0]} + {a1sum1[22], {21{~a1sum1[22]}}})>>>22;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section1
      if (reset == 1'b1) begin
        delay_section1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section1 <= a1sumtypeconvert1;
        end
      end
    end // delay_process_section1

  assign inputconv1 = (scaletypeconvert1[31] == 1'b0 & scaletypeconvert1[30] != 1'b0) ? 56'b01111111111111111111111111111111111111111111111111111111 : 
      (scaletypeconvert1[31] == 1'b1 && scaletypeconvert1[30] != 1'b1) ? 56'b10000000000000000000000000000000000000000000000000000000 : $signed({scaletypeconvert1, 25'b0000000000000000000000000});

  assign mul_temp_1 = delay_section1 * coeff_a2_section1;
  assign a2mul1 = ((mul_temp_1[71] == 1'b0 & mul_temp_1[70:55] != 16'b0000000000000000) || (mul_temp_1[71] == 1'b0 && mul_temp_1[55:0] == 56'b01111111111111111111111111111111111111111111111111111111) // special case0
) ? 56'b01111111111111111111111111111111111111111111111111111111 : 
      (mul_temp_1[71] == 1'b1 && mul_temp_1[70:55] != 16'b1111111111111111) ? 56'b10000000000000000000000000000000000000000000000000000000 : mul_temp_1[55:0];

  assign b1mul1 = (a1sumtypeconvert1[47] == 1'b0 & a1sumtypeconvert1[46:33] != 14'b00000000000000) ? 56'b01111111111111111111111111111111111111111111111111111111 : 
      (a1sumtypeconvert1[47] == 1'b1 && a1sumtypeconvert1[46:33] != 14'b11111111111111) ? 56'b10000000000000000000000000000000000000000000000000000000 : $signed({a1sumtypeconvert1, 22'b0000000000000000000000});

  assign unaryminus_temp = (delay_section1==48'b100000000000000000000000000000000000000000000000) ? $signed({1'b0, delay_section1}) : -delay_section1;
  assign b2mul1 = (unaryminus_temp[48] == 1'b0 & unaryminus_temp[47:33] != 15'b000000000000000) ? 56'b01111111111111111111111111111111111111111111111111111111 : 
      (unaryminus_temp[48] == 1'b1 && unaryminus_temp[47:33] != 15'b111111111111111) ? 56'b10000000000000000000000000000000000000000000000000000000 : $signed({unaryminus_temp, 22'b0000000000000000000000});

  assign sub_cast = inputconv1;
  assign sub_cast_1 = a2mul1;
  assign sub_temp = sub_cast - sub_cast_1;
  assign a1sum1 = ((sub_temp[56] == 1'b0 & sub_temp[55] != 1'b0) || (sub_temp[56] == 1'b0 && sub_temp[55:0] == 56'b01111111111111111111111111111111111111111111111111111111) // special case0
) ? 56'b01111111111111111111111111111111111111111111111111111111 : 
      (sub_temp[56] == 1'b1 && sub_temp[55] != 1'b1) ? 56'b10000000000000000000000000000000000000000000000000000000 : sub_temp[55:0];

  assign add_cast = b1mul1;
  assign add_cast_1 = b2mul1;
  assign add_temp = add_cast + add_cast_1;
  assign b1sum1 = ((add_temp[56] == 1'b0 & add_temp[55] != 1'b0) || (add_temp[56] == 1'b0 && add_temp[55:0] == 56'b01111111111111111111111111111111111111111111111111111111) // special case0
) ? 56'b01111111111111111111111111111111111111111111111111111111 : 
      (add_temp[56] == 1'b1 && add_temp[55] != 1'b1) ? 56'b10000000000000000000000000000000000000000000000000000000 : add_temp[55:0];

  assign output_typeconvert = ((b1sum1[55] == 1'b0 & b1sum1[54:46] != 9'b000000000) || (b1sum1[55] == 1'b0 && b1sum1[46:15] == 32'b01111111111111111111111111111111) // special case0
) ? 32'b01111111111111111111111111111111 : 
      (b1sum1[55] == 1'b1 && b1sum1[54:46] != 9'b111111111) ? 32'b10000000000000000000000000000000 : (b1sum1[46:0] + {b1sum1[15], {14{~b1sum1[15]}}})>>>15;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
