// -------------------------------------------------------------
//
// Module: filter_comp
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-08-05 17:17:35
// -------------------------------------------------------------
//========================================================================================  
// ----------------------------------------------------------------------------- 
//  Nanochap Electronics Copyright (C) 2014. ALL RIGHTS RESERVED. 
// ----------------------------------------------------------------------------- 
// Module name     : filter_wrapper
// Description     : the wrapper of LPF/HPF/MOTCH FILER
// ======================================================================================= 
// ----------------------------------------------------------------------------- 
// Revision History: 
// ----------------------------------------------------------------------------- 
// Revision       Date(xxxx-xx-xx)     Author             Description 
// ----------------------------------------------------------------------------- 
//   1.0          2025-9-15         Zhen Cao           Initial version 
// ----------------------------------------------------------------------------- 
//======================================================================================== 

module filter_wrapper#(
parameter DATA_WIDTH = 32
)(
input wire    clk,   
input wire    notch_clk,
input wire    lpf_clk,
input wire    hpf_clk,
input wire    pclk,     
//input wire    reset,
input wire    sign_en,
input wire    scan_mode,

///imeas
//clock and reset
//input wire           pclk,             // pclk
input wire           adc_clk,          // adc working clock, divider of 256khz
input wire [3:0]     DR,
input wire           presetn,          // reset
input wire           atpg_en,          // atpg enable

input  wire [7:0]    reg_ctrl,
input  wire          cic_rst_n,

output wire   [DATA_WIDTH-1:0]   chdata,
output wire                      chdata_en,
//output wire   [DATA_WIDTH-1:0]   chdata_adcclk,
//output wire                      chdata_en_adcclk,

//with analog
input  wire         imeas_adc_din,
//imeas

input  wire         cic_data_ok,

input wire [23:0]  hpf_coeff_data, 
input wire [17:0]  lpf_coeff_data [31:0],
input wire [19:0]  notch_coeff_data[41:0],

output wire    notch_clk_gtg_en,
output wire    lpf_clk_gtg_en,
output wire    hpf_clk_gtg_en,

input  wire  notch_filter_bypass_temp,
input  wire  lpf_filter_bypass_temp,
input  wire  hpf_filter_bypass_temp,
output wire  filter_chdata_en,
output wire [DATA_WIDTH-1:0] imeas_chdata_out





);


wire [DATA_WIDTH-1:0] filter1;
wire [DATA_WIDTH-1:0] filter2;
wire [DATA_WIDTH-1:0] filter3;
wire [DATA_WIDTH-1:0] filter4;
wire [DATA_WIDTH-1:0] filter5;
wire [DATA_WIDTH-1:0] filter6;
wire [DATA_WIDTH-1:0] imeas_chdata_out_temp;

wire  [DATA_WIDTH-1:0] imeas_chdata_adcclk;
wire                   chdata_en_adcclk;

reg lpf_filter_enable;
wire [4:0] lpf_filter_enable_cnt;

wire [5:0] notch_filter_enable_cnt;

wire lpf_filter_out_en;
wire lpf_filter_out_en_temp;
wire chdata_en_pulse;

reg notch_filter_enable;
reg notch_chdata_en_temp;
reg hpf_chdata_en_temp;
wire notch_chdata_en;
wire hpf_chdata_en;



////////////////////////////////////////////////////

   imeas #(
     .DATA_WIDTH(DATA_WIDTH)
   )
   u_imeas(
     .pclk(pclk),
     .adc_clk(adc_clk), //SDM_CLK,imeas_dig_adc_clk
     .DR(DR),
     .presetn(presetn),
     .reg_ctrl(reg_ctrl),//input  wire [15:0] 
     .cic_rst_n(cic_rst_n),// 
   
     .chdata_adcclk(imeas_chdata_adcclk),//output wire   [15:0]
     .chdata_en_adcclk(chdata_en_adcclk),//output wire   [15:0]
   	
     .chdata(chdata),//output wire   [15:0]
     .chdata_en(chdata_en),//output wire   [15:0]
     .atpg_en(atpg_en),
     .imeas_adc_din(imeas_adc_din)	//SDM_OUT, imeas_adc_din
   );

   //HPF
   filter_iir_hpf U_filter_iir_hpf (
    .clk          (hpf_clk),
    .clk_enable   (1'b1),
    .reset_n      (cic_rst_n),
    .sign_en      (sign_en),
    .bypass       (hpf_filter_bypass_temp),
    .coeff        (hpf_coeff_data),
    .filter_in    (filter1),
    .filter_out   (filter2)
   );

   //NOTCH
   notch_filter u_notch_filter(
   .clk(notch_clk),
   .clk_enable(1'b1),
   .reset(cic_rst_n),
   .sign_en(sign_en),
   .bypass(notch_filter_bypass_temp),
   .notch_coeff_data(notch_coeff_data),
   .filter_in(filter3),
   .o_cur_count(notch_filter_enable_cnt),
   .filter_out(filter4)
   );
   
   //LPF
   filter_fir_lpf u_filter_fir_lpf(
   .clk(lpf_clk),
   .clk_enable(1'b1),
   .reset(cic_rst_n),
   .sign_en(sign_en),
   .filter_out_en(lpf_filter_out_en_temp),
   .lpf_coeff_data(lpf_coeff_data),
   .bypass(lpf_filter_bypass_temp),
   .filter_in(filter5),
   .o_cur_count(lpf_filter_enable_cnt),
   .filter_out(filter6)
   );

assign imeas_chdata_out = imeas_chdata_out_temp & ({DATA_WIDTH{cic_data_ok}} | {DATA_WIDTH{notch_filter_bypass_temp & lpf_filter_bypass_temp}});


common_pulse_rising u_chdata_en_pulse(
.d_in(chdata_en_adcclk),
.clk(clk),
.rst_(cic_rst_n),
.d_out(chdata_en_pulse)
);


always @ (posedge clk or negedge cic_rst_n)begin
    if (cic_rst_n == 1'b0) begin
        lpf_filter_enable <= 1'b0;
    end
    else if (chdata_en_pulse & !lpf_filter_bypass_temp) begin        
        lpf_filter_enable <= 1'b1;   
    end
    else if (lpf_filter_enable) begin 
      if (lpf_filter_enable_cnt == 5'b11110) begin        
              lpf_filter_enable <= 1'b0;   
            end
            else begin
              lpf_filter_enable <= 1'b1;   
      end	    
    end   
    else begin
        lpf_filter_enable <= 1'b0;
    end 
end

//notch
assign lpf_filter_out_en = lpf_filter_bypass_temp? chdata_en_pulse : lpf_filter_out_en_temp;
always @ (posedge clk or negedge cic_rst_n)begin
    if (cic_rst_n == 1'b0) begin
        notch_filter_enable <= 1'b0;
        notch_chdata_en_temp        <= 1'b0;
    end
    else if (lpf_filter_out_en & !notch_filter_bypass_temp) begin        
        notch_filter_enable <= 1'b1;  
        notch_chdata_en_temp        <= 1'b0; 
    end
    else if (notch_filter_enable) begin 
      if (notch_filter_enable_cnt == 6'b10_1001) begin        
              notch_filter_enable <= 1'b0;  
              notch_chdata_en_temp        <= 1'b1; 
            end
            else begin
              notch_filter_enable <= 1'b1; 
              notch_chdata_en_temp        <= 1'b0;  
      end	    
    end   
    else begin
        notch_filter_enable <= 1'b0;
        notch_chdata_en_temp        <= 1'b0;
    end 
end

//hpf
always @ (posedge clk or negedge cic_rst_n)begin
    if (cic_rst_n == 1'b0) begin
        hpf_chdata_en_temp <= 1'b0;
    end else if (notch_chdata_en & !hpf_filter_bypass_temp) begin        
        hpf_chdata_en_temp <= 1'b1; 
    end else begin
        hpf_chdata_en_temp <= 1'b0;
    end 
end

assign lpf_clk_gtg_en      = !lpf_filter_bypass_temp & (chdata_en_pulse | lpf_filter_enable);

assign notch_clk_gtg_en    = !notch_filter_bypass_temp & notch_filter_enable;

assign notch_chdata_en     = notch_filter_bypass_temp? lpf_filter_out_en : notch_chdata_en_temp;

assign hpf_clk_gtg_en      = !hpf_filter_bypass_temp & (hpf_chdata_en);

assign hpf_chdata_en       = hpf_filter_bypass_temp? notch_chdata_en : hpf_chdata_en_temp;

common_pulse_sync u_chdata_en_sync(
.i_a_clk(clk),
.i_b_clk(pclk),  
.i_a_rst_n(cic_rst_n),
.i_b_rst_n(cic_rst_n),
.i_test_mode(scan_mode), 
.i_a_pulse(hpf_chdata_en),  
.o_a_ready(),   
.o_b_pulse(filter_chdata_en)    
); 

assign    filter5           = imeas_chdata_adcclk;
assign    filter3           = filter6;
assign    filter1           = filter4;
assign    imeas_chdata_out_temp  = filter2;



endmodule
