// -------------------------------------------------------------
//
// Module: filter_comp
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-08-05 17:17:35
// -------------------------------------------------------------
//========================================================================================  
// ----------------------------------------------------------------------------- 
//  Nanochap Electronics Copyright (C) 2014. ALL RIGHTS RESERVED. 
// ----------------------------------------------------------------------------- 
// Module name     : filter_wrapper
// Description     : the wrapper of LPF/HPF/MOTCH FILER
// ======================================================================================= 
// ----------------------------------------------------------------------------- 
// Revision History: 
// ----------------------------------------------------------------------------- 
// Revision       Date(xxxx-xx-xx)     Author             Description 
// ----------------------------------------------------------------------------- 
//   1.0          2025-9-15         Zhen Cao           Initial version 
// ----------------------------------------------------------------------------- 
//======================================================================================== 

module filter_wrapper#(
parameter DATA_WIDTH = 24
)(
input wire    clk,   
input wire    notch_clk,
input wire    lpf_clk,
input wire    hpf_clk,
input wire    pclk,     
//input wire    reset,
input wire    sign_en,
//input wire    scan_mode,

///imeas
//clock and reset
//input wire           pclk,             // pclk
input wire           adc_clk,          // adc working clock, divider of 256khz
input wire [3:0]     DR,
input wire           presetn,          // reset
input wire           atpg_en,          // atpg enable

input  wire [7:0]    reg_ctrl,
input  wire          cic_rst_n,

output wire   [DATA_WIDTH-1:0]   chdata,
output wire                      chdata_en,
//output wire   [DATA_WIDTH-1:0]   chdata_adcclk,
//output wire                      chdata_en_adcclk,

//with analog
input  wire         imeas_adc_din,
//imeas

input  wire         cic_data_ok,

input wire [23:0]  hpf_coeff_data, 
input wire signed [17:0]  lpf_coeff_data [27:0],
input wire signed [19:0]  notch_coeff_data[23:0],

output wire    notch_clk_gtg_en,
output wire    lpf_clk_gtg_en,
output wire    hpf_clk_gtg_en,

input  wire  notch_filter_bypass_temp,
input  wire  lpf_filter_bypass_temp,
input  wire  hpf_filter_bypass_temp,
output wire  filter_chdata_en,
output wire [DATA_WIDTH-1:0] imeas_chdata_out

);

wire [DATA_WIDTH-1:0] filter1;
wire [DATA_WIDTH-1:0] filter2;
wire [DATA_WIDTH-1:0] filter3;
wire [DATA_WIDTH-1:0] filter4;
wire [DATA_WIDTH-1:0] filter5;
wire [DATA_WIDTH-1:0] filter6;
wire [DATA_WIDTH-1:0] imeas_chdata_out_temp;

wire  [DATA_WIDTH-1:0] imeas_chdata_adcclk;
wire                   chdata_en_adcclk;

wire lpf_filter_enable;
wire hpf_filter_enable;

wire [4:0] lpf_filter_enable_cnt;
wire [4:0] notch_filter_enable_cnt;
wire [2:0] hpf_filter_enable_cnt;

wire lpf_filter_out_en;
wire lpf_filter_out_en_temp;
wire chdata_en_pulse;

wire notch_filter_enable;
wire notch_chdata_en_temp;
wire hpf_chdata_en_temp;
wire notch_chdata_en;
wire hpf_chdata_en;
wire lpf_cnt_flag;
wire nf_sw_flg;
//wire hpf_filter_out_en_temp;


wire signed [62:0] prod_nf;
wire signed [42:0] inputmux_section_nf;
wire signed [19:0] coeffmux_section_nf;

wire signed [42:0] prod_lpf;
wire signed [24:0] inputmux_section_lpf;
wire signed [17:0] coeffmux_section_lpf;

wire signed [69:0] prod_hpf;
wire signed [45:0] inputmux_section_hpf;
wire signed [23:0] coeffmux_section_hpf;

wire signed [69:0] prod;
wire signed [45:0] inputmux_section;
wire signed [23:0] coeffmux_section;



assign  inputmux_section = lpf_filter_enable?   {{21{inputmux_section_lpf[24]}},inputmux_section_lpf} : 
                           notch_filter_enable? {{3{inputmux_section_nf[42]}}  ,inputmux_section_nf } : inputmux_section_hpf;

assign  coeffmux_section = lpf_filter_enable? {{6{coeffmux_section_lpf[17]}},coeffmux_section_lpf}  : 
                           notch_filter_enable? {{4{coeffmux_section_nf[19]}}  ,coeffmux_section_nf } : coeffmux_section_hpf;

assign prod = inputmux_section * coeffmux_section;




assign prod_nf  = prod[62:0] & {63{notch_filter_enable}};
assign prod_lpf = prod[50:0] & {51{lpf_filter_enable}};
assign prod_hpf = prod[69:0] & {70{hpf_filter_enable}};


filter_ctrl u_filter_ctrl(
.clk_r(clk),
.rst_n(cic_rst_n),
.hpf_en(!hpf_filter_bypass_temp),
.lpf_en(!lpf_filter_bypass_temp),
.nf_en(!notch_filter_bypass_temp),
.imeas_done(chdata_en_pulse),
.hpf_done(hpf_chdata_en_temp),
.lpf_done(lpf_filter_out_en_temp),
.nf_done(notch_chdata_en_temp),
.hpf_cnt(hpf_filter_enable_cnt),
.lpf_cnt(lpf_filter_enable_cnt),
.nf_cnt(notch_filter_enable_cnt),
.lpf_cnt_flag(lpf_cnt_flag),
.nf_sw_flg(nf_sw_flg),
.hpf_fsm(hpf_filter_enable),
.lpf_fsm(lpf_filter_enable),
.nf_fsm(notch_filter_enable) 
);



////////////////////////////////////////////////////

   imeas #(
     .DATA_WIDTH(DATA_WIDTH)
   )
   u_imeas(
     .pclk(pclk),
     .adc_clk(adc_clk), //SDM_CLK,imeas_dig_adc_clk
     .DR(DR),
     .presetn(presetn),
     .reg_ctrl(reg_ctrl),//input  wire [15:0] 
     .cic_rst_n(cic_rst_n),// 
   
     .chdata_adcclk(imeas_chdata_adcclk),//output wire   [15:0]
     .chdata_en_adcclk(chdata_en_adcclk),//output wire   [15:0]
   	
     .chdata(chdata),//output wire   [15:0]
     .chdata_en(chdata_en),//output wire   [15:0]
     .atpg_en(atpg_en),
     .imeas_adc_din(imeas_adc_din)	//SDM_OUT, imeas_adc_din
   );

   //HPF
   filter_iir_hpf U_filter_iir_hpf (
    .clk          (hpf_clk),
    .clk_enable   (1'b1),
    .reset_n      (cic_rst_n),
    .sign_en      (sign_en),
    .bypass       (hpf_filter_bypass_temp),
    .coeff        (hpf_coeff_data),
    .filter_in    (filter1),
    .cur_count(hpf_filter_enable_cnt),
    .prod(prod_hpf),
    .inputmux_section_1(inputmux_section_hpf),
    .coeffmux_section_1(coeffmux_section_hpf),    
    .filter_out   (filter2)
   );

   //NOTCH
   notch_filter u_notch_filter(
   .clk(notch_clk),
   .clk_enable(1'b1),
   .reset(cic_rst_n),
   .sign_en(sign_en),
   .bypass(notch_filter_bypass_temp),
   .notch_coeff_data(notch_coeff_data),
   .filter_in(filter3),
   .prod(prod_nf),
   .inputmux_section_1(inputmux_section_nf),
   .coeffmux_section_1(coeffmux_section_nf),

   .cur_count(notch_filter_enable_cnt),
   .filter_out(filter4)
   );
   
   //LPF
   filter_fir_lpf u_filter_fir_lpf(
   .clk(lpf_clk),
   .clk_enable(1'b1),
   .reset(cic_rst_n),
   .sign_en(sign_en),
   .lpf_cnt_flag(lpf_cnt_flag),
   .lpf_coeff_data(lpf_coeff_data),
   .bypass(lpf_filter_bypass_temp),
   .filter_in(filter5),
   .mul_temp(prod_lpf),
   .inputmux_1(inputmux_section_lpf),
   .product_1_mux(coeffmux_section_lpf),
   .cur_count(lpf_filter_enable_cnt),
   .filter_out(filter6)
   );

assign imeas_chdata_out = imeas_chdata_out_temp & ({DATA_WIDTH{cic_data_ok}} | {DATA_WIDTH{notch_filter_bypass_temp & lpf_filter_bypass_temp}});


common_pulse_rising u_chdata_en_pulse(
.d_in(chdata_en_adcclk),
.clk(clk),
.rst_(cic_rst_n),
.d_out(chdata_en_pulse)
);


//hpf
//always @ (posedge clk or negedge cic_rst_n)begin
//    if (cic_rst_n == 1'b0) begin
//        hpf_filter_enable <= 1'b0;
//    end
//    else if (chdata_en_pulse & !hpf_filter_bypass_temp) begin        
//        hpf_filter_enable <= 1'b1;   
//    end
//    else if (hpf_filter_enable) begin 
//      if (hpf_filter_enable_cnt == 3'b101) begin        
//              hpf_filter_enable <= 1'b0;   
//            end
//            else begin
//              hpf_filter_enable <= 1'b1;   
//      end	    
//    end   
//    else begin
//        hpf_filter_enable <= 1'b0;
//    end 
//end


//lpf
//always @ (posedge clk or negedge cic_rst_n)begin
//    if (cic_rst_n == 1'b0) begin
//        lpf_filter_enable <= 1'b0;
//    end
//    else if (hpf_chdata_en & !lpf_filter_bypass_temp) begin        
//        lpf_filter_enable <= 1'b1;   
//    end
//    else if (lpf_filter_enable) begin 
//      if (lpf_filter_enable_cnt == 5'b11011) begin        
//              lpf_filter_enable <= 1'b0;   
//            end
//            else begin
//              lpf_filter_enable <= 1'b1;   
//      end	    
//    end   
//    else begin
//        lpf_filter_enable <= 1'b0;
//    end 
//end

//notch
assign lpf_filter_out_en = lpf_filter_bypass_temp? notch_chdata_en : lpf_filter_out_en_temp;
//always @ (posedge clk or negedge cic_rst_n)begin
//    if (cic_rst_n == 1'b0) begin
//        notch_filter_enable <= 1'b0;
//        notch_chdata_en_temp        <= 1'b0;
//    end
//    else if (lpf_filter_out_en & !notch_filter_bypass_temp) begin        
//        notch_filter_enable <= 1'b1;  
//        notch_chdata_en_temp        <= 1'b0; 
//    end
//    else if (notch_filter_enable) begin 
//      if (notch_filter_enable_cnt == 6'b10_0011) begin        
//             notch_filter_enable <= 1'b0;  
//              notch_chdata_en_temp        <= 1'b1; 
//            end
//            else begin
//              notch_filter_enable <= 1'b1; 
//              notch_chdata_en_temp        <= 1'b0;  
//      end	    
//    end   
//    else begin
//        notch_filter_enable <= 1'b0;
//        notch_chdata_en_temp        <= 1'b0;
//    end 
//end

//hpf
//always @ (posedge clk or negedge cic_rst_n)begin
//    if (cic_rst_n == 1'b0) begin
//        hpf_chdata_en_temp <= 1'b0;
//    end else if (hpf_filter_out_en_temp & !hpf_filter_bypass_temp) begin        
//        hpf_chdata_en_temp <= 1'b1; 
//    end else begin
//        hpf_chdata_en_temp <= 1'b0;
//    end 
//end

assign lpf_clk_gtg_en      = !lpf_filter_bypass_temp & lpf_filter_enable;

assign notch_clk_gtg_en    = !notch_filter_bypass_temp & nf_sw_flg;

assign notch_chdata_en     = notch_filter_bypass_temp? hpf_chdata_en : notch_chdata_en_temp;

assign hpf_clk_gtg_en      = !hpf_filter_bypass_temp & (hpf_filter_enable);

assign hpf_chdata_en       = hpf_filter_bypass_temp? chdata_en_pulse : hpf_chdata_en_temp;

common_pulse_sync u_chdata_en_sync(
.i_a_clk(clk),
.i_b_clk(pclk),  
.i_a_rst_n(cic_rst_n),
.i_b_rst_n(cic_rst_n),
.i_test_mode(atpg_en), 
.i_a_pulse(lpf_filter_out_en),  
.o_a_ready(),   
.o_b_pulse(filter_chdata_en)    
); 

assign    filter1                = imeas_chdata_adcclk;
assign    filter3                = filter2;
assign    imeas_chdata_out_temp  = filter6;
assign    filter5  = filter4;



endmodule
