// -------------------------------------------------------------
//
// Module: filter_comp
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-08-05 17:17:35
// -------------------------------------------------------------
//========================================================================================  
// ----------------------------------------------------------------------------- 
//  Nanochap Electronics Copyright (C) 2014. ALL RIGHTS RESERVED. 
// ----------------------------------------------------------------------------- 
// Module name     : filter_ctrl
// Description     : the controller of LPF/HPF/MOTCH FILER
// ======================================================================================= 
// ----------------------------------------------------------------------------- 
// Revision History: 
// ----------------------------------------------------------------------------- 
// Revision       Date(xxxx-xx-xx)     Author             Description 
// ----------------------------------------------------------------------------- 
//   1.0          2026-4-15         Zhen Cao           Initial version 
// ----------------------------------------------------------------------------- 
//======================================================================================== 


module filter_ctrl(

input wire clk_r,
input wire rst_n,

input wire hpf_en,
input wire lpf_en,
input wire nf_en,

input wire imeas_done,

output wire hpf_done,
output wire lpf_done,
output wire nf_done,

output wire [2:0] hpf_cnt,
output wire [4:0] lpf_cnt,
output wire [5:0] nf_cnt,

output reg        lpf_cnt_flag,


output reg nf_sw_flg,
output reg hpf_fsm,
output reg lpf_fsm,
output reg nf_fsm 

);


typedef enum logic [3:0]{
S_IDLE         = 4'h0,
S_HPF          = 4'h1,
S_LPF          = 4'h2,
S_NF           = 4'h3,
S_FILTER_DONE  = 4'h4


}filter_fsm_state;

filter_fsm_state cur_state;
filter_fsm_state next_state;

wire hpf_ready,lpf_ready,nf_ready,data_done;
wire timeout_flg;
//counter
localparam HPF_CNT_TAR = 6'h6;
localparam LPF_CNT_TAR = 6'h1d;
localparam NF_CNT_TAR  = 6'h24;
localparam TIME_OUT    = 6'h3f;

reg [5:0] fsm_cnt;


assign hpf_done    = (cur_state == S_HPF) & (fsm_cnt==HPF_CNT_TAR);
assign lpf_done    = (cur_state == S_LPF) & (fsm_cnt==LPF_CNT_TAR) & !lpf_cnt_flag;
assign nf_done     = (cur_state == S_NF)  & (fsm_cnt==NF_CNT_TAR);
assign timeout_flg = (cur_state != S_IDLE) & (fsm_cnt==TIME_OUT);

assign hpf_cnt  = hpf_fsm? (fsm_cnt<HPF_CNT_TAR)? fsm_cnt[2:0] : 3'b0  : 3'b0;
assign lpf_cnt  = lpf_fsm?  fsm_cnt[4:0] : 5'h1B;
//assign nf_cnt   = nf_fsm ? (fsm_cnt<NF_CNT_TAR )? fsm_cnt[5:0] : 6'b0  : 6'b0;
assign nf_cnt   = fsm_cnt[5:0] & {6{nf_fsm}};

always_ff@(posedge clk_r or negedge rst_n) begin
  if(~rst_n)begin
  fsm_cnt <= 6'h00; 
  lpf_cnt_flag <= 1'b0;
  nf_sw_flg <= 1'b0;
  end
  else if(lpf_ready) begin
  fsm_cnt <= 6'h1b; 
  lpf_cnt_flag <= 1'b1;
  end
  else begin
   if(cur_state == S_HPF) begin
      if(next_state!=S_HPF)begin
        fsm_cnt <= 6'h00; 
      end
      else  begin
        fsm_cnt <= fsm_cnt +1'b1;
      end
   end
   else if(cur_state == S_LPF) begin
      if(next_state!=S_LPF)begin
        fsm_cnt <= 6'h00; 
      end
      else if(lpf_cnt_flag) begin
        fsm_cnt <= 6'h00;
        lpf_cnt_flag <= 1'b0;
      end
      else  begin
        fsm_cnt <= fsm_cnt +1'b1;
      end
   end
   else if(cur_state == S_NF) begin
      if(next_state!=S_NF)begin
        fsm_cnt <= 6'h00; 
        nf_sw_flg <= 1'b0;
      end
      else if(nf_sw_flg)  begin
        fsm_cnt <= fsm_cnt +1'b1;  
        nf_sw_flg <= 1'b0;   
      end
      else begin
        nf_sw_flg <= 1'b1;   
      end      
   end
  end
end



//state-1
always_ff@(posedge clk_r or negedge rst_n) begin
  if(~rst_n)begin
  cur_state <= S_IDLE;
  end
  else if(timeout_flg) begin
  cur_state <= S_IDLE;
  end
  else begin
  cur_state <= next_state;
  end
end

//state-2
always_comb begin
 next_state = cur_state;
  case(cur_state)
  S_IDLE :begin
     if(imeas_done) begin
        if(hpf_en)begin
         next_state = S_HPF;
        end
        else if(lpf_en) begin
         next_state = S_LPF;
        end
        else if(nf_en) begin
         next_state = S_NF;
        end
        else begin
         next_state = S_IDLE;
        end        
     end
     else begin
      next_state = S_IDLE;
     end
  end

  S_HPF :begin
     if(hpf_done) begin
        if(lpf_en) begin
         next_state = S_LPF;
        end
        else if(nf_en) begin
         next_state = S_NF;
        end
        else begin
         next_state = S_HPF;
        end 
     end
     else begin
      next_state = S_HPF;
     end
  end

  S_LPF :begin
     if(lpf_done) begin
        if(nf_en) begin
         next_state = S_NF;
        end
        else begin
         next_state = S_LPF;
        end       
     end
     else begin
      next_state = S_LPF;
     end
  end
          
  S_NF :begin
     if(nf_done) begin
      next_state = S_FILTER_DONE;
     end
     else begin
      next_state = S_NF;
     end
  end

  S_FILTER_DONE :begin
      next_state = S_IDLE;
  end

  default : begin
      next_state = S_IDLE;
  end

  endcase
end


//state-3

assign hpf_ready = (cur_state==S_IDLE) & (next_state==S_HPF);
assign lpf_ready = (cur_state==S_IDLE) & (next_state==S_LPF) | ((cur_state==S_HPF)  & (next_state==S_LPF));
assign nf_ready  = (cur_state==S_IDLE) & (next_state==S_NF)  | ((cur_state==S_HPF)  & (next_state==S_NF)) | ((cur_state==S_LPF)  & (next_state==S_NF));
assign data_done = (cur_state==S_NF)   & (next_state==S_FILTER_DONE);


always_ff@(posedge clk_r or negedge rst_n) begin
   if(~rst_n)begin
   hpf_fsm <= 1'b0;
   end
   else begin
      if(hpf_ready)begin
       hpf_fsm <= 1'b1;
      end
      else if((cur_state == S_HPF) & (fsm_cnt==HPF_CNT_TAR-1))begin
       hpf_fsm <= 1'b0;
      end
      else if(data_done)begin
       hpf_fsm <= 1'b0;
      end    
   end
end

always_ff@(posedge clk_r or negedge rst_n) begin
   if(~rst_n)begin
   lpf_fsm <= 1'b0;
   end
   else begin
      if(lpf_ready)begin
       lpf_fsm <= 1'b1;
      end
      else if((cur_state == S_LPF) & (fsm_cnt==LPF_CNT_TAR-1) & !lpf_cnt_flag)begin
       lpf_fsm <= 1'b0;
      end
      else if(data_done)begin
       lpf_fsm <= 1'b0;
      end    
   end
end

always_ff@(posedge clk_r or negedge rst_n) begin
   if(~rst_n)begin
   nf_fsm <= 1'b0;
   end
   else begin
      if(nf_ready)begin
       nf_fsm <= 1'b1;
      end
      else if((cur_state == S_NF) & (fsm_cnt==NF_CNT_TAR-1) & nf_sw_flg)begin
       nf_fsm <= 1'b0;
      end
      else if(data_done)begin
       nf_fsm <= 1'b0;
      end    
   end
end


endmodule
