// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2026-01-05 10:49:36
// -------------------------------------------------------------
//========================================================================================  
// ----------------------------------------------------------------------------- 
//  Nanochap Electronics Copyright (C) 2014. ALL RIGHTS RESERVED. 
// ----------------------------------------------------------------------------- 
// Module name     : 
// Description     : 
// ======================================================================================= 
// -------------------------------------------------------------
// HDL Code Generation Options:
//
// OptimizeForHDL: on
// ResetInputPort: reset_n
// TargetDirectory: hdlsrc_1_5
// EDAScriptGeneration: off
// AddInputRegister: off
// AddPipelineRegisters: on
// ResetAssertedLevel: Active-low
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp 
// GenerateHDLTestBench: off
// LoopUnrolling: on

// Filter Specifications:
//
// Sample Rate   : N/A (normalized frequency)
// Response      : Highpass
// Specification : N,F3dB
// Filter Order  : 1
// 3-dB Point    : 7.8125e-06
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 1
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s24,22 -> [-2 2)
// Denominator         : s24,22 -> [-2 2)
// Scale Values        : s24,23 -> [-1 1)
// Input               : s33,32 -> [-1 1)
// Section Input       : s33,32 -> [-1 1)
// Section Output      : s33,32 -> [-1 1)
// Output              : s33,32 -> [-1 1)
// State               : s50,17 -> [-4294967296 4294967296)
// Numerator Prod      : s74,39 -> [-17179869184 17179869184)
// Denominator Prod    : s74,39 -> [-17179869184 17179869184)
// Numerator Accum     : s76,39 -> [-68719476736 68719476736)
// Denominator Accum   : s76,39 -> [-68719476736 68719476736)
// Round Mode          : convergent
// Overflow Mode       : saturate
// -------------------------------------------------------------
// Multipliers           : 2

module filter_iir_hpf
               (
                clk,
                clk_enable,
                reset_n,
                sign_en,
                bypass,
                coeff,
		cur_count,
		prod,
                inputmux_section_1,
                coeffmux_section_1,		
                filter_in,
                filter_out
                );

  input                 clk;
  input                 clk_enable;
  input                 reset_n;
  input                 sign_en;
  input                 bypass;
  input          [23:0] coeff;
  input   signed [23:0] filter_in; //sfix33
  output  signed [23:0] filter_out; //sfix33
  input  wire   [2:0]  cur_count;
  input wire  signed [69:0]   prod;
  output wire signed [45:0] inputmux_section_1;
  output wire signed [23:0] coeffmux_section_1;
  

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants



  wire      signed [23:0] scaleconst1 = coeff; // sfix24_En23
  parameter signed [23:0] coeff_b1_section1 = 24'b010000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b2_section1 = 24'b110000000000000000000000; //sfix24_En22
  parameter signed [23:0] coeff_b3_section1 = 24'b000000000000000000000000; //sfix24_En22
  wire      signed [23:0] coeff_a2_section1 = coeff_b1_section1 - (coeff<<1); // sfix24_En22
  parameter signed [23:0] coeff_a3_section1 = 24'b000000000000000000000000; //sfix24_En22




  // Signals
  reg  signed [24:0] input_register; // sfix25_En24
//  reg  [2:0] cur_count; // ufix3
  wire phase_0; // boolean
  wire phase_2; // boolean
  wire phase_3; // boolean
  wire phase_5; // boolean
  wire signed [24:0] sectionipconvert; // sfix25_En24
  wire signed [45:0] storagetypeconvert; // sfix46_En24
  reg  signed [45:0] storage_state_in1; // sfix46_En24
  reg  signed [45:0] delay_section1 [0:1] ; // sfix46_En24
  wire signed [45:0] input_section1_cast; // sfix46_En24
  wire signed [45:0] storage_in_section1_cast; // sfix46_En24
  wire signed [45:0] delay_section11_cast; // sfix46_En24
  wire signed [45:0] delay_section12_cast; // sfix46_En24
//  wire signed [45:0] inputmux_section_1; // sfix46_En24
//  wire signed [23:0] coeffmux_section_1; // sfix24_En22
//  wire signed [69:0] prod; // sfix70_En46
  wire signed [69:0] prod_den; // sfix70_En46
  wire signed [71:0] prod_den_cast_temp; // sfix72_En46
  wire signed [71:0] prod_den_cast; // sfix72_En46
  wire signed [71:0] prod_den_cast_neg; // sfix72_En46
  wire signed [72:0] unaryminus_temp; // sfix73_En46
  wire signed [69:0] prod_num; // sfix70_En46
  wire signed [71:0] prod_num_cast_temp; // sfix72_En46
  wire signed [71:0] prod_num_cast; // sfix72_En46
  wire signed [71:0] accum_mux_in1; // sfix72_En46
  wire signed [71:0] accum_mux_in2; // sfix72_En46
  wire signed [71:0] accum_mux_out; // sfix72_En46
  wire signed [71:0] accum_mux_in1_temp; // sfix72_En46
  wire signed [71:0] sectionipconvert_cast; // sfix72_En46
  wire final_phase; // boolean
  wire section_phase; // boolean
  reg  signed [71:0] accum_reg; // sfix72_En46
  wire signed [71:0] add_cast; // sfix72_En46
  wire signed [71:0] add_cast_1; // sfix72_En46
  wire signed [72:0] add_temp; // sfix73_En46
  wire signed [71:0] acc_out_cast_numacc; // sfix72_En46
  wire signed [24:0] output_typeconvert; // sfix25_En24
  reg  signed [24:0] output_register; // sfix25_En24

  // Block Statements
  always @ (posedge clk or negedge reset_n)
    begin: input_reg_process
      if (reset_n == 1'b0) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <=  ~sign_en?  $signed({1'b0,filter_in})-25'sh0_80_0000 : {{2{filter_in[23]}},filter_in[22:0]};
        end
      end
    end // input_reg_process

//  always @ (posedge clk or negedge reset_n)
//    begin: Counter_process
//      if (reset_n == 1'b0) begin
//        cur_count <= 3'b000;
//      end
//      else begin
//        if (clk_enable == 1'b1) begin
//          if (cur_count >= 3'b101) begin
//            cur_count <= 3'b000;
//          end
//          else begin
//            cur_count <= cur_count + 3'b001;
//          end
//        end
//      end
//    end // Counter_process

  assign  phase_0 = (cur_count == 3'b000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_2 = (cur_count == 3'b010 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_3 = (cur_count == 3'b011 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_5 = (cur_count == 3'b101 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @ (posedge clk or negedge reset_n)
    begin: delay_process_section1
      if (reset_n == 1'b0) begin
        delay_section1[0] <= 46'h000000000000;
        delay_section1[1] <= 46'h000000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section1[1] <= delay_section1[0];
          delay_section1[0] <= storage_state_in1;
        end
      end
    end // delay_process_section1

  // Making common precision for input and state 
  assign input_section1_cast = $signed({{21{input_register[24]}}, input_register});

  assign delay_section11_cast = delay_section1[0];

  assign delay_section12_cast = delay_section1[1];

  assign storage_in_section1_cast = storage_state_in1;

  assign inputmux_section_1 = (cur_count == 3'b000) ? input_section1_cast :
                             (cur_count == 3'b001) ? delay_section11_cast :
                             (cur_count == 3'b010) ? delay_section12_cast :
                             (cur_count == 3'b011) ? storage_in_section1_cast :
                             (cur_count == 3'b100) ? delay_section11_cast :
                             delay_section12_cast;

  assign coeffmux_section_1 = (cur_count == 3'b000) ? scaleconst1 :
                             (cur_count == 3'b001) ? coeff_a2_section1 :
                             (cur_count == 3'b010) ? coeff_a3_section1 :
                             (cur_count == 3'b011) ? coeff_b1_section1 :
                             (cur_count == 3'b100) ? coeff_b2_section1 :
                             coeff_b3_section1;

//  assign prod = inputmux_section_1 * coeffmux_section_1;

  assign prod_den = prod;

  assign prod_den_cast_temp = $signed({{2{prod_den[69]}}, prod_den});

  assign prod_den_cast = prod_den_cast_temp;

  assign unaryminus_temp = (prod_den_cast==72'b100000000000000000000000000000000000000000000000000000000000000000000000) ? $signed({1'b0, prod_den_cast}) : -prod_den_cast;
  assign prod_den_cast_neg = unaryminus_temp[71:0];

  assign prod_num = prod;

  assign prod_num_cast_temp = $signed({{2{prod_num[69]}}, prod_num});

  assign prod_num_cast = prod_num_cast_temp;

  assign accum_mux_in1 = (cur_count == 3'b000) ? prod_num_cast :
                        (cur_count == 3'b001) ? prod_den_cast_neg :
                        (cur_count == 3'b010) ? prod_den_cast_neg :
                        (cur_count == 3'b011) ? prod_num_cast :
                        (cur_count == 3'b100) ? prod_num_cast :
                        prod_num_cast;

  assign final_phase =  phase_0 | phase_3;

  assign section_phase =  phase_0;

  assign accum_mux_in1_temp = (section_phase == 1'b1) ? sectionipconvert_cast :
                             accum_mux_in1;

  assign accum_mux_out = (final_phase == 1'b1) ? accum_mux_in1_temp :
                        accum_mux_in2;

  always @ (posedge clk or negedge reset_n)
    begin: accumulator_reg_process
      if (reset_n == 1'b0) begin
        accum_reg <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          accum_reg <= accum_mux_out;
        end
      end
    end // accumulator_reg_process

  assign add_cast = accum_reg;
  assign add_cast_1 = accum_mux_in1;
  assign add_temp = add_cast + add_cast_1;
  assign accum_mux_in2 = add_temp[71:0];

  assign storagetypeconvert = (accum_mux_out[67:0] + {accum_mux_out[22], {21{~accum_mux_out[22]}}})>>>22;

  assign sectionipconvert = (prod[46:0] + {prod[22], {21{~prod[22]}}})>>>22;

  assign sectionipconvert_cast = $signed({sectionipconvert[24:0], 22'b0000000000000000000000});

  assign acc_out_cast_numacc = accum_mux_out;

  assign output_typeconvert = (acc_out_cast_numacc[46:0] + {acc_out_cast_numacc[22], {21{~acc_out_cast_numacc[22]}}})>>>22;

  always @ (posedge clk or negedge reset_n)
    begin: storage_reg1_process
      if (reset_n == 1'b0) begin
        storage_state_in1 <= 0;
      end
      else begin
        if (phase_2 == 1'b1) begin
          storage_state_in1 <= storagetypeconvert;
        end
      end
    end // storage_reg1_process

  always @ (posedge clk or negedge reset_n)
    begin: Output_Register_process
      if (reset_n == 1'b0) begin
        output_register <= 0;
      end
      else begin
        if (phase_5 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
 
   wire [23:0] output_register_temp; 
 assign output_register_temp = (output_register[24:23]==2'b10)? 24'h80_0000 : (output_register[24:23]==2'b01)? 24'h7f_ffff : output_register[23:0];
 assign filter_out = bypass? filter_in : ~sign_en? output_register_temp[23:0] + 24'h80_0000 : output_register_temp[23:0];


endmodule  // filter
