// -------------------------------------------------------------
//
// Module: filter_comp
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-08-05 17:17:35
// -------------------------------------------------------------
//========================================================================================  
// ----------------------------------------------------------------------------- 
//  Nanochap Electronics Copyright (C) 2014. ALL RIGHTS RESERVED. 
// ----------------------------------------------------------------------------- 
// Module name     : notch_filter
// Description     : this is notch filter for 50hz; the order is 4, section is 2
// ======================================================================================= 
// =osr_sel :(4'h0~4'h1 and 4'hc~4'hf) is not supported
// =value 4'h0 - 4'h1 - 4'h2 - 4'h3 - 4'h4 - 4'h5 - 4'h6 - 4'h7 - 4'h8 - 4'h9 - 4'ha - 4'hb  
// =OSR    x   -  x   -  32  - 64   - 128  - 256  - 512  - 1024 - 2048 - 4096 - 8192 - 16384 
// =Fs                   64k    32k    16k    8k     4K     2k     1K    512    256   128   //hz
// =Fpass1               46.5   46.5   46.5   46.5   46.5   46.5   46.5  46.5   46.5   46.5  //hz
// =Fstop1               48.9   48.9   48.9   48.9   48.9   48.9   48.9  48.9   49     49    //hz
// =Fpass2               51.1   51.1   51.1   51.1   51.1   51.1   51.1  51.1   51     51    //hz
// =Fstop2               53.75  53.75  53.75  53.75  53.75  53.75  53.75 53.75  53.75  53.7  //hz
// =Apass1                       3     3      3     3      3      3      3       3   //dB
// =Astop                        20    20     20    20     20     20     20      20  //dB
// =Apass2                       3     3      3     3      3      3      3       3   //dB
// ======================================================================================= 
// =sign_en:
// =value        1'b0     -   1'b1 
// =signed?    unsigned   -  signed   
// ======================================================================================= 
// ----------------------------------------------------------------------------- 
// Revision History: 
// ----------------------------------------------------------------------------- 
// Revision       Date(xxxx-xx-xx)     Author             Description 
// ----------------------------------------------------------------------------- 
//   1.0          2025-9-15         Zhen Cao           Initial version 
// ----------------------------------------------------------------------------- 
//======================================================================================== 

module notch_filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
		sign_en,
//		osr_sel,
		bypass,
		cur_count,
                inputmux_section_1,
                coeffmux_section_1,
                prod,
		notch_coeff_data,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   sign_en;  
  input   bypass; 
//  input          [3:0]  osr_sel;
  input   signed [23:0] filter_in; //sfix33
  output  signed [23:0] filter_out; //sfix33
  input   wire  [4:0]  cur_count;
  input wire  signed [19:0] notch_coeff_data[23:0];
  input wire  signed [62:0] prod;
  output wire signed [42:0] inputmux_section_1;
  output wire signed [19:0] coeffmux_section_1;   



////////////////////////////////////////////////////////////////
//Module Architecture: filter_notch
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants

  wire signed [19:0] scaleconst1      ; 
wire signed [19:0] coeff_b1_section1; 
wire signed [19:0] coeff_b2_section1; 
wire signed [19:0] coeff_b3_section1; 
wire signed [19:0] coeff_a2_section1; 
wire signed [19:0] coeff_a3_section1; 
wire signed [19:0] scaleconst2      ; 
wire signed [19:0] coeff_b1_section2; 
wire signed [19:0] coeff_b2_section2; 
wire signed [19:0] coeff_b3_section2; 
wire signed [19:0] coeff_a2_section2; 
wire signed [19:0] coeff_a3_section2; 
wire signed [19:0] scaleconst3      ; 
wire signed [19:0] coeff_b1_section3; 
wire signed [19:0] coeff_b2_section3; 
wire signed [19:0] coeff_b3_section3; 
wire signed [19:0] coeff_a2_section3; 
wire signed [19:0] coeff_a3_section3; 
wire signed [19:0] scaleconst4      ; 
wire signed [19:0] coeff_b1_section4; 
wire signed [19:0] coeff_b2_section4; 
wire signed [19:0] coeff_b3_section4; 
wire signed [19:0] coeff_a2_section4; 
wire signed [19:0] coeff_a3_section4; 


assign scaleconst1       = notch_coeff_data[0]; //sfix20_En18
assign coeff_b1_section1 = notch_coeff_data[1]; //sfix20_En18
assign coeff_b2_section1 = notch_coeff_data[2]; //sfix20_En18
assign coeff_b3_section1 = notch_coeff_data[3]; //sfix20_En18
assign coeff_a2_section1 = notch_coeff_data[4]; //sfix20_En18
assign coeff_a3_section1 = notch_coeff_data[5]; //sfix20_En18
assign scaleconst2       = notch_coeff_data[6]; //sfix20_En18
assign coeff_b1_section2 = notch_coeff_data[7]; //sfix20_En18
assign coeff_b2_section2 = notch_coeff_data[8]; //sfix20_En18
assign coeff_b3_section2 = notch_coeff_data[9]; //sfix20_En18
assign coeff_a2_section2 = notch_coeff_data[10]; //sfix20_En18
assign coeff_a3_section2 = notch_coeff_data[11]; //sfix20_En18
assign scaleconst3       = notch_coeff_data[12]; //sfix20_En18
assign coeff_b1_section3 = notch_coeff_data[13]; //sfix20_En18
assign coeff_b2_section3 = notch_coeff_data[14]; //sfix20_En18
assign coeff_b3_section3 = notch_coeff_data[15]; //sfix20_En18
assign coeff_a2_section3 = notch_coeff_data[16]; //sfix20_En18
assign coeff_a3_section3 = notch_coeff_data[17]; //sfix20_En18
assign scaleconst4       = notch_coeff_data[18]; //sfix20_En18
assign coeff_b1_section4 = notch_coeff_data[19]; //sfix20_En18
assign coeff_b2_section4 = notch_coeff_data[20]; //sfix20_En18
assign coeff_b3_section4 = notch_coeff_data[21]; //sfix20_En18
assign coeff_a2_section4 = notch_coeff_data[22]; //sfix20_En18
assign coeff_a3_section4 = notch_coeff_data[23]; //sfix20_En18

  // Signals
  wire  signed [24:0] input_register; // sfix25_En24
  wire phase_0; // boolean
  wire phase_2; // boolean
  wire phase_3; // boolean
  wire phase_5; // boolean
  wire phase_6; // boolean
  wire phase_8; // boolean
  wire phase_9; // boolean
  wire phase_11; // boolean
  wire phase_12; // boolean
  wire phase_14; // boolean
  wire phase_15; // boolean
  wire phase_17; // boolean
  wire phase_18; // boolean
  wire phase_20; // boolean
  wire phase_21; // boolean
  wire phase_23; // boolean
  wire signed [24:0] sectionipconvert; // sfix25_En24
  wire signed [41:0] storagetypeconvert; // sfix42_En23
  reg  signed [24:0] prev_stg_op1; // sfix25_En24
  reg  signed [24:0] prev_stg_op2; // sfix25_En24
  reg  signed [24:0] prev_stg_op3; // sfix25_En24
  reg  signed [41:0] storage_state_in1; // sfix42_En23
  reg  signed [41:0] delay_section1 [0:1] ; // sfix42_En23
  reg  signed [41:0] storage_state_in2; // sfix42_En23
  reg  signed [41:0] delay_section2 [0:1] ; // sfix42_En23
  reg  signed [41:0] storage_state_in3; // sfix42_En23
  reg  signed [41:0] delay_section3 [0:1] ; // sfix42_En23
  reg  signed [41:0] storage_state_in4; // sfix42_En23
  reg  signed [41:0] delay_section4 [0:1] ; // sfix42_En23
  wire signed [42:0] input_section1_cast; // sfix43_En24
  wire signed [42:0] storage_in_section1_cast; // sfix43_En24
  wire signed [42:0] delay_section11_cast; // sfix43_En24
  wire signed [42:0] delay_section12_cast; // sfix43_En24
  wire signed [42:0] input_section2_cast; // sfix43_En24
  wire signed [42:0] storage_in_section2_cast; // sfix43_En24
  wire signed [42:0] delay_section21_cast; // sfix43_En24
  wire signed [42:0] delay_section22_cast; // sfix43_En24
  wire signed [42:0] input_section3_cast; // sfix43_En24
  wire signed [42:0] storage_in_section3_cast; // sfix43_En24
  wire signed [42:0] delay_section31_cast; // sfix43_En24
  wire signed [42:0] delay_section32_cast; // sfix43_En24
  wire signed [42:0] input_section4_cast; // sfix43_En24
  wire signed [42:0] storage_in_section4_cast; // sfix43_En24
  wire signed [42:0] delay_section41_cast; // sfix43_En24
  wire signed [42:0] delay_section42_cast; // sfix43_En24
  wire signed [61:0] prod_den; // sfix62_En41
  wire signed [63:0] prod_den_cast_temp; // sfix64_En41
  wire signed [63:0] prod_den_cast; // sfix64_En41
  wire signed [63:0] prod_den_cast_neg; // sfix64_En41
  wire signed [64:0] unaryminus_temp; // sfix65_En41
  wire signed [61:0] prod_num; // sfix62_En41
  wire signed [63:0] prod_num_cast_temp; // sfix64_En41
  wire signed [63:0] prod_num_cast; // sfix64_En41
  wire signed [63:0] accum_mux_in1; // sfix64_En41
  wire signed [63:0] accum_mux_in2; // sfix64_En41
  wire signed [63:0] accum_mux_out; // sfix64_En41
  wire signed [63:0] accum_mux_in1_temp; // sfix64_En41
  wire signed [63:0] sectionipconvert_cast; // sfix64_En41
  wire final_phase; // boolean
  wire section_phase; // boolean
  reg  signed [63:0] accum_reg; // sfix64_En41
  wire signed [63:0] add_cast; // sfix64_En41
  wire signed [63:0] add_cast_1; // sfix64_En41
  wire signed [64:0] add_temp; // sfix65_En41
  wire signed [63:0] acc_out_cast_numacc; // sfix64_En41
  wire signed [24:0] sectionopconvert; // sfix25_En24
  wire signed [24:0] output_typeconvert; // sfix25_En24
  reg  signed [24:0] output_register; // sfix25_En24

assign          input_register = ~sign_en?  $signed({1'b0,filter_in})-25'sh0_80_0000 : {{2{filter_in[23]}},filter_in[22:0]};


  assign  phase_0 = (cur_count == 5'b00000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_2 = (cur_count == 5'b00010 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_3 = (cur_count == 5'b00011 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_5 = (cur_count == 5'b00101 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_6 = (cur_count == 5'b00110 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_8 = (cur_count == 5'b01000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_9 = (cur_count == 5'b01001 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_11 = (cur_count == 5'b01011 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_12 = (cur_count == 5'b01100 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_14 = (cur_count == 5'b01110 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_15 = (cur_count == 5'b01111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_17 = (cur_count == 5'b10001 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_18 = (cur_count == 5'b10010 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_20 = (cur_count == 5'b10100 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_21 = (cur_count == 5'b10101 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_23 = (cur_count == 5'b10111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;


  // Next stage input = Previous stage output. Storing Previous stage output
  always @ (posedge clk or negedge reset)
    begin: prev_stg_op1_process
      if (reset == 1'b0) begin
        prev_stg_op1 <= 0;
      end
      else begin
        if (phase_5 == 1'b1) begin
          prev_stg_op1 <= sectionopconvert;
        end
      end
    end // prev_stg_op1_process

  always @ (posedge clk or negedge reset)
    begin: prev_stg_op2_process
      if (reset == 1'b0) begin
        prev_stg_op2 <= 0;
      end
      else begin
        if (phase_11 == 1'b1) begin
          prev_stg_op2 <= sectionopconvert;
        end
      end
    end // prev_stg_op2_process

  always @ (posedge clk or negedge reset)
    begin: prev_stg_op3_process
      if (reset == 1'b0) begin
        prev_stg_op3 <= 0;
      end
      else begin
        if (phase_17 == 1'b1) begin
          prev_stg_op3 <= sectionopconvert;
        end
      end
    end // prev_stg_op3_process

  always @ (posedge clk or negedge reset)
    begin: delay_process_section1
      if (reset == 1'b0) begin
        delay_section1[0] <= 42'h00000000000;
        delay_section1[1] <= 42'h00000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section1[1] <= delay_section1[0];
          delay_section1[0] <= storage_state_in1;
        end
      end
    end // delay_process_section1

  always @ (posedge clk or negedge reset)
    begin: delay_process_section2
      if (reset == 1'b0) begin
        delay_section2[0] <= 42'h00000000000;
        delay_section2[1] <= 42'h00000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section2[1] <= delay_section2[0];
          delay_section2[0] <= storage_state_in2;
        end
      end
    end // delay_process_section2

  always @ (posedge clk or negedge reset)
    begin: delay_process_section3
      if (reset == 1'b0) begin
        delay_section3[0] <= 42'h00000000000;
        delay_section3[1] <= 42'h00000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section3[1] <= delay_section3[0];
          delay_section3[0] <= storage_state_in3;
        end
      end
    end // delay_process_section3

  always @ (posedge clk or negedge reset)
    begin: delay_process_section4
      if (reset == 1'b0) begin
        delay_section4[0] <= 42'h00000000000;
        delay_section4[1] <= 42'h00000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section4[1] <= delay_section4[0];
          delay_section4[0] <= storage_state_in4;
        end
      end
    end // delay_process_section4

  // Making common precision for input and state 
  assign input_section1_cast = $signed({{18{input_register[24]}}, input_register});

  assign delay_section11_cast = $signed({delay_section1[0], 1'b0});

  assign delay_section12_cast = $signed({delay_section1[1], 1'b0});

  assign storage_in_section1_cast = $signed({storage_state_in1, 1'b0});

  assign input_section2_cast = $signed({{18{prev_stg_op1[24]}}, prev_stg_op1});

  assign delay_section21_cast = $signed({delay_section2[0], 1'b0});

  assign delay_section22_cast = $signed({delay_section2[1], 1'b0});

  assign storage_in_section2_cast = $signed({storage_state_in2, 1'b0});

  assign input_section3_cast = $signed({{18{prev_stg_op2[24]}}, prev_stg_op2});

  assign delay_section31_cast = $signed({delay_section3[0], 1'b0});

  assign delay_section32_cast = $signed({delay_section3[1], 1'b0});

  assign storage_in_section3_cast = $signed({storage_state_in3, 1'b0});

  assign input_section4_cast = $signed({{18{prev_stg_op3[24]}}, prev_stg_op3});

  assign delay_section41_cast = $signed({delay_section4[0], 1'b0});

  assign delay_section42_cast = $signed({delay_section4[1], 1'b0});

  assign storage_in_section4_cast = $signed({storage_state_in4, 1'b0});

  assign inputmux_section_1 = (cur_count == 5'b00000) ? input_section1_cast :
                             (cur_count == 5'b00001) ? delay_section11_cast :
                             (cur_count == 5'b00010) ? delay_section12_cast :
                             (cur_count == 5'b00011) ? storage_in_section1_cast :
                             (cur_count == 5'b00100) ? delay_section11_cast :
                             (cur_count == 5'b00101) ? delay_section12_cast :
                             (cur_count == 5'b00110) ? input_section2_cast :
                             (cur_count == 5'b00111) ? delay_section21_cast :
                             (cur_count == 5'b01000) ? delay_section22_cast :
                             (cur_count == 5'b01001) ? storage_in_section2_cast :
                             (cur_count == 5'b01010) ? delay_section21_cast :
                             (cur_count == 5'b01011) ? delay_section22_cast :
                             (cur_count == 5'b01100) ? input_section3_cast :
                             (cur_count == 5'b01101) ? delay_section31_cast :
                             (cur_count == 5'b01110) ? delay_section32_cast :
                             (cur_count == 5'b01111) ? storage_in_section3_cast :
                             (cur_count == 5'b10000) ? delay_section31_cast :
                             (cur_count == 5'b10001) ? delay_section32_cast :
                             (cur_count == 5'b10010) ? input_section4_cast :
                             (cur_count == 5'b10011) ? delay_section41_cast :
                             (cur_count == 5'b10100) ? delay_section42_cast :
                             (cur_count == 5'b10101) ? storage_in_section4_cast :
                             (cur_count == 5'b10110) ? delay_section41_cast :
                             delay_section42_cast;

  assign coeffmux_section_1 = (cur_count == 5'b00000) ? scaleconst1 :
                             (cur_count == 5'b00001) ? coeff_a2_section1 :
                             (cur_count == 5'b00010) ? coeff_a3_section1 :
                             (cur_count == 5'b00011) ? coeff_b1_section1 :
                             (cur_count == 5'b00100) ? coeff_b2_section1 :
                             (cur_count == 5'b00101) ? coeff_b3_section1 :
                             (cur_count == 5'b00110) ? scaleconst2 :
                             (cur_count == 5'b00111) ? coeff_a2_section2 :
                             (cur_count == 5'b01000) ? coeff_a3_section2 :
                             (cur_count == 5'b01001) ? coeff_b1_section2 :
                             (cur_count == 5'b01010) ? coeff_b2_section2 :
                             (cur_count == 5'b01011) ? coeff_b3_section2 :
                             (cur_count == 5'b01100) ? scaleconst3 :
                             (cur_count == 5'b01101) ? coeff_a2_section3 :
                             (cur_count == 5'b01110) ? coeff_a3_section3 :
                             (cur_count == 5'b01111) ? coeff_b1_section3 :
                             (cur_count == 5'b10000) ? coeff_b2_section3 :
                             (cur_count == 5'b10001) ? coeff_b3_section3 :
                             (cur_count == 5'b10010) ? scaleconst4 :
                             (cur_count == 5'b10011) ? coeff_a2_section4 :
                             (cur_count == 5'b10100) ? coeff_a3_section4 :
                             (cur_count == 5'b10101) ? coeff_b1_section4 :
                             (cur_count == 5'b10110) ? coeff_b2_section4 :
                             coeff_b3_section4;

//  assign prod = inputmux_section_1 * coeffmux_section_1;

  assign prod_den = (prod[62] == 1'b0 && prod[61:0] == 62'b11111111111111111111111111111111111111111111111111111111111111) ? 62'b01111111111111111111111111111111111111111111111111111111111111 : (prod[62:0] + prod[1])>>>1;

  assign prod_den_cast_temp = $signed({{2{prod_den[61]}}, prod_den});

  assign prod_den_cast = prod_den_cast_temp;

  assign unaryminus_temp = (prod_den_cast==64'b1000000000000000000000000000000000000000000000000000000000000000) ? $signed({1'b0, prod_den_cast}) : -prod_den_cast;
  assign prod_den_cast_neg = ((unaryminus_temp[64] == 1'b0 & unaryminus_temp[63] != 1'b0) || (unaryminus_temp[64] == 1'b0 && unaryminus_temp[63:0] == 64'b0111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 64'b0111111111111111111111111111111111111111111111111111111111111111 : 
      (unaryminus_temp[64] == 1'b1 && unaryminus_temp[63] != 1'b1) ? 64'b1000000000000000000000000000000000000000000000000000000000000000 : unaryminus_temp[63:0];

  assign prod_num = (prod[62] == 1'b0 && prod[61:0] == 62'b11111111111111111111111111111111111111111111111111111111111111) ? 62'b01111111111111111111111111111111111111111111111111111111111111 : (prod[62:0] + prod[1])>>>1;

  assign prod_num_cast_temp = $signed({{2{prod_num[61]}}, prod_num});

  assign prod_num_cast = prod_num_cast_temp;

  assign accum_mux_in1 = (cur_count == 5'b00000) ? prod_num_cast :
                        (cur_count == 5'b00001) ? prod_den_cast_neg :
                        (cur_count == 5'b00010) ? prod_den_cast_neg :
                        (cur_count == 5'b00011) ? prod_num_cast :
                        (cur_count == 5'b00100) ? prod_num_cast :
                        (cur_count == 5'b00101) ? prod_num_cast :
                        (cur_count == 5'b00110) ? prod_num_cast :
                        (cur_count == 5'b00111) ? prod_den_cast_neg :
                        (cur_count == 5'b01000) ? prod_den_cast_neg :
                        (cur_count == 5'b01001) ? prod_num_cast :
                        (cur_count == 5'b01010) ? prod_num_cast :
                        (cur_count == 5'b01011) ? prod_num_cast :
                        (cur_count == 5'b01100) ? prod_num_cast :
                        (cur_count == 5'b01101) ? prod_den_cast_neg :
                        (cur_count == 5'b01110) ? prod_den_cast_neg :
                        (cur_count == 5'b01111) ? prod_num_cast :
                        (cur_count == 5'b10000) ? prod_num_cast :
                        (cur_count == 5'b10001) ? prod_num_cast :
                        (cur_count == 5'b10010) ? prod_num_cast :
                        (cur_count == 5'b10011) ? prod_den_cast_neg :
                        (cur_count == 5'b10100) ? prod_den_cast_neg :
                        (cur_count == 5'b10101) ? prod_num_cast :
                        (cur_count == 5'b10110) ? prod_num_cast :
                        prod_num_cast;

  assign final_phase =  phase_0 | phase_3 | phase_6 | phase_9 | phase_12 | phase_15 | phase_18 | phase_21;

  assign section_phase =  phase_0 | phase_6 | phase_12 | phase_18;

  assign accum_mux_in1_temp = (section_phase == 1'b1) ? sectionipconvert_cast :
                             accum_mux_in1;

  assign accum_mux_out = (final_phase == 1'b1) ? accum_mux_in1_temp :
                        accum_mux_in2;

  always @ (posedge clk or negedge reset)
    begin: accumulator_reg_process
      if (reset == 1'b0) begin
        accum_reg <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          accum_reg <= accum_mux_out;
        end
      end
    end // accumulator_reg_process

  assign add_cast = accum_reg;
  assign add_cast_1 = accum_mux_in1;
  assign add_temp = add_cast + add_cast_1;
  assign accum_mux_in2 = ((add_temp[64] == 1'b0 & add_temp[63] != 1'b0) || (add_temp[64] == 1'b0 && add_temp[63:0] == 64'b0111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 64'b0111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp[64] == 1'b1 && add_temp[63] != 1'b1) ? 64'b1000000000000000000000000000000000000000000000000000000000000000 : add_temp[63:0];

  assign storagetypeconvert = ((accum_mux_out[63] == 1'b0 & accum_mux_out[62:59] != 4'b0000) || (accum_mux_out[63] == 1'b0 && accum_mux_out[59:18] == 42'b011111111111111111111111111111111111111111) // special case0
) ? 42'b011111111111111111111111111111111111111111 : 
      (accum_mux_out[63] == 1'b1 && accum_mux_out[62:59] != 4'b1111) ? 42'b100000000000000000000000000000000000000000 : (accum_mux_out[59:0] + {accum_mux_out[18], {17{~accum_mux_out[18]}}})>>>18;

  assign sectionipconvert = ((prod[62] == 1'b0 & prod[61:42] != 20'b00000000000000000000) || (prod[62] == 1'b0 && prod[42:18] == 25'b0111111111111111111111111) // special case0
) ? 25'b0111111111111111111111111 : 
      (prod[62] == 1'b1 && prod[61:42] != 20'b11111111111111111111) ? 25'b1000000000000000000000000 : (prod[42:0] + {prod[18], {17{~prod[18]}}})>>>18;

  assign sectionipconvert_cast = $signed({sectionipconvert, 17'b00000000000000000});

  assign acc_out_cast_numacc = accum_mux_out;

  assign sectionopconvert = ((acc_out_cast_numacc[63] == 1'b0 & acc_out_cast_numacc[62:41] != 22'b0000000000000000000000) || (acc_out_cast_numacc[63] == 1'b0 && acc_out_cast_numacc[41:17] == 25'b0111111111111111111111111) // special case0
) ? 25'b0111111111111111111111111 : 
      (acc_out_cast_numacc[63] == 1'b1 && acc_out_cast_numacc[62:41] != 22'b1111111111111111111111) ? 25'b1000000000000000000000000 : (acc_out_cast_numacc[41:0] + {acc_out_cast_numacc[17], {16{~acc_out_cast_numacc[17]}}})>>>17;

  assign output_typeconvert = ((acc_out_cast_numacc[63] == 1'b0 & acc_out_cast_numacc[62:41] != 22'b0000000000000000000000) || (acc_out_cast_numacc[63] == 1'b0 && acc_out_cast_numacc[41:17] == 25'b0111111111111111111111111) // special case0
) ? 25'b0111111111111111111111111 : 
      (acc_out_cast_numacc[63] == 1'b1 && acc_out_cast_numacc[62:41] != 22'b1111111111111111111111) ? 25'b1000000000000000000000000 : (acc_out_cast_numacc[41:0] + {acc_out_cast_numacc[17], {16{~acc_out_cast_numacc[17]}}})>>>17;

  always @ (posedge clk or negedge reset)
    begin: storage_reg1_process
      if (reset == 1'b0) begin
        storage_state_in1 <= 0;
      end
      else begin
        if (phase_2 == 1'b1) begin
          storage_state_in1 <= storagetypeconvert;
        end
      end
    end // storage_reg1_process

  always @ (posedge clk or negedge reset)
    begin: storage_reg2_process
      if (reset == 1'b0) begin
        storage_state_in2 <= 0;
      end
      else begin
        if (phase_8 == 1'b1) begin
          storage_state_in2 <= storagetypeconvert;
        end
      end
    end // storage_reg2_process

  always @ (posedge clk or negedge reset)
    begin: storage_reg3_process
      if (reset == 1'b0) begin
        storage_state_in3 <= 0;
      end
      else begin
        if (phase_14 == 1'b1) begin
          storage_state_in3 <= storagetypeconvert;
        end
      end
    end // storage_reg3_process

  always @ (posedge clk or negedge reset)
    begin: storage_reg4_process
      if (reset == 1'b0) begin
        storage_state_in4 <= 0;
      end
      else begin
        if (phase_20 == 1'b1) begin
          storage_state_in4 <= storagetypeconvert;
        end
      end
    end // storage_reg4_process

  always @ (posedge clk or negedge reset)
    begin: Output_Register_process
      if (reset == 1'b0) begin
        output_register <= 0;
      end
      else begin
        if (phase_23 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process
   wire [23:0] output_register_temp; 
 assign output_register_temp = (output_register[24:23]==2'b10)? 24'h80_0000 : (output_register[24:23]==2'b01)? 24'h7f_ffff : output_register[23:0];
 assign filter_out = bypass? filter_in : ~sign_en? output_register_temp[23:0] + 24'h80_0000 : output_register_temp[23:0];

endmodule  // filter_notch










