// -------------------------------------------------------------
//
// Module: filter_comp
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-08-05 17:17:35
// -------------------------------------------------------------
//========================================================================================  
// ----------------------------------------------------------------------------- 
//  Nanochap Electronics Copyright (C) 2014. ALL RIGHTS RESERVED. 
// ----------------------------------------------------------------------------- 
// Module name     : notch_filter
// Description     : this is notch filter for 50hz; the order is 4, section is 2
// ======================================================================================= 
// =osr_sel :(4'h0~4'h1 and 4'hc~4'hf) is not supported
// =value 4'h0 - 4'h1 - 4'h2 - 4'h3 - 4'h4 - 4'h5 - 4'h6 - 4'h7 - 4'h8 - 4'h9 - 4'ha - 4'hb  
// =OSR    x   -  x   -  32  - 64   - 128  - 256  - 512  - 1024 - 2048 - 4096 - 8192 - 16384 
// =Fs                   64k    32k    16k    8k     4K     2k     1K    512    256   128   //hz
// =Fpass1               46.5   46.5   46.5   46.5   46.5   46.5   46.5  46.5   46.5   46.5  //hz
// =Fstop1               48.9   48.9   48.9   48.9   48.9   48.9   48.9  48.9   49     49    //hz
// =Fpass2               51.1   51.1   51.1   51.1   51.1   51.1   51.1  51.1   51     51    //hz
// =Fstop2               53.75  53.75  53.75  53.75  53.75  53.75  53.75 53.75  53.75  53.7  //hz
// =Apass1                       3     3      3     3      3      3      3       3   //dB
// =Astop                        20    20     20    20     20     20     20      20  //dB
// =Apass2                       3     3      3     3      3      3      3       3   //dB
// ======================================================================================= 
// =sign_en:
// =value        1'b0     -   1'b1 
// =signed?    unsigned   -  signed   
// ======================================================================================= 
// ----------------------------------------------------------------------------- 
// Revision History: 
// ----------------------------------------------------------------------------- 
// Revision       Date(xxxx-xx-xx)     Author             Description 
// ----------------------------------------------------------------------------- 
//   1.0          2025-9-15         Zhen Cao           Initial version 
// ----------------------------------------------------------------------------- 
//======================================================================================== 

module notch_filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
		sign_en,
//		osr_sel,
		bypass,
		o_cur_count,
		notch_coeff_data,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   sign_en;  
  input   bypass; 
//  input          [3:0]  osr_sel;
  input   signed [31:0] filter_in; //sfix33
  output  signed [31:0] filter_out; //sfix33
  output   wire  [5:0]  o_cur_count;
  input wire  signed [19:0] notch_coeff_data[41:0];

////////////////////////////////////////////////////////////////
//Module Architecture: filter_notch
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants

  wire signed [19:0] scaleconst1      ; 
wire signed [19:0] coeff_b1_section1; 
wire signed [19:0] coeff_b2_section1; 
wire signed [19:0] coeff_b3_section1; 
wire signed [19:0] coeff_a2_section1; 
wire signed [19:0] coeff_a3_section1; 
wire signed [19:0] scaleconst2      ; 
wire signed [19:0] coeff_b1_section2; 
wire signed [19:0] coeff_b2_section2; 
wire signed [19:0] coeff_b3_section2; 
wire signed [19:0] coeff_a2_section2; 
wire signed [19:0] coeff_a3_section2; 
wire signed [19:0] scaleconst3      ; 
wire signed [19:0] coeff_b1_section3; 
wire signed [19:0] coeff_b2_section3; 
wire signed [19:0] coeff_b3_section3; 
wire signed [19:0] coeff_a2_section3; 
wire signed [19:0] coeff_a3_section3; 
wire signed [19:0] scaleconst4      ; 
wire signed [19:0] coeff_b1_section4; 
wire signed [19:0] coeff_b2_section4; 
wire signed [19:0] coeff_b3_section4; 
wire signed [19:0] coeff_a2_section4; 
wire signed [19:0] coeff_a3_section4; 
wire signed [19:0] scaleconst5      ; 
wire signed [19:0] coeff_b1_section5; 
wire signed [19:0] coeff_b2_section5; 
wire signed [19:0] coeff_b3_section5; 
wire signed [19:0] coeff_a2_section5; 
wire signed [19:0] coeff_a3_section5; 
wire signed [19:0] scaleconst6      ; 
wire signed [19:0] coeff_b1_section6; 
wire signed [19:0] coeff_b2_section6; 
wire signed [19:0] coeff_b3_section6; 
wire signed [19:0] coeff_a2_section6; 
wire signed [19:0] coeff_a3_section6; 
wire signed [19:0] scaleconst7      ; 
wire signed [19:0] coeff_b1_section7; 
wire signed [19:0] coeff_b2_section7; 
wire signed [19:0] coeff_b3_section7; 
wire signed [19:0] coeff_a2_section7; 
wire signed [19:0] coeff_a3_section7; 


assign scaleconst1       = notch_coeff_data[0]; //sfix20_En18
assign coeff_b1_section1 = notch_coeff_data[1]; //sfix20_En18
assign coeff_b2_section1 = notch_coeff_data[2]; //sfix20_En18
assign coeff_b3_section1 = notch_coeff_data[3]; //sfix20_En18
assign coeff_a2_section1 = notch_coeff_data[4]; //sfix20_En18
assign coeff_a3_section1 = notch_coeff_data[5]; //sfix20_En18
assign scaleconst2       = notch_coeff_data[6]; //sfix20_En18
assign coeff_b1_section2 = notch_coeff_data[7]; //sfix20_En18
assign coeff_b2_section2 = notch_coeff_data[8]; //sfix20_En18
assign coeff_b3_section2 = notch_coeff_data[9]; //sfix20_En18
assign coeff_a2_section2 = notch_coeff_data[10]; //sfix20_En18
assign coeff_a3_section2 = notch_coeff_data[11]; //sfix20_En18
assign scaleconst3       = notch_coeff_data[12]; //sfix20_En18
assign coeff_b1_section3 = notch_coeff_data[13]; //sfix20_En18
assign coeff_b2_section3 = notch_coeff_data[14]; //sfix20_En18
assign coeff_b3_section3 = notch_coeff_data[15]; //sfix20_En18
assign coeff_a2_section3 = notch_coeff_data[16]; //sfix20_En18
assign coeff_a3_section3 = notch_coeff_data[17]; //sfix20_En18
assign scaleconst4       = notch_coeff_data[18]; //sfix20_En18
assign coeff_b1_section4 = notch_coeff_data[19]; //sfix20_En18
assign coeff_b2_section4 = notch_coeff_data[20]; //sfix20_En18
assign coeff_b3_section4 = notch_coeff_data[21]; //sfix20_En18
assign coeff_a2_section4 = notch_coeff_data[22]; //sfix20_En18
assign coeff_a3_section4 = notch_coeff_data[23]; //sfix20_En18
assign scaleconst5       = notch_coeff_data[24]; //sfix20_En18
assign coeff_b1_section5 = notch_coeff_data[25]; //sfix20_En18
assign coeff_b2_section5 = notch_coeff_data[26]; //sfix20_En18
assign coeff_b3_section5 = notch_coeff_data[27]; //sfix20_En18
assign coeff_a2_section5 = notch_coeff_data[28]; //sfix20_En18
assign coeff_a3_section5 = notch_coeff_data[29]; //sfix20_En18
assign scaleconst6       = notch_coeff_data[30]; //sfix20_En18
assign coeff_b1_section6 = notch_coeff_data[31]; //sfix20_En18
assign coeff_b2_section6 = notch_coeff_data[32]; //sfix20_En18
assign coeff_b3_section6 = notch_coeff_data[33]; //sfix20_En18
assign coeff_a2_section6 = notch_coeff_data[34]; //sfix20_En18
assign coeff_a3_section6 = notch_coeff_data[35]; //sfix20_En18
assign scaleconst7       = notch_coeff_data[36]; //sfix20_En18
assign coeff_b1_section7 = notch_coeff_data[37]; //sfix20_En18
assign coeff_b2_section7 = notch_coeff_data[38]; //sfix20_En18
assign coeff_b3_section7 = notch_coeff_data[39]; //sfix20_En18
assign coeff_a2_section7 = notch_coeff_data[40]; //sfix20_En18
assign coeff_a3_section7 = notch_coeff_data[41]; //sfix20_En18

  // Signals
  reg  signed [32:0] input_register; // sfix33_En33
  reg  [5:0] cur_count; // ufix6
    assign o_cur_count = cur_count;  
  wire phase_0; // boolean
  wire phase_2; // boolean
  wire phase_3; // boolean
  wire phase_5; // boolean
  wire phase_6; // boolean
  wire phase_8; // boolean
  wire phase_9; // boolean
  wire phase_11; // boolean
  wire phase_12; // boolean
  wire phase_14; // boolean
  wire phase_15; // boolean
  wire phase_17; // boolean
  wire phase_18; // boolean
  wire phase_20; // boolean
  wire phase_21; // boolean
  wire phase_23; // boolean
  wire phase_24; // boolean
  wire phase_26; // boolean
  wire phase_27; // boolean
  wire phase_29; // boolean
  wire phase_30; // boolean
  wire phase_32; // boolean
  wire phase_33; // boolean
  wire phase_35; // boolean
  wire phase_36; // boolean
  wire phase_38; // boolean
  wire phase_39; // boolean
  wire phase_41; // boolean
  wire signed [32:0] sectionipconvert; // sfix33_En33
  wire signed [49:0] storagetypeconvert; // sfix50_En25
  reg  signed [32:0] prev_stg_op1; // sfix33_En33
  reg  signed [32:0] prev_stg_op2; // sfix33_En33
  reg  signed [32:0] prev_stg_op3; // sfix33_En33
  reg  signed [32:0] prev_stg_op4; // sfix33_En33
  reg  signed [32:0] prev_stg_op5; // sfix33_En33
  reg  signed [32:0] prev_stg_op6; // sfix33_En33
  reg  signed [49:0] storage_state_in1; // sfix50_En25
  reg  signed [49:0] delay_section1 [0:1] ; // sfix50_En25
  reg  signed [49:0] storage_state_in2; // sfix50_En25
  reg  signed [49:0] delay_section2 [0:1] ; // sfix50_En25
  reg  signed [49:0] storage_state_in3; // sfix50_En25
  reg  signed [49:0] delay_section3 [0:1] ; // sfix50_En25
  reg  signed [49:0] storage_state_in4; // sfix50_En25
  reg  signed [49:0] delay_section4 [0:1] ; // sfix50_En25
  reg  signed [49:0] storage_state_in5; // sfix50_En25
  reg  signed [49:0] delay_section5 [0:1] ; // sfix50_En25
  reg  signed [49:0] storage_state_in6; // sfix50_En25
  reg  signed [49:0] delay_section6 [0:1] ; // sfix50_En25
  reg  signed [49:0] storage_state_in7; // sfix50_En25
  reg  signed [49:0] delay_section7 [0:1] ; // sfix50_En25
  wire signed [57:0] input_section1_cast; // sfix58_En33
  wire signed [57:0] storage_in_section1_cast; // sfix58_En33
  wire signed [57:0] delay_section11_cast; // sfix58_En33
  wire signed [57:0] delay_section12_cast; // sfix58_En33
  wire signed [57:0] input_section2_cast; // sfix58_En33
  wire signed [57:0] storage_in_section2_cast; // sfix58_En33
  wire signed [57:0] delay_section21_cast; // sfix58_En33
  wire signed [57:0] delay_section22_cast; // sfix58_En33
  wire signed [57:0] input_section3_cast; // sfix58_En33
  wire signed [57:0] storage_in_section3_cast; // sfix58_En33
  wire signed [57:0] delay_section31_cast; // sfix58_En33
  wire signed [57:0] delay_section32_cast; // sfix58_En33
  wire signed [57:0] input_section4_cast; // sfix58_En33
  wire signed [57:0] storage_in_section4_cast; // sfix58_En33
  wire signed [57:0] delay_section41_cast; // sfix58_En33
  wire signed [57:0] delay_section42_cast; // sfix58_En33
  wire signed [57:0] input_section5_cast; // sfix58_En33
  wire signed [57:0] storage_in_section5_cast; // sfix58_En33
  wire signed [57:0] delay_section51_cast; // sfix58_En33
  wire signed [57:0] delay_section52_cast; // sfix58_En33
  wire signed [57:0] input_section6_cast; // sfix58_En33
  wire signed [57:0] storage_in_section6_cast; // sfix58_En33
  wire signed [57:0] delay_section61_cast; // sfix58_En33
  wire signed [57:0] delay_section62_cast; // sfix58_En33
  wire signed [57:0] input_section7_cast; // sfix58_En33
  wire signed [57:0] storage_in_section7_cast; // sfix58_En33
  wire signed [57:0] delay_section71_cast; // sfix58_En33
  wire signed [57:0] delay_section72_cast; // sfix58_En33
  wire signed [57:0] inputmux_section_1; // sfix58_En33
  wire signed [19:0] coeffmux_section_1; // sfix20_En18
  wire signed [77:0] prod; // sfix78_En51
  wire signed [69:0] prod_den; // sfix70_En43
  wire signed [71:0] prod_den_cast_temp; // sfix72_En43
  wire signed [71:0] prod_den_cast; // sfix72_En43
  wire signed [71:0] prod_den_cast_neg; // sfix72_En43
  wire signed [72:0] unaryminus_temp; // sfix73_En43
  wire signed [69:0] prod_num; // sfix70_En43
  wire signed [71:0] prod_num_cast_temp; // sfix72_En43
  wire signed [71:0] prod_num_cast; // sfix72_En43
  wire signed [71:0] accum_mux_in1; // sfix72_En43
  wire signed [71:0] accum_mux_in2; // sfix72_En43
  wire signed [71:0] accum_mux_out; // sfix72_En43
  wire signed [71:0] accum_mux_in1_temp; // sfix72_En43
  wire signed [71:0] sectionipconvert_cast; // sfix72_En43
  wire final_phase; // boolean
  wire section_phase; // boolean
  reg  signed [71:0] accum_reg; // sfix72_En43
  wire signed [71:0] add_cast; // sfix72_En43
  wire signed [71:0] add_cast_1; // sfix72_En43
  wire signed [72:0] add_temp; // sfix73_En43
  wire signed [71:0] acc_out_cast_numacc; // sfix72_En43
  wire signed [32:0] sectionopconvert; // sfix33_En33
  wire signed [32:0] output_typeconvert; // sfix33_En33
  reg  signed [32:0] output_register; // sfix33_En33

  // Block Statements
  always @ (posedge clk or negedge reset)
    begin: input_reg_process
      if (reset == 1'b0) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
//          input_register <= ~sign_en?  (filter_in==32'hffff_ffff)? 33'h8000_0000 :  (filter_in==32'h7fff_ffff)? 33'h0 : $signed({{2{~filter_in[31]}},filter_in[30:0]+1'b1}) : {{2{filter_in[31]}},filter_in[30:0]};
            input_register <= ~sign_en?  $signed({1'b0,filter_in})-33'sh0_8000_0000 : {{2{filter_in[31]}},filter_in[30:0]};
        end
      end
    end // input_reg_process

  always @ (posedge clk or negedge reset)
    begin: Counter_process
      if (reset == 1'b0) begin
        cur_count <= 6'b000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 6'b101001) begin
            cur_count <= 6'b000000;
          end
          else begin
            cur_count <= cur_count + 6'b000001;
          end
        end
      end
    end // Counter_process

  assign  phase_0 = (cur_count == 6'b000000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_2 = (cur_count == 6'b000010 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_3 = (cur_count == 6'b000011 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_5 = (cur_count == 6'b000101 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_6 = (cur_count == 6'b000110 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_8 = (cur_count == 6'b001000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_9 = (cur_count == 6'b001001 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_11 = (cur_count == 6'b001011 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_12 = (cur_count == 6'b001100 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_14 = (cur_count == 6'b001110 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_15 = (cur_count == 6'b001111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_17 = (cur_count == 6'b010001 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_18 = (cur_count == 6'b010010 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_20 = (cur_count == 6'b010100 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_21 = (cur_count == 6'b010101 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_23 = (cur_count == 6'b010111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_24 = (cur_count == 6'b011000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_26 = (cur_count == 6'b011010 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_27 = (cur_count == 6'b011011 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_29 = (cur_count == 6'b011101 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_30 = (cur_count == 6'b011110 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_32 = (cur_count == 6'b100000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_33 = (cur_count == 6'b100001 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_35 = (cur_count == 6'b100011 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_36 = (cur_count == 6'b100100 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_38 = (cur_count == 6'b100110 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_39 = (cur_count == 6'b100111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_41 = (cur_count == 6'b101001 && clk_enable == 1'b1) ? 1'b1 : 1'b0;


  // Next stage input = Previous stage output. Storing Previous stage output
  always @ (posedge clk or negedge reset)
    begin: prev_stg_op1_process
      if (reset == 1'b0) begin
        prev_stg_op1 <= 0;
      end
      else begin
        if (phase_5 == 1'b1) begin
          prev_stg_op1 <= sectionopconvert;
        end
      end
    end // prev_stg_op1_process

  always @ (posedge clk or negedge reset)
    begin: prev_stg_op2_process
      if (reset == 1'b0) begin
        prev_stg_op2 <= 0;
      end
      else begin
        if (phase_11 == 1'b1) begin
          prev_stg_op2 <= sectionopconvert;
        end
      end
    end // prev_stg_op2_process

  always @ (posedge clk or negedge reset)
    begin: prev_stg_op3_process
      if (reset == 1'b0) begin
        prev_stg_op3 <= 0;
      end
      else begin
        if (phase_17 == 1'b1) begin
          prev_stg_op3 <= sectionopconvert;
        end
      end
    end // prev_stg_op3_process

  always @ (posedge clk or negedge reset)
    begin: prev_stg_op4_process
      if (reset == 1'b0) begin
        prev_stg_op4 <= 0;
      end
      else begin
        if (phase_23 == 1'b1) begin
          prev_stg_op4 <= sectionopconvert;
        end
      end
    end // prev_stg_op4_process

  always @ (posedge clk or negedge reset)
    begin: prev_stg_op5_process
      if (reset == 1'b0) begin
        prev_stg_op5 <= 0;
      end
      else begin
        if (phase_29 == 1'b1) begin
          prev_stg_op5 <= sectionopconvert;
        end
      end
    end // prev_stg_op5_process

  always @ (posedge clk or negedge reset)
    begin: prev_stg_op6_process
      if (reset == 1'b0) begin
        prev_stg_op6 <= 0;
      end
      else begin
        if (phase_35 == 1'b1) begin
          prev_stg_op6 <= sectionopconvert;
        end
      end
    end // prev_stg_op6_process

  always @ (posedge clk or negedge reset)
    begin: delay_process_section1
      if (reset == 1'b0) begin
        delay_section1[0] <= 50'h0000000000000;
        delay_section1[1] <= 50'h0000000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section1[1] <= delay_section1[0];
          delay_section1[0] <= storage_state_in1;
        end
      end
    end // delay_process_section1

  always @ (posedge clk or negedge reset)
    begin: delay_process_section2
      if (reset == 1'b0) begin
        delay_section2[0] <= 50'h0000000000000;
        delay_section2[1] <= 50'h0000000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section2[1] <= delay_section2[0];
          delay_section2[0] <= storage_state_in2;
        end
      end
    end // delay_process_section2

  always @ (posedge clk or negedge reset)
    begin: delay_process_section3
      if (reset == 1'b0) begin
        delay_section3[0] <= 50'h0000000000000;
        delay_section3[1] <= 50'h0000000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section3[1] <= delay_section3[0];
          delay_section3[0] <= storage_state_in3;
        end
      end
    end // delay_process_section3

  always @ (posedge clk or negedge reset)
    begin: delay_process_section4
      if (reset == 1'b0) begin
        delay_section4[0] <= 50'h0000000000000;
        delay_section4[1] <= 50'h0000000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section4[1] <= delay_section4[0];
          delay_section4[0] <= storage_state_in4;
        end
      end
    end // delay_process_section4

  always @ (posedge clk or negedge reset)
    begin: delay_process_section5
      if (reset == 1'b0) begin
        delay_section5[0] <= 50'h0000000000000;
        delay_section5[1] <= 50'h0000000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section5[1] <= delay_section5[0];
          delay_section5[0] <= storage_state_in5;
        end
      end
    end // delay_process_section5

  always @ (posedge clk or negedge reset)
    begin: delay_process_section6
      if (reset == 1'b0) begin
        delay_section6[0] <= 50'h0000000000000;
        delay_section6[1] <= 50'h0000000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section6[1] <= delay_section6[0];
          delay_section6[0] <= storage_state_in6;
        end
      end
    end // delay_process_section6

  always @ (posedge clk or negedge reset)
    begin: delay_process_section7
      if (reset == 1'b0) begin
        delay_section7[0] <= 50'h0000000000000;
        delay_section7[1] <= 50'h0000000000000;
      end
      else begin
        if (phase_0 == 1'b1) begin
          delay_section7[1] <= delay_section7[0];
          delay_section7[0] <= storage_state_in7;
        end
      end
    end // delay_process_section7

  // Making common precision for input and state 
  assign input_section1_cast = $signed({{25{input_register[32]}}, input_register});

  assign delay_section11_cast = $signed({delay_section1[0], 8'b00000000});

  assign delay_section12_cast = $signed({delay_section1[1], 8'b00000000});

  assign storage_in_section1_cast = $signed({storage_state_in1, 8'b00000000});

  assign input_section2_cast = $signed({{25{prev_stg_op1[32]}}, prev_stg_op1});

  assign delay_section21_cast = $signed({delay_section2[0], 8'b00000000});

  assign delay_section22_cast = $signed({delay_section2[1], 8'b00000000});

  assign storage_in_section2_cast = $signed({storage_state_in2, 8'b00000000});

  assign input_section3_cast = $signed({{25{prev_stg_op2[32]}}, prev_stg_op2});

  assign delay_section31_cast = $signed({delay_section3[0], 8'b00000000});

  assign delay_section32_cast = $signed({delay_section3[1], 8'b00000000});

  assign storage_in_section3_cast = $signed({storage_state_in3, 8'b00000000});

  assign input_section4_cast = $signed({{25{prev_stg_op3[32]}}, prev_stg_op3});

  assign delay_section41_cast = $signed({delay_section4[0], 8'b00000000});

  assign delay_section42_cast = $signed({delay_section4[1], 8'b00000000});

  assign storage_in_section4_cast = $signed({storage_state_in4, 8'b00000000});

  assign input_section5_cast = $signed({{25{prev_stg_op4[32]}}, prev_stg_op4});

  assign delay_section51_cast = $signed({delay_section5[0], 8'b00000000});

  assign delay_section52_cast = $signed({delay_section5[1], 8'b00000000});

  assign storage_in_section5_cast = $signed({storage_state_in5, 8'b00000000});

  assign input_section6_cast = $signed({{25{prev_stg_op5[32]}}, prev_stg_op5});

  assign delay_section61_cast = $signed({delay_section6[0], 8'b00000000});

  assign delay_section62_cast = $signed({delay_section6[1], 8'b00000000});

  assign storage_in_section6_cast = $signed({storage_state_in6, 8'b00000000});

  assign input_section7_cast = $signed({{25{prev_stg_op6[32]}}, prev_stg_op6});

  assign delay_section71_cast = $signed({delay_section7[0], 8'b00000000});

  assign delay_section72_cast = $signed({delay_section7[1], 8'b00000000});

  assign storage_in_section7_cast = $signed({storage_state_in7, 8'b00000000});

  assign inputmux_section_1 = (cur_count == 6'b000000) ? input_section1_cast :
                             (cur_count == 6'b000001) ? delay_section11_cast :
                             (cur_count == 6'b000010) ? delay_section12_cast :
                             (cur_count == 6'b000011) ? storage_in_section1_cast :
                             (cur_count == 6'b000100) ? delay_section11_cast :
                             (cur_count == 6'b000101) ? delay_section12_cast :
                             (cur_count == 6'b000110) ? input_section2_cast :
                             (cur_count == 6'b000111) ? delay_section21_cast :
                             (cur_count == 6'b001000) ? delay_section22_cast :
                             (cur_count == 6'b001001) ? storage_in_section2_cast :
                             (cur_count == 6'b001010) ? delay_section21_cast :
                             (cur_count == 6'b001011) ? delay_section22_cast :
                             (cur_count == 6'b001100) ? input_section3_cast :
                             (cur_count == 6'b001101) ? delay_section31_cast :
                             (cur_count == 6'b001110) ? delay_section32_cast :
                             (cur_count == 6'b001111) ? storage_in_section3_cast :
                             (cur_count == 6'b010000) ? delay_section31_cast :
                             (cur_count == 6'b010001) ? delay_section32_cast :
                             (cur_count == 6'b010010) ? input_section4_cast :
                             (cur_count == 6'b010011) ? delay_section41_cast :
                             (cur_count == 6'b010100) ? delay_section42_cast :
                             (cur_count == 6'b010101) ? storage_in_section4_cast :
                             (cur_count == 6'b010110) ? delay_section41_cast :
                             (cur_count == 6'b010111) ? delay_section42_cast :
                             (cur_count == 6'b011000) ? input_section5_cast :
                             (cur_count == 6'b011001) ? delay_section51_cast :
                             (cur_count == 6'b011010) ? delay_section52_cast :
                             (cur_count == 6'b011011) ? storage_in_section5_cast :
                             (cur_count == 6'b011100) ? delay_section51_cast :
                             (cur_count == 6'b011101) ? delay_section52_cast :
                             (cur_count == 6'b011110) ? input_section6_cast :
                             (cur_count == 6'b011111) ? delay_section61_cast :
                             (cur_count == 6'b100000) ? delay_section62_cast :
                             (cur_count == 6'b100001) ? storage_in_section6_cast :
                             (cur_count == 6'b100010) ? delay_section61_cast :
                             (cur_count == 6'b100011) ? delay_section62_cast :
                             (cur_count == 6'b100100) ? input_section7_cast :
                             (cur_count == 6'b100101) ? delay_section71_cast :
                             (cur_count == 6'b100110) ? delay_section72_cast :
                             (cur_count == 6'b100111) ? storage_in_section7_cast :
                             (cur_count == 6'b101000) ? delay_section71_cast :
                             delay_section72_cast;

  assign coeffmux_section_1 = (cur_count == 6'b000000) ? scaleconst1 :
                             (cur_count == 6'b000001) ? coeff_a2_section1 :
                             (cur_count == 6'b000010) ? coeff_a3_section1 :
                             (cur_count == 6'b000011) ? coeff_b1_section1 :
                             (cur_count == 6'b000100) ? coeff_b2_section1 :
                             (cur_count == 6'b000101) ? coeff_b3_section1 :
                             (cur_count == 6'b000110) ? scaleconst2 :
                             (cur_count == 6'b000111) ? coeff_a2_section2 :
                             (cur_count == 6'b001000) ? coeff_a3_section2 :
                             (cur_count == 6'b001001) ? coeff_b1_section2 :
                             (cur_count == 6'b001010) ? coeff_b2_section2 :
                             (cur_count == 6'b001011) ? coeff_b3_section2 :
                             (cur_count == 6'b001100) ? scaleconst3 :
                             (cur_count == 6'b001101) ? coeff_a2_section3 :
                             (cur_count == 6'b001110) ? coeff_a3_section3 :
                             (cur_count == 6'b001111) ? coeff_b1_section3 :
                             (cur_count == 6'b010000) ? coeff_b2_section3 :
                             (cur_count == 6'b010001) ? coeff_b3_section3 :
                             (cur_count == 6'b010010) ? scaleconst4 :
                             (cur_count == 6'b010011) ? coeff_a2_section4 :
                             (cur_count == 6'b010100) ? coeff_a3_section4 :
                             (cur_count == 6'b010101) ? coeff_b1_section4 :
                             (cur_count == 6'b010110) ? coeff_b2_section4 :
                             (cur_count == 6'b010111) ? coeff_b3_section4 :
                             (cur_count == 6'b011000) ? scaleconst5 :
                             (cur_count == 6'b011001) ? coeff_a2_section5 :
                             (cur_count == 6'b011010) ? coeff_a3_section5 :
                             (cur_count == 6'b011011) ? coeff_b1_section5 :
                             (cur_count == 6'b011100) ? coeff_b2_section5 :
                             (cur_count == 6'b011101) ? coeff_b3_section5 :
                             (cur_count == 6'b011110) ? scaleconst6 :
                             (cur_count == 6'b011111) ? coeff_a2_section6 :
                             (cur_count == 6'b100000) ? coeff_a3_section6 :
                             (cur_count == 6'b100001) ? coeff_b1_section6 :
                             (cur_count == 6'b100010) ? coeff_b2_section6 :
                             (cur_count == 6'b100011) ? coeff_b3_section6 :
                             (cur_count == 6'b100100) ? scaleconst7 :
                             (cur_count == 6'b100101) ? coeff_a2_section7 :
                             (cur_count == 6'b100110) ? coeff_a3_section7 :
                             (cur_count == 6'b100111) ? coeff_b1_section7 :
                             (cur_count == 6'b101000) ? coeff_b2_section7 :
                             coeff_b3_section7;

  assign prod = inputmux_section_1 * coeffmux_section_1;

  assign prod_den = (prod[77] == 1'b0 && prod[76:7] == 70'b1111111111111111111111111111111111111111111111111111111111111111111111) ? 70'b0111111111111111111111111111111111111111111111111111111111111111111111 : (prod[77:0] + {prod[8], {7{~prod[8]}}})>>>8;

  assign prod_den_cast_temp = $signed({{2{prod_den[69]}}, prod_den});

  assign prod_den_cast = prod_den_cast_temp;

  assign unaryminus_temp = (prod_den_cast==72'b100000000000000000000000000000000000000000000000000000000000000000000000) ? $signed({1'b0, prod_den_cast}) : -prod_den_cast;
  assign prod_den_cast_neg = ((unaryminus_temp[72] == 1'b0 & unaryminus_temp[71] != 1'b0) || (unaryminus_temp[72] == 1'b0 && unaryminus_temp[71:0] == 72'b011111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 72'b011111111111111111111111111111111111111111111111111111111111111111111111 : 
      (unaryminus_temp[72] == 1'b1 && unaryminus_temp[71] != 1'b1) ? 72'b100000000000000000000000000000000000000000000000000000000000000000000000 : unaryminus_temp[71:0];

  assign prod_num = (prod[77] == 1'b0 && prod[76:7] == 70'b1111111111111111111111111111111111111111111111111111111111111111111111) ? 70'b0111111111111111111111111111111111111111111111111111111111111111111111 : (prod[77:0] + {prod[8], {7{~prod[8]}}})>>>8;

  assign prod_num_cast_temp = $signed({{2{prod_num[69]}}, prod_num});

  assign prod_num_cast = prod_num_cast_temp;

  assign accum_mux_in1 = (cur_count == 6'b000000) ? prod_num_cast :
                        (cur_count == 6'b000001) ? prod_den_cast_neg :
                        (cur_count == 6'b000010) ? prod_den_cast_neg :
                        (cur_count == 6'b000011) ? prod_num_cast :
                        (cur_count == 6'b000100) ? prod_num_cast :
                        (cur_count == 6'b000101) ? prod_num_cast :
                        (cur_count == 6'b000110) ? prod_num_cast :
                        (cur_count == 6'b000111) ? prod_den_cast_neg :
                        (cur_count == 6'b001000) ? prod_den_cast_neg :
                        (cur_count == 6'b001001) ? prod_num_cast :
                        (cur_count == 6'b001010) ? prod_num_cast :
                        (cur_count == 6'b001011) ? prod_num_cast :
                        (cur_count == 6'b001100) ? prod_num_cast :
                        (cur_count == 6'b001101) ? prod_den_cast_neg :
                        (cur_count == 6'b001110) ? prod_den_cast_neg :
                        (cur_count == 6'b001111) ? prod_num_cast :
                        (cur_count == 6'b010000) ? prod_num_cast :
                        (cur_count == 6'b010001) ? prod_num_cast :
                        (cur_count == 6'b010010) ? prod_num_cast :
                        (cur_count == 6'b010011) ? prod_den_cast_neg :
                        (cur_count == 6'b010100) ? prod_den_cast_neg :
                        (cur_count == 6'b010101) ? prod_num_cast :
                        (cur_count == 6'b010110) ? prod_num_cast :
                        (cur_count == 6'b010111) ? prod_num_cast :
                        (cur_count == 6'b011000) ? prod_num_cast :
                        (cur_count == 6'b011001) ? prod_den_cast_neg :
                        (cur_count == 6'b011010) ? prod_den_cast_neg :
                        (cur_count == 6'b011011) ? prod_num_cast :
                        (cur_count == 6'b011100) ? prod_num_cast :
                        (cur_count == 6'b011101) ? prod_num_cast :
                        (cur_count == 6'b011110) ? prod_num_cast :
                        (cur_count == 6'b011111) ? prod_den_cast_neg :
                        (cur_count == 6'b100000) ? prod_den_cast_neg :
                        (cur_count == 6'b100001) ? prod_num_cast :
                        (cur_count == 6'b100010) ? prod_num_cast :
                        (cur_count == 6'b100011) ? prod_num_cast :
                        (cur_count == 6'b100100) ? prod_num_cast :
                        (cur_count == 6'b100101) ? prod_den_cast_neg :
                        (cur_count == 6'b100110) ? prod_den_cast_neg :
                        (cur_count == 6'b100111) ? prod_num_cast :
                        (cur_count == 6'b101000) ? prod_num_cast :
                        prod_num_cast;

  assign final_phase =  phase_0 | phase_3 | phase_6 | phase_9 | phase_12 | phase_15 | phase_18 | phase_21 | phase_24 | phase_27 | phase_30 | phase_33 | phase_36 | phase_39;

  assign section_phase =  phase_0 | phase_6 | phase_12 | phase_18 | phase_24 | phase_30 | phase_36;

  assign accum_mux_in1_temp = (section_phase == 1'b1) ? sectionipconvert_cast :
                             accum_mux_in1;

  assign accum_mux_out = (final_phase == 1'b1) ? accum_mux_in1_temp :
                        accum_mux_in2;

  always @ (posedge clk or negedge reset)
    begin: accumulator_reg_process
      if (reset == 1'b0) begin
        accum_reg <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          accum_reg <= accum_mux_out;
        end
      end
    end // accumulator_reg_process

  assign add_cast = accum_reg;
  assign add_cast_1 = accum_mux_in1;
  assign add_temp = add_cast + add_cast_1;
  assign accum_mux_in2 = ((add_temp[72] == 1'b0 & add_temp[71] != 1'b0) || (add_temp[72] == 1'b0 && add_temp[71:0] == 72'b011111111111111111111111111111111111111111111111111111111111111111111111) // special case0
) ? 72'b011111111111111111111111111111111111111111111111111111111111111111111111 : 
      (add_temp[72] == 1'b1 && add_temp[71] != 1'b1) ? 72'b100000000000000000000000000000000000000000000000000000000000000000000000 : add_temp[71:0];

  assign storagetypeconvert = ((accum_mux_out[71] == 1'b0 & accum_mux_out[70:67] != 4'b0000) || (accum_mux_out[71] == 1'b0 && accum_mux_out[67:18] == 50'b01111111111111111111111111111111111111111111111111) // special case0
) ? 50'b01111111111111111111111111111111111111111111111111 : 
      (accum_mux_out[71] == 1'b1 && accum_mux_out[70:67] != 4'b1111) ? 50'b10000000000000000000000000000000000000000000000000 : (accum_mux_out[67:0] + {accum_mux_out[18], {17{~accum_mux_out[18]}}})>>>18;

  assign sectionipconvert = ((prod[77] == 1'b0 & prod[76:50] != 27'b000000000000000000000000000) || (prod[77] == 1'b0 && prod[50:18] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (prod[77] == 1'b1 && prod[76:50] != 27'b111111111111111111111111111) ? 33'b100000000000000000000000000000000 : (prod[50:0] + {prod[18], {17{~prod[18]}}})>>>18;

  assign sectionipconvert_cast = $signed({sectionipconvert, 10'b0000000000});

  assign acc_out_cast_numacc = accum_mux_out;

  assign sectionopconvert = ((acc_out_cast_numacc[71] == 1'b0 & acc_out_cast_numacc[70:42] != 29'b00000000000000000000000000000) || (acc_out_cast_numacc[71] == 1'b0 && acc_out_cast_numacc[42:10] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (acc_out_cast_numacc[71] == 1'b1 && acc_out_cast_numacc[70:42] != 29'b11111111111111111111111111111) ? 33'b100000000000000000000000000000000 : (acc_out_cast_numacc[42:0] + {acc_out_cast_numacc[10], {9{~acc_out_cast_numacc[10]}}})>>>10;

  assign output_typeconvert = ((acc_out_cast_numacc[71] == 1'b0 & acc_out_cast_numacc[70:42] != 29'b00000000000000000000000000000) || (acc_out_cast_numacc[71] == 1'b0 && acc_out_cast_numacc[42:10] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (acc_out_cast_numacc[71] == 1'b1 && acc_out_cast_numacc[70:42] != 29'b11111111111111111111111111111) ? 33'b100000000000000000000000000000000 : (acc_out_cast_numacc[42:0] + {acc_out_cast_numacc[10], {9{~acc_out_cast_numacc[10]}}})>>>10;

  always @ (posedge clk or negedge reset)
    begin: storage_reg1_process
      if (reset == 1'b0) begin
        storage_state_in1 <= 0;
      end
      else begin
        if (phase_2 == 1'b1) begin
          storage_state_in1 <= storagetypeconvert;
        end
      end
    end // storage_reg1_process

  always @ (posedge clk or negedge reset)
    begin: storage_reg2_process
      if (reset == 1'b0) begin
        storage_state_in2 <= 0;
      end
      else begin
        if (phase_8 == 1'b1) begin
          storage_state_in2 <= storagetypeconvert;
        end
      end
    end // storage_reg2_process

  always @ (posedge clk or negedge reset)
    begin: storage_reg3_process
      if (reset == 1'b0) begin
        storage_state_in3 <= 0;
      end
      else begin
        if (phase_14 == 1'b1) begin
          storage_state_in3 <= storagetypeconvert;
        end
      end
    end // storage_reg3_process

  always @ (posedge clk or negedge reset)
    begin: storage_reg4_process
      if (reset == 1'b0) begin
        storage_state_in4 <= 0;
      end
      else begin
        if (phase_20 == 1'b1) begin
          storage_state_in4 <= storagetypeconvert;
        end
      end
    end // storage_reg4_process

  always @ (posedge clk or negedge reset)
    begin: storage_reg5_process
      if (reset == 1'b0) begin
        storage_state_in5 <= 0;
      end
      else begin
        if (phase_26 == 1'b1) begin
          storage_state_in5 <= storagetypeconvert;
        end
      end
    end // storage_reg5_process

  always @ (posedge clk or negedge reset)
    begin: storage_reg6_process
      if (reset == 1'b0) begin
        storage_state_in6 <= 0;
      end
      else begin
        if (phase_32 == 1'b1) begin
          storage_state_in6 <= storagetypeconvert;
        end
      end
    end // storage_reg6_process

  always @ (posedge clk or negedge reset)
    begin: storage_reg7_process
      if (reset == 1'b0) begin
        storage_state_in7 <= 0;
      end
      else begin
        if (phase_38 == 1'b1) begin
          storage_state_in7 <= storagetypeconvert;
        end
      end
    end // storage_reg7_process

  always @ (posedge clk or negedge reset)
    begin: Output_Register_process
      if (reset == 1'b0) begin
        output_register <= 0;
      end
      else begin
        if (phase_41 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
   wire [31:0] output_register_temp; 
 assign output_register_temp = (output_register[32:31]==2'b10)? 32'h8000_0000 : (output_register[32:31]==2'b01)? 32'h7fff_ffff : output_register[31:0];
 assign filter_out = bypass? filter_in : ~sign_en? output_register_temp[31:0] + 32'h8000_0000 : output_register_temp[31:0];

endmodule  // filter_notch
