// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-09-22 21:15:11
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: hdlsrc_1000
// EDAScriptGeneration: off
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp 
// GenerateHDLTestBench: off

// Filter Specifications:
//
// Sample Rate   : N/A (normalized frequency)
// Response      : Highpass
// Specification : N,F3dB
// 3-dB Point    : 0.2
// Filter Order  : 1
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 1
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s16,14 -> [-2 2)
// Denominator         : s16,14 -> [-2 2)
// Scale Values        : s16,15 -> [-1 1)
// Input               : s32,0 -> [-2147483648 2147483648)
// Section Input       : s32,26 -> [-32 32)
// Section Output      : s32,27 -> [-16 16)
// Output              : s32,27 -> [-16 16)
// State               : s16,15 -> [-1 1)
// Numerator Prod      : s32,29 -> [-4 4)
// Denominator Prod    : s32,29 -> [-4 4)
// Numerator Accum     : s34,29 -> [-16 16)
// Denominator Accum   : s34,29 -> [-16 16)
// Round Mode          : convergent
// Overflow Mode       : wrap
// -------------------------------------------------------------
// Multipliers           : 2



`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [31:0] filter_in; //sfix32
  output  signed [31:0] filter_out; //sfix32_En27

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] scaleconst1 = 16'b0110000010011100; //sfix16_En15
  parameter signed [15:0] coeff_b1_section1 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_b2_section1 = 16'b1100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_b3_section1 = 16'b0000000000000000; //sfix16_En14
  parameter signed [15:0] coeff_a2_section1 = 16'b1101111101100100; //sfix16_En14
  parameter signed [15:0] coeff_a3_section1 = 16'b0000000000000000; //sfix16_En14
  // Signals
  reg  signed [31:0] input_register; // sfix32
  wire signed [74:0] scale1; // sfix75_En42
  wire signed [47:0] mul_temp; // sfix48_En15
  wire signed [31:0] scaletypeconvert1; // sfix32_En26
  //   -- Section 1 Signals 
  wire signed [33:0] a1sum1; // sfix34_En29
  wire signed [33:0] b1sum1; // sfix34_En29
  wire signed [15:0] a1sumtypeconvert1; // sfix16_En15
  reg  signed [15:0] delay_section1; // sfix16_En15
  wire signed [33:0] inputconv1; // sfix34_En29
  wire signed [31:0] a2mul1; // sfix32_En29
  wire signed [31:0] b1mul1; // sfix32_En29
  wire signed [31:0] b2mul1; // sfix32_En29
  wire signed [16:0] unaryminus_temp; // sfix17_En15
  wire signed [33:0] sub_cast; // sfix34_En29
  wire signed [33:0] sub_cast_1; // sfix34_En29
  wire signed [34:0] sub_temp; // sfix35_En29
  wire signed [33:0] b1multypeconvert1; // sfix34_En29
  wire signed [33:0] add_cast; // sfix34_En29
  wire signed [33:0] add_cast_1; // sfix34_En29
  wire signed [34:0] add_temp; // sfix35_En29
  wire signed [31:0] output_typeconvert; // sfix32_En27
  reg  signed [31:0] output_register; // sfix32_En27

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  assign mul_temp = input_register * scaleconst1;
  assign scale1 = $signed({mul_temp[47:0], 27'b000000000000000000000000000});

  assign scaletypeconvert1 = (scale1[47:0] + {scale1[16], {15{~scale1[16]}}})>>>16;

  //   ------------------ Section 1 (First Order) ------------------

  assign a1sumtypeconvert1 = (a1sum1[29:0] + {a1sum1[14], {13{~a1sum1[14]}}})>>>14;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section1
      if (reset == 1'b1) begin
        delay_section1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section1 <= a1sumtypeconvert1;
        end
      end
    end // delay_process_section1

  assign inputconv1 = $signed({scaletypeconvert1[30:0], 3'b000});

  assign a2mul1 = delay_section1 * coeff_a2_section1;

  assign b1mul1 = $signed({a1sumtypeconvert1[15:0], 14'b00000000000000});

  assign unaryminus_temp = (delay_section1==16'b1000000000000000) ? $signed({1'b0, delay_section1}) : -delay_section1;
  assign b2mul1 = $signed({unaryminus_temp[16:0], 14'b00000000000000});

  assign sub_cast = inputconv1;
  assign sub_cast_1 = $signed({{2{a2mul1[31]}}, a2mul1});
  assign sub_temp = sub_cast - sub_cast_1;
  assign a1sum1 = sub_temp[33:0];

  assign b1multypeconvert1 = $signed({{2{b1mul1[31]}}, b1mul1});

  assign add_cast = b1multypeconvert1;
  assign add_cast_1 = $signed({{2{b2mul1[31]}}, b2mul1});
  assign add_temp = add_cast + add_cast_1;
  assign b1sum1 = add_temp[33:0];

  assign output_typeconvert = (b1sum1[33:0] + {b1sum1[2], {1{~b1sum1[2]}}})>>>2;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
